## 이름 정제

In [1]:
import pandas as pd
from openai import OpenAI
import time

client = OpenAI(api_key="sktax-XyeKFrq67ZjS4EpsDlrHHXV8it", base_url="https://guest-api.sktax.chat/v1")

# CSV 읽기
recipes = pd.read_csv("recipes_easy.csv")

def clean_title_with_ai(title: str) -> str:
    prompt = (
        f"다음 요리 제목에서 불필요한 설명, 괄호 속 내용, 수식어를 제거하고 "
        f"순수한 음식 이름만 추출하세요.\n"
        f"순수한 음식 이름만 출력하고, 다른 말은 절대 하지 마세요.\n"
        f"입력: {title}\n"
        f"출력:"
    )

    completion = client.chat.completions.create(
        model="ax4",
        messages=[
            {"role": "user", "content": prompt}
        ]
    )

    return completion.choices[0].message.content.strip()

# 한 행씩 처리
cleaned_titles = []
for idx, row in recipes[:30].iterrows():
    cleaned = clean_title_with_ai(row["title"])
    cleaned_titles.append(cleaned)
    
    print(f"{idx+1}/{len(recipes)} 처리 완료: {cleaned}")

1/113 처리 완료: 떡꼬치
2/113 처리 완료: 계란빵 꿀빵
3/113 처리 완료: 고구마 빵
4/113 처리 완료: 코울슬로, 사라다빵
5/113 처리 완료: 또띠아 피자
6/113 처리 완료: 스파게티 샌드위치
7/113 처리 완료: 치즈 샌드위치
8/113 처리 완료: 양배추샌드위치
9/113 처리 완료: 샌드위치
10/113 처리 완료: 연어 샌드위치
11/113 처리 완료: 샌드위치
12/113 처리 완료: 닭가슴살샌드위치
13/113 처리 완료: 닭가슴살브리또
14/113 처리 완료: 샌드위치
15/113 처리 완료: 딸기롤샌드위치
16/113 처리 완료: 에그 샌드위치
17/113 처리 완료: 두부 계란찜
18/113 처리 완료: 몬테크리스토 샌드위치
19/113 처리 완료: 딸기샌드위치
20/113 처리 완료: 오픈샌드위치
21/113 처리 완료: 닭 가슴살 샐러드, 샌드위치
22/113 처리 완료: 아보카도 샌드위치
23/113 처리 완료: 베이컨 샌드위치
24/113 처리 완료: 스파이시슈림프샌드위치
25/113 처리 완료: 연어샌드위치
26/113 처리 완료: 오픈 샌드위치
27/113 처리 완료: 메추리알맛살샌드위치
28/113 처리 완료: 모닝롤
29/113 처리 완료: 버터비빔밥
30/113 처리 완료: 파니니샌드위치

In [4]:

for idx, row in recipes[30:60].iterrows():
    cleaned = clean_title_with_ai(row["title"])
    cleaned_titles.append(cleaned)
    
    print(f"{idx+1}/{len(recipes)} 처리 완료: {cleaned}")

31/113 처리 완료: 치즈샌드위치
32/113 처리 완료: 오징어 샐러드
33/113 처리 완료: 닭가슴살 무침
34/113 처리 완료: 게맛살 또띠아 샌드위치
35/113 처리 완료: 견과아몬드쿠키
36/113 처리 완료: 콩나물무침
37/113 처리 완료: 통 삼겹살
38/113 처리 완료: 옥수수치즈
39/113 처리 완료: 소고기
고구마
40/113 처리 완료: 웨지고구마
41/113 처리 완료: 누룽지
42/113 처리 완료: 떡꼬치
43/113 처리 완료: 크로크무슈
44/113 처리 완료: 브라질 치즈빵
45/113 처리 완료: 얼그레이 사브레 쿠키
46/113 처리 완료: 카레구이
47/113 처리 완료: 숙주나물무침
48/113 처리 완료: 마약달걀장
49/113 처리 완료: 멸치고추지볶음
50/113 처리 완료: 삼겹살김치파스타
51/113 처리 완료: 오믈렛
52/113 처리 완료: 볶음밥
53/113 처리 완료: 토마토 계란 피자
54/113 처리 완료: 마늘볶음밥
55/113 처리 완료: 알리오 올리오
56/113 처리 완료: 해물 토스트
57/113 처리 완료: 명란젓 마요계란밥
58/113 처리 완료: 메밀소바
59/113 처리 완료: 모짜프렌치토스트
60/113 처리 완료: 참치마요 주먹밥

In [6]:

for idx, row in recipes[60:90].iterrows():
    cleaned = clean_title_with_ai(row["title"])
    cleaned_titles.append(cleaned)
    
    print(f"{idx+1}/{len(recipes)} 처리 완료: {cleaned}")

61/113 처리 완료: 상추 주먹밥
62/113 처리 완료: 들기름 막국수
간장비빔메밀국수
63/113 처리 완료: 아보카도 참치마요 덮밥
64/113 처리 완료: 두부 덮밥
65/113 처리 완료: 마요네즈계란밥
66/113 처리 완료: 볶음밥
67/113 처리 완료: 버터비빔밥
68/113 처리 완료: 찹스테이크
69/113 처리 완료: 삼겹살 상추 조림
70/113 처리 완료: 야채 김 계란말이
71/113 처리 완료: 돈까스 샌드위치
72/113 처리 완료: 양배추 만둣국
73/113 처리 완료: 명란,된장
74/113 처리 완료: 참치샐러드
75/113 처리 완료: 카레 주먹밥
76/113 처리 완료: 열무김치국수
77/113 처리 완료: 치즈떡 계란말이
78/113 처리 완료: 비빔국수
79/113 처리 완료: 김치찌개
80/113 처리 완료: 콩나물국
81/113 처리 완료: 간장파스타
82/113 처리 완료: 국물떡볶이
83/113 처리 완료: 계란빵, 꿀빵
84/113 처리 완료: 연어 샐러드
85/113 처리 완료: 소세지야채볶음
86/113 처리 완료: 달걀 볶음밥
87/113 처리 완료: 두부찌개
88/113 처리 완료: 데리야키 닭고기
89/113 처리 완료: 몬테크리스토 시리얼 토스트
90/113 처리 완료: 김밥

In [7]:

for idx, row in recipes[90:113].iterrows():
    cleaned = clean_title_with_ai(row["title"])
    cleaned_titles.append(cleaned)
    
    print(f"{idx+1}/{len(recipes)} 처리 완료: {cleaned}")

91/113 처리 완료: 카레라이스
92/113 처리 완료: 쇠고기볶음
93/113 처리 완료: 김치부침개피자
94/113 처리 완료: 식빵피자
95/113 처리 완료: 콘치즈
96/113 처리 완료: 김치볶음밥
97/113 처리 완료: 꿀피자
98/113 처리 완료: 계란프라이
99/113 처리 완료: 프렌치 토스트
100/113 처리 완료: 감자
101/113 처리 완료: 계란죽
102/113 처리 완료: 크림우동
103/113 처리 완료: 밥버거
104/113 처리 완료: 스파게티
105/113 처리 완료: 계란찜
106/113 처리 완료: 토스트
107/113 처리 완료: 로제떡볶이
108/113 처리 완료: 꿀빵
109/113 처리 완료: 토스트
110/113 처리 완료: 피자계란밥
111/113 처리 완료: 볶음밥
112/113 처리 완료: 스팸계란밥
113/113 처리 완료: 계란찜

In [ ]:

# for idx, row in recipes[120:150].iterrows():
#     cleaned = clean_title_with_ai(row["title"])
#     cleaned_titles.append(cleaned)
    
#     print(f"{idx+1}/{len(recipes)} 처리 완료: {cleaned}")

121/251 처리 완료: 비빔만두
122/251 처리 완료: 부타동
123/251 처리 완료: 오레오 치즈케이크
124/251 처리 완료: 스팸 맛탕
125/251 처리 완료: 카레주먹밥
126/251 처리 완료: 부타동
127/251 처리 완료: 토마토부르스케타
128/251 처리 완료: 장떡만둣국
129/251 처리 완료: 식빵팝콘
130/251 처리 완료: 통마늘표고버섯볶음
131/251 처리 완료: 두부 파프리카전, 두부, 달걀
132/251 처리 완료: 고구마에그슬럿
133/251 처리 완료: 빨간 오뎅 / Spicy fish cakes
134/251 처리 완료: 고구마채전
135/251 처리 완료: 바치 디 다마
136/251 처리 완료: 파프리카 피자
137/251 처리 완료: 허니윙
138/251 처리 완료: 감자전
139/251 처리 완료: 토스트
140/251 처리 완료: 야채샐러드빵
141/251 처리 완료: 무침만두
142/251 처리 완료: 떡볶음
143/251 처리 완료: 버섯볶음두부면
144/251 처리 완료: 카페모카쿠키슈
145/251 처리 완료: 양파덮밥
146/251 처리 완료: 컵케이크
147/251 처리 완료: 오이들깨무침
148/251 처리 완료: 물비빔국수
149/251 처리 완료: 불참치장
150/251 처리 완료: 치즈 공구마

In [ ]:

# for idx, row in recipes[150:180].iterrows():
#     cleaned = clean_title_with_ai(row["title"])
#     cleaned_titles.append(cleaned)
    
#     print(f"{idx+1}/{len(recipes)} 처리 완료: {cleaned}")

151/251 처리 완료: 모카 케이크
152/251 처리 완료: 숙주볶음
153/251 처리 완료: 치즈 쿠키
154/251 처리 완료: 초코 비스코티
155/251 처리 완료: 고추장황태채볶음
156/251 처리 완료: 된장삼겹살덮밥
157/251 처리 완료: 오징어말이
158/251 처리 완료: 애호박 새우마요 볶음
159/251 처리 완료: 돼지갈비
160/251 처리 완료: 두부스테이크
161/251 처리 완료: 두부 마요네즈
162/251 처리 완료: 크림 새송이
163/251 처리 완료: 오이롤초밥
164/251 처리 완료: 콘치즈 고로케
165/251 처리 완료: 표고버섯 덮밥
166/251 처리 완료: 가지탕수
167/251 처리 완료: 그라탱
168/251 처리 완료: 우유달걀카레
169/251 처리 완료: 오일파스타
170/251 처리 완료: 황태채 버터구이
171/251 처리 완료: 대패대파구이
172/251 처리 완료: 베이컨치즈밥말이
173/251 처리 완료: 양파튀김
174/251 처리 완료: 사과 케이크
175/251 처리 완료: 새송이
176/251 처리 완료: 훈제오리볶음
오리훈제볶음
양배추볶음
177/251 처리 완료: 파프리카된장무침
178/251 처리 완료: 닭마볶음밥
179/251 처리 완료: 우삼겹 덮밥 규동
180/251 처리 완료: 가지 라자냐

In [ ]:
# for idx, row in recipes[180:210].iterrows():
#     cleaned = clean_title_with_ai(row["title"])
#     cleaned_titles.append(cleaned)
    
#     print(f"{idx+1}/{len(recipes)} 처리 완료: {cleaned}")

181/251 처리 완료: 닭죽
182/251 처리 완료: 참치 파스타, 두부면 파스타
183/251 처리 완료: 떡감자
184/251 처리 완료: 느타리두루치기
185/251 처리 완료: 오이무침
186/251 처리 완료: 콩나물무침
187/251 처리 완료: 간장두부장
188/251 처리 완료: 돈까스 김치나베
189/251 처리 완료: 얼큰만둣국
190/251 처리 완료: 시금치 플랫브레드 피자
191/251 처리 완료: 마늘빵
마늘빵
마늘빵
식빵
192/251 처리 완료: 돼지불백
193/251 처리 완료: 녹차머핀
194/251 처리 완료: 참치맛나니
195/251 처리 완료: 프리타타
196/251 처리 완료: 아망디오 쇼콜라
197/251 처리 완료: 할로윈 브라우니 쿠키
198/251 처리 완료: 연어 파피요트
199/251 처리 완료: 새송이버섯 고추장구이
200/251 처리 완료: 뢰스티
201/251 처리 완료: 츄러스
202/251 처리 완료: 어묵비빔국수
203/251 처리 완료: 김치마요우동
204/251 처리 완료: 하트파이 팔미에
205/251 처리 완료: 달걀떡볶이
206/251 처리 완료: 소고기볶음
207/251 처리 완료: 양파햄치즈빵
208/251 처리 완료: 게살버거
209/251 처리 완료: 크랜베리 화이트 초코 쿠키
210/251 처리 완료: 모카 컵케이크

In [ ]:

# for idx, row in recipes[210:240].iterrows():
#     cleaned = clean_title_with_ai(row["title"])
#     cleaned_titles.append(cleaned)
    
#     print(f"{idx+1}/{len(recipes)} 처리 완료: {cleaned}")

211/251 처리 완료: 어향치킨
212/251 처리 완료: 체리클라푸티
213/251 처리 완료: 순두부 계란
214/251 처리 완료: 투움바파스타
215/251 처리 완료: 오레오 크림치즈 머핀
216/251 처리 완료: 버터구이 진미채
217/251 처리 완료: 함양파 링전
218/251 처리 완료: 스팸아보카도덮밥
219/251 처리 완료: 고추참치비빔우동
220/251 처리 완료: 면두부 크림파스타
221/251 처리 완료: 스팸마요 덮밥
222/251 처리 완료: 사과 크렘블 파이
223/251 처리 완료: 스카레
224/251 처리 완료: 어묵노미야끼
225/251 처리 완료: 콘치즈
226/251 처리 완료: 식빵 러스크 (에어프라이어)
227/251 처리 완료: 소고기쪽파말이
228/251 처리 완료: 딸기잼 쿠키
과일잼 쿠키
229/251 처리 완료: 계란탕
230/251 처리 완료: 오징어볶음
231/251 처리 완료: 시나몬 롤 쿠키
232/251 처리 완료: 가지덮밥
233/251 처리 완료: 시래기지짐
234/251 처리 완료: 파마산 치즈 쿠키
235/251 처리 완료: 소시지강정
236/251 처리 완료: 식빵팝콘
237/251 처리 완료: 베이컨말이
238/251 처리 완료: 퍼지 브라우니
239/251 처리 완료: 대파토스트
240/251 처리 완료: 소시지콩나물찜

In [ ]:

# for idx, row in recipes[240:251].iterrows():
#     cleaned = clean_title_with_ai(row["title"])
#     cleaned_titles.append(cleaned)
    
#     print(f"{idx+1}/{len(recipes)} 처리 완료: {cleaned}")

241/251 처리 완료: 아보카도 베이컨구이
242/251 처리 완료: 고구마조림
243/251 처리 완료: 주먹밥
244/251 처리 완료: 양배추어묵볶음
245/251 처리 완료: 구운 참치 주먹밥
246/251 처리 완료: 퐁크러쉬 쉐이크
247/251 처리 완료: 소시지 배추 롤
248/251 처리 완료: 돼지불백
249/251 처리 완료: 등갈비
250/251 처리 완료: 초코칩쿠키
251/251 처리 완료: 커피콩 쿠키

In [8]:

recipes["title"] = cleaned_titles
recipes

,Unnamed: 0,url,title,description,servings,time,difficulty,materials,tools,steps,final_images,tips,danger
0,1,https://www.10000recipe.com/recipe/6953727,떡꼬치,떡꼬치를 너무 좋아하는데 요즘 파는곳이 별로 없어서\n간단하게 집에서 한번 만들어봤...,2인분,15분 이내,초급,"가래떡 7개, 기름 조금, 케찹 3큰술, 진간장 1/2큰술, 고추장 1큰술, 올리고...",에어프라이어,[{'text': '떡에 기름을 골고루 조금씩 묻혀 에어프라이어에 돌려줍니다\n18...,[],"저는 이마트에서 2,000원짜리 떡 한팩을 사와서 냉동에 넣지않고 바로 뒷날 해먹었...",0
1,3,https://www.10000recipe.com/recipe/6928779,계란빵 꿀빵,계란빵도 먹고 꿀빵도 먹고 즐거운 간식 타임에 모양틀을 이용해 아이와 함께 또는 혼...,2인분,15분 이내,초급,"빵 4장, 달걀 2개, 슬라이스 치즈 2장, 소금 톡톡, 꿀 듬뿍","오븐, 숟가락","[{'text': '1 계란빵 만들기\n빵에 구멍을 냅니다', 'images': [...",['https://recipe1.ezmember.co.kr/cache/recipe/...,큼직한 식빵에 만들면 더 쉬워요,0
2,5,https://www.10000recipe.com/recipe/6728751,고구마 빵,"초간단 노오븐 베이킹. 노버터, 노밀가루라 아기에게 딱!! 건강한 간식이예요",2인분,30분 이내,초급,"고구마 2개, 계란 흰자 2개, 올리브오일 약간","오븐, 숟가락",[{'text': '고구마는 껍질을 까고 쪄낸 후 뜨거울때 으깨주세요. 고구마가 달...,['https://recipe1.ezmember.co.kr/cache/recipe/...,NaN,0
3,10,https://www.10000recipe.com/recipe/6881646,"코울슬로, 사라다빵",새콤달콤한 양배추 샐러드 '코울슬로'와\n모닝빵 대신 통식빵을 이용한 '사라다빵'을...,6인분 이상,30분 이내,초급,"양배추 350g, 사과 1/2개, 캔옥수수 100g, 마요네즈 5큰술, 레몬즙 3큰...","오븐, 숟가락","[{'text': '분량의 마요네즈, 레몬즙, 연유, 천일염을 잘 섞고 통후추도 갈...",['https://recipe1.ezmember.co.kr/cache/recipe/...,서너시간 지나 맛을 보고 좀 더 새콤달콤한 맛을 원한다면 레몬즙과 연유를 입맛에 맞...,0
4,15,https://www.10000recipe.com/recipe/6880305,또띠아 피자,달걀지단이 들어간\n사과 또띠아 피자!,2인분,15분 이내,초급,"사과 1/4개, 사과잼 3T, 또띠아 1개, 미트스파게티소스 3T, 달걀 1개, 견...","전자레인지,에어프라이어",[{'text': '* 재료 준비\n또띠아 1개\n사과 1/4개\n사과잼 3T\n미...,['https://recipe1.ezmember.co.kr/cache/recipe/...,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
108,123,https://youtu.be/nKZ_bKiDeVY?list=TLGGgpMG1C4C...,토스트,NaN,NaN,NaN,NaN,"식빵, 달걀, 샌드위치 햄, 설탕, 케첩, 마요네즈","숟가락, 전자레인지",NaN,NaN,NaN,0
109,124,https://youtu.be/Z2vjsJZnXog?list=TLGGk0UrLaeB...,피자계란밥,NaN,NaN,NaN,NaN,"밥 100g, 계란 1알, 케첩, 모짜렐라 치즈","숟가락, 전자레인지",NaN,NaN,NaN,0
110,125,https://youtu.be/YQZn6dQV0xg?list=TLGGSlnnq6am...,볶음밥,NaN,NaN,NaN,NaN,"즉석밥 1개, 계란 2알, 스팸, 김치","숟가락, 가위, 전자레인지, 깊은 그릇(유리, 사기)","1. 재료 준비\n- 즉석밥 1개, 계란 2알, 스팸, 김치\n2. 조리도구준비\n...",NaN,NaN,0
111,126,https://youtu.be/e9VVSZei8hU?list=TLGGLCgQyHYh...,스팸계란밥,NaN,NaN,NaN,NaN,"계란 2알, 즉석밥 1개, 스팸, 파, 소금, 간장","깊은 그릇, 전자레인지, 비닐랩",NaN,NaN,NaN,0
112,127,https://youtu.be/j1JVxiuNSuU?list=TLGGfkA0RV52...,계란찜,NaN,NaN,NaN,NaN,"계란 1알, 우유 200ml, 카레가루, 파, 즉석밥 1","숫가락, 전자레인지, 가위",NaN,NaN,NaN,0

In [9]:

recipes.to_csv("recipes_cleaned.csv")

In [36]:
# title 길이가 15 이하인 행만 남기기
recipes = recipes[recipes['title'].str.len() <= 15]

# 결과 저장
recipes.to_csv("recipes_cleaned.csv", index=False)

## 카테고리 추가

In [7]:
import pandas as pd
from openai import OpenAI
import time

client = OpenAI(api_key="sktax-XyeKFrq67ZjS4EpsDlrHHXV8it", base_url="https://guest-api.sktax.chat/v1")

In [10]:
# AI에게 카테고리 분류 요청
def categorize_with_ai(title):
    """
    title을 입력하면 AI가 한식, 중식, 양식, 디저트, 음료 등으로 분류
    """
    prompt = f"다음 음식 제목을 보고 [한식, 중식, 양식, 일식, 간식, 기타] 중 가장 적절한 카테고리 하나만 선택하세요.\n선택한 카테고리의 단어만 출력하고, 다른 말은 절대 하지 마세요.\n\n음식 제목: {title}"
    completion = client.chat.completions.create(
        model="ax4",
        messages=[{"role": "user", "content": prompt}]
    )
    # AI 응답에서 텍스트 추출
    category = completion.choices[0].message.content.strip()
    return category

In [11]:
# CSV 불러오기
recipes = pd.read_csv("recipes_cleaned.csv")

# category 컬럼 초기화
categories = []

In [12]:
for idx, row in recipes[:30].iterrows():
    cat = categorize_with_ai(row["title"])
    categories.append(cat)
    print(f"{idx+1}/{len(recipes)} 처리 완료: {row['title']} -> {cat}")

1/113 처리 완료: 떡꼬치 -> 간식
2/113 처리 완료: 계란빵 꿀빵 -> 간식
3/113 처리 완료: 고구마 빵 -> 간식
4/113 처리 완료: 코울슬로, 사라다빵 -> 양식
5/113 처리 완료: 또띠아 피자 -> 간식
6/113 처리 완료: 스파게티 샌드위치 -> 양식
7/113 처리 완료: 치즈 샌드위치 -> 양식
8/113 처리 완료: 양배추샌드위치 -> 양식
9/113 처리 완료: 샌드위치 -> 양식
10/113 처리 완료: 연어 샌드위치 -> 양식
11/113 처리 완료: 샌드위치 -> 양식
12/113 처리 완료: 닭가슴살샌드위치 -> 양식
13/113 처리 완료: 닭가슴살브리또 -> 양식
14/113 처리 완료: 샌드위치 -> 양식
15/113 처리 완료: 딸기롤샌드위치 -> 간식
16/113 처리 완료: 에그 샌드위치 -> 양식
17/113 처리 완료: 두부 계란찜 -> 한식
18/113 처리 완료: 몬테크리스토 샌드위치 -> 양식
19/113 처리 완료: 딸기샌드위치 -> 간식
20/113 처리 완료: 오픈샌드위치 -> 양식
21/113 처리 완료: 닭 가슴살 샐러드, 샌드위치 -> 간식
22/113 처리 완료: 아보카도 샌드위치 -> 양식
23/113 처리 완료: 베이컨 샌드위치 -> 양식
24/113 처리 완료: 스파이시슈림프샌드위치 -> 양식
25/113 처리 완료: 연어샌드위치 -> 양식
26/113 처리 완료: 오픈 샌드위치 -> 양식
27/113 처리 완료: 메추리알맛살샌드위치 -> 양식
28/113 처리 완료: 모닝롤 -> 간식
29/113 처리 완료: 버터비빔밥 -> 한식
30/113 처리 완료: 파니니샌드위치 -> 양식

In [13]:
for idx, row in recipes[30:60].iterrows():
    cat = categorize_with_ai(row["title"])
    categories.append(cat)
    print(f"{idx+1}/{len(recipes)} 처리 완료: {row['title']} -> {cat}")

31/113 처리 완료: 치즈샌드위치 -> 양식
32/113 처리 완료: 오징어 샐러드 -> 양식
33/113 처리 완료: 닭가슴살 무침 -> 한식
34/113 처리 완료: 게맛살 또띠아 샌드위치 -> 간식
35/113 처리 완료: 견과아몬드쿠키 -> 간식
36/113 처리 완료: 콩나물무침 -> 한식
37/113 처리 완료: 통 삼겹살 -> 한식
38/113 처리 완료: 옥수수치즈 -> 간식
39/113 처리 완료: 소고기
고구마 -> 간식
40/113 처리 완료: 웨지고구마 -> 간식
41/113 처리 완료: 누룽지 -> 한식
42/113 처리 완료: 떡꼬치 -> 간식
43/113 처리 완료: 크로크무슈 -> 양식
44/113 처리 완료: 브라질 치즈빵 -> 간식
45/113 처리 완료: 얼그레이 사브레 쿠키 -> 간식
46/113 처리 완료: 카레구이 -> 중식
47/113 처리 완료: 숙주나물무침 -> 한식
48/113 처리 완료: 마약달걀장 -> 중식
49/113 처리 완료: 멸치고추지볶음 -> 한식
50/113 처리 완료: 삼겹살김치파스타 -> 양식
51/113 처리 완료: 오믈렛 -> 양식
52/113 처리 완료: 볶음밥 -> 중식
53/113 처리 완료: 토마토 계란 피자 -> 양식
54/113 처리 완료: 마늘볶음밥 -> 중식
55/113 처리 완료: 알리오 올리오 -> 양식
56/113 처리 완료: 해물 토스트 -> 간식
57/113 처리 완료: 명란젓 마요계란밥 -> 한식
58/113 처리 완료: 메밀소바 -> 일식
59/113 처리 완료: 모짜프렌치토스트 -> 간식
60/113 처리 완료: 참치마요 주먹밥 -> 한식

In [14]:
print(len(categories))

60

In [15]:
c = []
for idx, row in recipes[60:90].iterrows():
    cat = categorize_with_ai(row["title"])
    c.append(cat)
    print(f"{idx+1}/{len(recipes)} 처리 완료: {row['title']} -> {cat}")

categories += c
len(categories)

61/113 처리 완료: 상추 주먹밥 -> 한식
62/113 처리 완료: 들기름 막국수
간장비빔메밀국수 -> 한식
63/113 처리 완료: 아보카도 참치마요 덮밥 -> 일식
64/113 처리 완료: 두부 덮밥 -> 일식
65/113 처리 완료: 마요네즈계란밥 -> 한식
66/113 처리 완료: 볶음밥 -> 중식
67/113 처리 완료: 버터비빔밥 -> 한식
68/113 처리 완료: 찹스테이크 -> 양식
69/113 처리 완료: 삼겹살 상추 조림 -> 한식
70/113 처리 완료: 야채 김 계란말이 -> 간식
71/113 처리 완료: 돈까스 샌드위치 -> 양식
72/113 처리 완료: 양배추 만둣국 -> 한식
73/113 처리 완료: 명란,된장 -> 한식
74/113 처리 완료: 참치샐러드 -> 양식
75/113 처리 완료: 카레 주먹밥 -> 일식
76/113 처리 완료: 열무김치국수 -> 한식
77/113 처리 완료: 치즈떡 계란말이 -> 간식
78/113 처리 완료: 비빔국수 -> 한식
79/113 처리 완료: 김치찌개 -> 한식
80/113 처리 완료: 콩나물국 -> 한식
81/113 처리 완료: 간장파스타 -> 양식
82/113 처리 완료: 국물떡볶이 -> 한식
83/113 처리 완료: 계란빵, 꿀빵 -> 간식
84/113 처리 완료: 연어 샐러드 -> 양식
85/113 처리 완료: 소세지야채볶음 -> 양식
86/113 처리 완료: 달걀 볶음밥 -> 양식
87/113 처리 완료: 두부찌개 -> 한식
88/113 처리 완료: 데리야키 닭고기 -> 일식
89/113 처리 완료: 몬테크리스토 시리얼 토스트 -> 간식
90/113 처리 완료: 김밥 -> 간식

90

In [18]:
c = []
for idx, row in recipes[90:113].iterrows():
    cat = categorize_with_ai(row["title"])
    c.append(cat)
    print(f"{idx+1}/{len(recipes)} 처리 완료: {row['title']} -> {cat}")

categories += c
len(categories)

91/113 처리 완료: 카레라이스 -> 양식
92/113 처리 완료: 쇠고기볶음 -> 한식
93/113 처리 완료: 김치부침개피자 -> 한식
94/113 처리 완료: 식빵피자 -> 간식
95/113 처리 완료: 콘치즈 -> 간식
96/113 처리 완료: 김치볶음밥 -> 한식
97/113 처리 완료: 꿀피자 -> 간식
98/113 처리 완료: 계란프라이 -> 간식
99/113 처리 완료: 프렌치 토스트 -> 양식
100/113 처리 완료: 감자 -> 간식
101/113 처리 완료: 계란죽 -> 한식
102/113 처리 완료: 크림우동 -> 일식
103/113 처리 완료: 밥버거 -> 간식
104/113 처리 완료: 스파게티 -> 양식
105/113 처리 완료: 계란찜 -> 한식
106/113 처리 완료: 토스트 -> 간식
107/113 처리 완료: 로제떡볶이 -> 한식
108/113 처리 완료: 꿀빵 -> 간식
109/113 처리 완료: 토스트 -> 간식
110/113 처리 완료: 피자계란밥 -> 한식
111/113 처리 완료: 볶음밥 -> 중식
112/113 처리 완료: 스팸계란밥 -> 한식
113/113 처리 완료: 계란찜 -> 한식

113

In [ ]:
# c = []
# for idx, row in recipes[120:150].iterrows():
#     cat = categorize_with_ai(row["title"])
#     c.append(cat)
#     print(f"{idx+1}/{len(recipes)} 처리 완료: {row['title']} -> {cat}")

# categories += c
# len(categories)

121/246 처리 완료: 오레오 치즈케이크 -> 간식
122/246 처리 완료: 스팸 맛탕 -> 간식
123/246 처리 완료: 카레주먹밥 -> 간식
124/246 처리 완료: 부타동 -> 일식
125/246 처리 완료: 토마토부르스케타 -> 양식
126/246 처리 완료: 장떡만둣국 -> 한식
127/246 처리 완료: 식빵팝콘 -> 간식
128/246 처리 완료: 통마늘표고버섯볶음 -> 한식
129/246 처리 완료: 고구마에그슬럿 -> 간식
130/246 처리 완료: 고구마채전 -> 간식
131/246 처리 완료: 바치 디 다마 -> 중식
132/246 처리 완료: 파프리카 피자 -> 양식
133/246 처리 완료: 허니윙 -> 간식
134/246 처리 완료: 감자전 -> 한식
135/246 처리 완료: 토스트 -> 간식
136/246 처리 완료: 야채샐러드빵 -> 간식
137/246 처리 완료: 무침만두 -> 한식
138/246 처리 완료: 떡볶음 -> 한식
139/246 처리 완료: 버섯볶음두부면 -> 한식
140/246 처리 완료: 카페모카쿠키슈 -> 간식
141/246 처리 완료: 양파덮밥 -> 일식
142/246 처리 완료: 컵케이크 -> 간식
143/246 처리 완료: 오이들깨무침 -> 한식
144/246 처리 완료: 물비빔국수 -> 한식
145/246 처리 완료: 불참치장 -> 일식
146/246 처리 완료: 치즈 공구마 -> 간식
147/246 처리 완료: 모카 케이크 -> 간식
148/246 처리 완료: 숙주볶음 -> 중식
149/246 처리 완료: 치즈 쿠키 -> 간식
150/246 처리 완료: 초코 비스코티 -> 간식

150

In [ ]:
# c = []
# for idx, row in recipes[150:180].iterrows():
#     cat = categorize_with_ai(row["title"])
#     c.append(cat)
#     print(f"{idx+1}/{len(recipes)} 처리 완료: {row['title']} -> {cat}")

# categories += c
# len(categories)

151/246 처리 완료: 고추장황태채볶음 -> 한식
152/246 처리 완료: 된장삼겹살덮밥 -> 한식
153/246 처리 완료: 오징어말이 -> 일식
154/246 처리 완료: 애호박 새우마요 볶음 -> 한식
155/246 처리 완료: 돼지갈비 -> 한식
156/246 처리 완료: 두부스테이크 -> 양식
157/246 처리 완료: 두부 마요네즈 -> 한식
158/246 처리 완료: 크림 새송이 -> 양식
159/246 처리 완료: 오이롤초밥 -> 일식
160/246 처리 완료: 콘치즈 고로케 -> 간식
161/246 처리 완료: 표고버섯 덮밥 -> 일식
162/246 처리 완료: 가지탕수 -> 중식
163/246 처리 완료: 그라탱 -> 양식
164/246 처리 완료: 우유달걀카레 -> 간식
165/246 처리 완료: 오일파스타 -> 양식
166/246 처리 완료: 황태채 버터구이 -> 한식
167/246 처리 완료: 대패대파구이 -> 한식
168/246 처리 완료: 베이컨치즈밥말이 -> 양식
169/246 처리 완료: 양파튀김 -> 간식
170/246 처리 완료: 사과 케이크 -> 간식
171/246 처리 완료: 새송이 -> 한식
172/246 처리 완료: 파프리카된장무침 -> 한식
173/246 처리 완료: 닭마볶음밥 -> 중식
174/246 처리 완료: 우삼겹 덮밥 규동 -> 일식
175/246 처리 완료: 가지 라자냐 -> 양식
176/246 처리 완료: 닭죽 -> 한식
177/246 처리 완료: 참치 파스타, 두부면 파스타 -> 양식
178/246 처리 완료: 떡감자 -> 간식
179/246 처리 완료: 느타리두루치기 -> 한식
180/246 처리 완료: 오이무침 -> 한식

180

In [ ]:
# c = []
# for idx, row in recipes[180:210].iterrows():
#     cat = categorize_with_ai(row["title"])
#     c.append(cat)
#     print(f"{idx+1}/{len(recipes)} 처리 완료: {row['title']} -> {cat}")

# categories += c
# len(categories)

181/246 처리 완료: 콩나물무침 -> 한식
182/246 처리 완료: 간장두부장 -> 중식
183/246 처리 완료: 돈까스 김치나베 -> 일식
184/246 처리 완료: 얼큰만둣국 -> 한식
185/246 처리 완료: 시금치 플랫브레드 피자 -> 양식
186/246 처리 완료: 마늘빵
마늘빵
마늘빵
식빵 -> 양식
187/246 처리 완료: 돼지불백 -> 한식
188/246 처리 완료: 녹차머핀 -> 간식
189/246 처리 완료: 참치맛나니 -> 일식
190/246 처리 완료: 프리타타 -> 양식
191/246 처리 완료: 아망디오 쇼콜라 -> 간식
192/246 처리 완료: 할로윈 브라우니 쿠키 -> 간식
193/246 처리 완료: 연어 파피요트 -> 양식
194/246 처리 완료: 새송이버섯 고추장구이 -> 한식
195/246 처리 완료: 뢰스티 -> 간식
196/246 처리 완료: 츄러스 -> 간식
197/246 처리 완료: 어묵비빔국수 -> 간식
198/246 처리 완료: 김치마요우동 -> 일식
199/246 처리 완료: 하트파이 팔미에 -> 간식
200/246 처리 완료: 달걀떡볶이 -> 한식
201/246 처리 완료: 소고기볶음 -> 한식
202/246 처리 완료: 양파햄치즈빵 -> 간식
203/246 처리 완료: 게살버거 -> 양식
204/246 처리 완료: 크랜베리 화이트 초코 쿠키 -> 간식
205/246 처리 완료: 모카 컵케이크 -> 간식
206/246 처리 완료: 어향치킨 -> 중식
207/246 처리 완료: 체리클라푸티 -> 간식
208/246 처리 완료: 순두부 계란 -> 한식
209/246 처리 완료: 투움바파스타 -> 양식
210/246 처리 완료: 오레오 크림치즈 머핀 -> 간식

210

In [ ]:
# c = []
# for idx, row in recipes[210:246].iterrows():
#     cat = categorize_with_ai(row["title"])
#     c.append(cat)
#     print(f"{idx+1}/{len(recipes)} 처리 완료: {row['title']} -> {cat}")

# categories += c
# len(categories)

211/246 처리 완료: 버터구이 진미채 -> 간식
212/246 처리 완료: 함양파 링전 -> 한식
213/246 처리 완료: 스팸아보카도덮밥 -> 일식
214/246 처리 완료: 고추참치비빔우동 -> 일식
215/246 처리 완료: 면두부 크림파스타 -> 양식
216/246 처리 완료: 스팸마요 덮밥 -> 일식
217/246 처리 완료: 사과 크렘블 파이 -> 간식
218/246 처리 완료: 스카레 -> 아라비아
219/246 처리 완료: 어묵노미야끼 -> 기타
220/246 처리 완료: 콘치즈 -> 간식
221/246 처리 완료: 식빵 러스크 (에어프라이어) -> 간식
222/246 처리 완료: 소고기쪽파말이 -> 한식
223/246 처리 완료: 딸기잼 쿠키
과일잼 쿠키 -> 간식
224/246 처리 완료: 계란탕 -> 한식
225/246 처리 완료: 오징어볶음 -> 한식
226/246 처리 완료: 시나몬 롤 쿠키 -> 간식
227/246 처리 완료: 가지덮밥 -> 일식
228/246 처리 완료: 시래기지짐 -> 한식
229/246 처리 완료: 파마산 치즈 쿠키 -> 간식
230/246 처리 완료: 소시지강정 -> 간식
231/246 처리 완료: 식빵팝콘 -> 간식
232/246 처리 완료: 베이컨말이 -> 간식
233/246 처리 완료: 퍼지 브라우니 -> 간식
234/246 처리 완료: 대파토스트 -> 간식
235/246 처리 완료: 소시지콩나물찜 -> 한식
236/246 처리 완료: 아보카도 베이컨구이 -> 양식
237/246 처리 완료: 고구마조림 -> 간식
238/246 처리 완료: 주먹밥 -> 한식
239/246 처리 완료: 양배추어묵볶음 -> 한식
240/246 처리 완료: 구운 참치 주먹밥 -> 일식
241/246 처리 완료: 퐁크러쉬 쉐이크 -> 간식
242/246 처리 완료: 소시지 배추 롤 -> 간식
243/246 처리 완료: 돼지불백 -> 한식
244/246 처리 완료: 등갈비 -> 한식
245/246 처리 완료: 초코칩쿠키 -> 간식
246/246 처리 완료: 커피콩 쿠키 -> 간식

246

In [19]:
len(categories)

113

In [22]:
recipes1 = recipes
recipes1.drop(columns=["Unnamed: 0", "Unnamed: 0.1"], inplace=True, errors='ignore')
recipes1.head(1)

,url,title,description,servings,time,difficulty,materials,tools,steps,final_images,tips,danger
0,https://www.10000recipe.com/recipe/6953727,떡꼬치,떡꼬치를 너무 좋아하는데 요즘 파는곳이 별로 없어서\n간단하게 집에서 한번 만들어봤...,2인분,15분 이내,초급,"가래떡 7개, 기름 조금, 케찹 3큰술, 진간장 1/2큰술, 고추장 1큰술, 올리고...",에어프라이어,[{'text': '떡에 기름을 골고루 조금씩 묻혀 에어프라이어에 돌려줍니다\n18...,[],"저는 이마트에서 2,000원짜리 떡 한팩을 사와서 냉동에 넣지않고 바로 뒷날 해먹었...",0

In [23]:
recipes

,url,title,description,servings,time,difficulty,materials,tools,steps,final_images,tips,danger
0,https://www.10000recipe.com/recipe/6953727,떡꼬치,떡꼬치를 너무 좋아하는데 요즘 파는곳이 별로 없어서\n간단하게 집에서 한번 만들어봤...,2인분,15분 이내,초급,"가래떡 7개, 기름 조금, 케찹 3큰술, 진간장 1/2큰술, 고추장 1큰술, 올리고...",에어프라이어,[{'text': '떡에 기름을 골고루 조금씩 묻혀 에어프라이어에 돌려줍니다\n18...,[],"저는 이마트에서 2,000원짜리 떡 한팩을 사와서 냉동에 넣지않고 바로 뒷날 해먹었...",0
1,https://www.10000recipe.com/recipe/6928779,계란빵 꿀빵,계란빵도 먹고 꿀빵도 먹고 즐거운 간식 타임에 모양틀을 이용해 아이와 함께 또는 혼...,2인분,15분 이내,초급,"빵 4장, 달걀 2개, 슬라이스 치즈 2장, 소금 톡톡, 꿀 듬뿍","오븐, 숟가락","[{'text': '1 계란빵 만들기\n빵에 구멍을 냅니다', 'images': [...",['https://recipe1.ezmember.co.kr/cache/recipe/...,큼직한 식빵에 만들면 더 쉬워요,0
2,https://www.10000recipe.com/recipe/6728751,고구마 빵,"초간단 노오븐 베이킹. 노버터, 노밀가루라 아기에게 딱!! 건강한 간식이예요",2인분,30분 이내,초급,"고구마 2개, 계란 흰자 2개, 올리브오일 약간","오븐, 숟가락",[{'text': '고구마는 껍질을 까고 쪄낸 후 뜨거울때 으깨주세요. 고구마가 달...,['https://recipe1.ezmember.co.kr/cache/recipe/...,NaN,0
3,https://www.10000recipe.com/recipe/6881646,"코울슬로, 사라다빵",새콤달콤한 양배추 샐러드 '코울슬로'와\n모닝빵 대신 통식빵을 이용한 '사라다빵'을...,6인분 이상,30분 이내,초급,"양배추 350g, 사과 1/2개, 캔옥수수 100g, 마요네즈 5큰술, 레몬즙 3큰...","오븐, 숟가락","[{'text': '분량의 마요네즈, 레몬즙, 연유, 천일염을 잘 섞고 통후추도 갈...",['https://recipe1.ezmember.co.kr/cache/recipe/...,서너시간 지나 맛을 보고 좀 더 새콤달콤한 맛을 원한다면 레몬즙과 연유를 입맛에 맞...,0
4,https://www.10000recipe.com/recipe/6880305,또띠아 피자,달걀지단이 들어간\n사과 또띠아 피자!,2인분,15분 이내,초급,"사과 1/4개, 사과잼 3T, 또띠아 1개, 미트스파게티소스 3T, 달걀 1개, 견...","전자레인지,에어프라이어",[{'text': '* 재료 준비\n또띠아 1개\n사과 1/4개\n사과잼 3T\n미...,['https://recipe1.ezmember.co.kr/cache/recipe/...,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...
108,https://youtu.be/nKZ_bKiDeVY?list=TLGGgpMG1C4C...,토스트,NaN,NaN,NaN,NaN,"식빵, 달걀, 샌드위치 햄, 설탕, 케첩, 마요네즈","숟가락, 전자레인지",NaN,NaN,NaN,0
109,https://youtu.be/Z2vjsJZnXog?list=TLGGk0UrLaeB...,피자계란밥,NaN,NaN,NaN,NaN,"밥 100g, 계란 1알, 케첩, 모짜렐라 치즈","숟가락, 전자레인지",NaN,NaN,NaN,0
110,https://youtu.be/YQZn6dQV0xg?list=TLGGSlnnq6am...,볶음밥,NaN,NaN,NaN,NaN,"즉석밥 1개, 계란 2알, 스팸, 김치","숟가락, 가위, 전자레인지, 깊은 그릇(유리, 사기)","1. 재료 준비\n- 즉석밥 1개, 계란 2알, 스팸, 김치\n2. 조리도구준비\n...",NaN,NaN,0
111,https://youtu.be/e9VVSZei8hU?list=TLGGLCgQyHYh...,스팸계란밥,NaN,NaN,NaN,NaN,"계란 2알, 즉석밥 1개, 스팸, 파, 소금, 간장","깊은 그릇, 전자레인지, 비닐랩",NaN,NaN,NaN,0
112,https://youtu.be/j1JVxiuNSuU?list=TLGGfkA0RV52...,계란찜,NaN,NaN,NaN,NaN,"계란 1알, 우유 200ml, 카레가루, 파, 즉석밥 1","숫가락, 전자레인지, 가위",NaN,NaN,NaN,0

In [24]:
recipes["category"] = categories
recipes.head(1)

,url,title,description,servings,time,difficulty,materials,tools,steps,final_images,tips,danger,category
0,https://www.10000recipe.com/recipe/6953727,떡꼬치,떡꼬치를 너무 좋아하는데 요즘 파는곳이 별로 없어서\n간단하게 집에서 한번 만들어봤...,2인분,15분 이내,초급,"가래떡 7개, 기름 조금, 케찹 3큰술, 진간장 1/2큰술, 고추장 1큰술, 올리고...",에어프라이어,[{'text': '떡에 기름을 골고루 조금씩 묻혀 에어프라이어에 돌려줍니다\n18...,[],"저는 이마트에서 2,000원짜리 떡 한팩을 사와서 냉동에 넣지않고 바로 뒷날 해먹었...",0,간식

In [25]:
recipes.to_csv("recipes_with_categories.csv", index=False)

## 시간, 인분 int화

In [1]:
import pandas as pd

In [26]:
recipes = pd.read_csv('recipes_with_categories.csv')

In [48]:
# 널 제거
len(recipes.dropna(subset=["title", "servings", "time", "difficulty", "materials", "tools", "steps", "danger", "category"]))
# null인 행 개수
# len(recipes[recipes["difficulty"].isnull()])

87

In [49]:
recipes.dropna(subset=["title", "servings", "time", "difficulty", "materials", "tools", "steps", "danger", "category"], inplace=True)

In [50]:
# 허용 값 리스트
allowed_values = ['초급', '아무나', '중급', '고급']
# 조건 필터
recipes = recipes[recipes['difficulty'].isin(allowed_values)]


# '인분'으로 끝나는 행만 유지
recipes = recipes[recipes['servings'].str.endswith('인분', na=False)]
# '인분' 글자 제거
recipes['servings'] = recipes['servings'].str.replace('인분', '', regex=False)


# '분 이내'으로 끝나는 행만 유지
recipes = recipes[recipes['time'].str.endswith('분 이내', na=False)]
# '분 이내' 글자 제거
recipes['time'] = recipes['time'].str.replace('분 이내', '', regex=False)

recipes.head(3)

,url,title,description,servings,time,difficulty,materials,tools,steps,final_images,tips,danger,category
0,https://www.10000recipe.com/recipe/6953727,떡꼬치,떡꼬치를 너무 좋아하는데 요즘 파는곳이 별로 없어서\n간단하게 집에서 한번 만들어봤...,2,15,초급,"가래떡 7개, 기름 조금, 케찹 3큰술, 진간장 1/2큰술, 고추장 1큰술, 올리고...",에어프라이어,[{'text': '떡에 기름을 골고루 조금씩 묻혀 에어프라이어에 돌려줍니다\n18...,[],"저는 이마트에서 2,000원짜리 떡 한팩을 사와서 냉동에 넣지않고 바로 뒷날 해먹었...",0,간식
1,https://www.10000recipe.com/recipe/6928779,계란빵 꿀빵,계란빵도 먹고 꿀빵도 먹고 즐거운 간식 타임에 모양틀을 이용해 아이와 함께 또는 혼...,2,15,초급,"빵 4장, 달걀 2개, 슬라이스 치즈 2장, 소금 톡톡, 꿀 듬뿍","오븐, 숟가락","[{'text': '1 계란빵 만들기\n빵에 구멍을 냅니다', 'images': [...",['https://recipe1.ezmember.co.kr/cache/recipe/...,큼직한 식빵에 만들면 더 쉬워요,0,간식
2,https://www.10000recipe.com/recipe/6728751,고구마 빵,"초간단 노오븐 베이킹. 노버터, 노밀가루라 아기에게 딱!! 건강한 간식이예요",2,30,초급,"고구마 2개, 계란 흰자 2개, 올리브오일 약간","오븐, 숟가락",[{'text': '고구마는 껍질을 까고 쪄낸 후 뜨거울때 으깨주세요. 고구마가 달...,['https://recipe1.ezmember.co.kr/cache/recipe/...,NaN,0,간식

In [51]:
recipes.to_csv("recipes.csv", index=False)

## 도구 있는 레시피만 필터링

In [2]:
import pandas as pd

In [22]:
recipes = pd.read_csv('recipes.csv')
recipes = recipes.dropna(subset=['title', 'tools', 'materials'])
recipes

,url,main_image,author,title,description,servings,time,difficulty,materials,tools,video_url,steps,final_images,tips,category
0,https://www.10000recipe.com/recipe/7056958,https://recipe1.ezmember.co.kr/cache/recipe/20...,반이짝이,소고기 고추장,더운 여름에 입맛 없을 때 열무김치나 생야채 넣고 비빔밥 만들어먹거나 달걀프라이만 ...,2,20,초급,"다진소고기 200g, 양파 1/4개, 대파 1/4대, 다진마늘 1큰술, 진간장 1/...","키친타올, 믹싱볼, 도마, 조리용나이프, 계량스푼, 프라이팬, 요리스푼, 완성그릇",https://tv.naver.com/embed/21142287?autoPlay=true,[{'text': '다짐육 200g 정도를 준비한 다음 먼저 키친타월로 핏물을 제거...,['https://recipe1.ezmember.co.kr/cache/recipe/...,나물 반찬 만들어둔게 있어서 비빔밥 만들어먹을 때 약고추장 넣고 슥슥 비벼서 먹었더...,한식
1,https://www.10000recipe.com/recipe/7056078,https://recipe1.ezmember.co.kr/cache/recipe/20...,블루픽콕,비름나물,여름에 먹으면 맛있는 나물인 비름나물을 무쳐보았어요. 고추장 양념으로 무치면 된장찌...,4,30,아무나,"비름나물1봉 400g, 소금 1/2Ts, 고추장 2Ts, 다진 마늘 1Ts, 설탕 ...","볼, 냄비, 계량스푼, 조리주걱, 채반, 도마, 조리용나이프, 접시",https://www.youtube.com/embed/hcgBbhPK_4c,[{'text': '비름나물 한 봉지의 무게를 달아보았더니 대략 400g이 나왔어요...,['https://recipe1.ezmember.co.kr/cache/recipe/...,비름나물은 데치기전 굵고 억센 줄기는 골라내고 데쳐야 부드러운 나물을 먹을 수 있어...,한식
3,https://www.10000recipe.com/recipe/7004229,https://recipe1.ezmember.co.kr/cache/recipe/20...,유튜버아뜨,참치쌈장,다른 반찬 필요없이 이거 하나면 밥 한공기 뚝딱 갓한 따끈한 밥에 쌈장올려 쌈싸먹으...,3,15,초급,"참치 1캔, 양파 1개, 청양고추 3개, 기름 1T, 물 1/2컵, 된장 3T, 고...","인덱스도마, 믹싱볼, 요리스푼, 볶음팬",https://www.youtube.com/embed/_pF_uCKx9XU,"[{'text': '양파,고추 잘게썰기', 'images': ['https://re...",['https://recipe1.ezmember.co.kr/cache/recipe/...,"취향에 맞게 고추는 더 넣어도 좋아요 싱겁게 드신다면 두부, 감자 ,애호박, 버섯 ...",한식
5,https://www.10000recipe.com/recipe/7045377,https://recipe1.ezmember.co.kr/cache/recipe/20...,만개의레시피,양배추만두,만두는 먹고 싶은데 피까지 만들긴 귀찮고..그럴 땐 라이스페이퍼를 활용해 보세요!\...,2,20,아무나,"양배추 1/4개, 참치 1캔, 달걀 2개, 라이스페이퍼 10장, 굴소스 1T, 후추...","나무도마, 조리용나이프, 찬기, 숟가락, 프라이팬, 조리주걱, 접시",https://www.youtube.com/embed/EGWcn41U0zs,"[{'text': '양배추는 잘게 채 썰어요.\n나무도마 , 조리용나이프', 'im...",['https://recipe1.ezmember.co.kr/cache/recipe/...,NaN,중식
6,https://www.10000recipe.com/recipe/7033948,https://recipe1.ezmember.co.kr/cache/recipe/20...,반이짝이,햄 감자채볶음,아이들반찬으로 간단하게 만들기 좋은 감자채볶음을 스팸을 넣고 고소하고 짭조름하게 볶았어요,2,20,초급,"감자큰것 2개, 스팸 80g, 양파 1/4개, 당근 30g, 마늘 1작은술, 소금 ...","도마, 조리용나이프, 볼, 채반, 냄비, 프라이팬, 조리주걱, 계량스푼, 접시",https://tv.naver.com/embed/23435309?autoPlay=true,[{'text': '감자는 5~6mm 정도 두께로 일정하게 썰어준 뒤 먹기 좋게 채...,[],좋아하는 식감에 따라 데치지 않고 볶아도 되지만 한번 데친 뒤 요리하면 익히기도 쉽...,한식
7,https://www.10000recipe.com/recipe/7052761,https://recipe1.ezmember.co.kr/cache/recipe/20...,아임레시피,토마토간장샐러드,일본식 토마토샐러드는 간장소스에 먹는다고 해요~ 토마토와 간장이 조합이라.. 이거 ...,2,10,아무나,"토마토 2개, 상추 1/2장, 소금 2꼬집, 진간장 1/2큰술, 매실액 1/2큰술,...","도마, 조리용나이프, 소스볼, 계량스푼, 접시",https://www.youtube.com/embed/10XCyS-Yn8U,[{'text': '토마토는 깨끗이 씻어 반으로 잘라 먹기 좋게 일정한 크기로 썰어...,['https://recipe1.ezmember.co.kr/cache/recipe/...,간장소스를 골고루 뿌려 바로 드세요 ^^ 정말 맛있어요~,양식
8,https://www.10000recipe.com/recipe/7023640,https://recipe1.ezmember.co.kr/cache/recipe/20...,만개의레시피,취나물무침,취나물을 쌈장으로 조물조물 무쳐보세요. 향긋한 취나물을 간단하고 맛있게! 순식간에 ...,2,15,아무나,"취나물 150g, 통깨 1숟가락, 소금 1/2숟가락, 대파 1/3대, 쌈장 2숟가락...","도마, 조리용나이프, 냄비, 조리용집게, 니트릴장갑, 볼, 소스볼, 조리용스푼, 찬기",https://www.youtube.com/embed/H4TL-Ql3NZc,[{'text': '취나물은 억센 줄기는 제거하고 연한 줄기와 잎 부분만 남겨 손질...,['https://recipe1.ezmember.co.kr/cache/recipe/...,NaN,한식
9,https://www.10000recipe.com/recipe/7032079,https://recipe1.ezmember.co.kr/cache/recipe/20...,아임레시피,감자꽈리고추조림,감자가 맛난 계절 꽈리고추 넣어 맛있게 졸여보세요~ 이건 정말 말이 필요 없어지는 ...,2,15,아무나,"감자 3~4개, 꽈리고추작은거 20개, 다진마늘 1큰술, 고추장 1큰술, 된장 1작...","도마, 조리용나이프, 믹싱볼, 채반, 소스볼, 프라이팬, 조리용스푼, 접시",https://www.youtube.com/embed/yBCk2otlE5s,[{'text': '껍질벗긴 감자는 일정한 크기로 잘라요 찬물에 헹궈 물기를 탈탈 ...,['https://recipe1.ezmember.co.kr/cache/recipe/...,NaN,한식
10,https://www.10000recipe.com/recipe/7018922,https://recipe1.ezmember.co.kr/cache/recipe/20...,만개의레시피,크래미깻잎전,크래미와 깻잎으로 만드는 맛있는 반찬 향긋한 매력이 있는 크래미깻잎전 크래미를 깻잎...,2,15,아무나,"크래미 1팩, 깻잎 6장, 달걀 2개, 부침가루 3숟가락, 소금 약간, 식용유 약간","도마, 조리용나이프, 위생장갑, 유리볼, 요리젓가락, 프라이팬, 플레이팅접시",https://www.youtube.com/embed/soYa5k2K9os,[{'text': '깨끗하게 씻은 깻잎은 꼭지와 뾰족한 부분을 자르고 절반으로 잘라...,[],NaN,한식
13,https://www.10000recipe.com/recipe/7004960,https://recipe1.ezmember.co.kr/cache/recipe/20...,만개의레시피,두부피자,다이어트 중 피자가 먹고 싶을 때 빵 대신 두부를 이용해 피자를 만들어 보세요. 담...,3,30,아무나,"두부 1모, 토마토소스 6숟가락, 양파 1/4개, 방울토마토 3개, 닭가슴살 1/4...","도마, 프라이팬, 뒤집개",https://www.youtube.com/embed/Q6dqEeKbrOY,[{'text': '두부는(500g) 넓게 잘라 2~3등분 하고 물기를 제거해요.'...,['https://recipe1.ezmember.co.kr/cache/recipe/...,NaN,양식
20,https://www.10000recipe.com/recipe/7006926,https://recipe1.ezmember.co.kr/cache/recipe/20...,즐거운날랄라,알배추무침,불쓰기 힘든 요즘 불없이 간단하게 만들어 보세요,2,10,아무나,"알배추 300g, 대파 흰부분 1토막, 된장 1큰술, 국간장 1/2큰술, 참기름 1...","도마, 조리용나이프, 내열용기, 전자레인지, 유리볼, 위생장갑",https://www.youtube.com/embed/vAq_JQg-8sA,[{'text': '알배추는 적당한 크기로 썰은 후 깨끗하게 씻어요 씻은 알배추 전...,['https://recipe1.ezmember.co.kr/cache/recipe/...,NaN,한식
21,https://www.10000recipe.com/recipe/7002427,https://recipe1.ezmember.co.kr/cache/recipe/20...,즐거운날랄라,돼지고기감자조림,자박자박 매~콤~한 국물에 푹 익힌 감자와 야들야들 부드러운 돼지고기..... 밥 ...,3,20,아무나,"감자 3개, 돼지고기 앞다리살 250g, 양파 1/2개, 청양고추 3개, 대파 1/...","도마, 프라이팬, 요리주걱",https://www.youtube.com/embed/A8VTUfcHuRQ,"[{'text': '양파1/2개 채썰어주고 대파 1/2대, 청양고추 3개 어슷썰기 ...",['https://recipe1.ezmember.co.kr/cache/recipe/...,NaN,한식
24,https://www.10000recipe.com/recipe/7002301,https://recipe1.ezmember.co.kr/cache/recipe/20...,만개의레시피,우동,"국물 없이 간단하게 비벼먹는 우동 명란, 버터, 김가루, 쪽파 등을 올리고 쯔유를 ...",1,10,아무나,"우동면 1인분, 명란젓 1개, 쪽파 1줄, 버터 1조각, 달걀 1개, 김가루 약간,...","도마, 유리볼, 휴대용가스버너, 면기, 요리젓가락, 냄비, 채반",https://www.youtube.com/embed/UeZ1KV-97kA,"[{'text': '명란은 반을 가른 후 칼등으로 밀어 껍질을 제거해요', 'ima...",['https://recipe1.ezmember.co.kr/cache/recipe/...,NaN,일식
27,https://www.10000recipe.com/recipe/7042593,https://recipe1.ezmember.co.kr/cache/recipe/20...,음식중개사,애호박전,오늘은 흔한 애호박전에 고명 하나를 더해 꽃보다 예쁜 '애호박전' 레시피를 소개할게...,4,20,아무나,"애호박 2개, 계란 3개, 홍고추 1개, 소금 1/2작은술, 참치액젓 1/2큰술, ...","도마, 조리용나이프, 비닐봉지, 볼, 숟가락, 니트릴장갑, 프라이팬, 키친타올, 접시",https://www.youtube.com/embed/VUsXWQdnXzk,[{'text': '세척한 애호박을 1cm 두께로 썰어줍니다. 애호박이 너무 얇으면...,['https://recipe1.ezmember.co.kr/cache/recipe/...,NaN,한식
29,https://www.10000recipe.com/recipe/7037873,https://recipe1.ezmember.co.kr/cache/recipe/20...,김진옥요리가좋다,얼갈이드레싱무침,안녕하세요 김진옥입니다. 제가 금요일마다 어르신들 섬기는 봉사를 가는데요.. 지난 ...,4,10,아무나,"얼갈이손질전 무게 1kg, 다진마늘 2/3T, 국간장 1T, 갈은깨 1.5T, 들기...","니트릴장갑, 믹싱볼, 조리용나이프, 냄비, 조리주걱, 채반, 도마, 접시",https://www.youtube.com/embed/5w7JPVSk8UE,[{'text': '얼갈이 1키로 준비합니다. 손질전 무게입니다(누런잎 없었습니다)...,['https://recipe1.ezmember.co.kr/cache/recipe/...,**밥숟가락 계량입니다 **여름철 얼갈이가 억센경우에는 데치는 시간 조금만 늘려주세...,한식
31,https://www.10000recipe.com/recipe/7053709,https://recipe1.ezmember.co.kr/cache/recipe/20...,만개의레시피,소고기유부초밥,요즘 날씨가 정말 좋아서 나들이 많이 가시죠? 나들이에는 역시 뭐니뭐니해도 도시락!...,2,20,아무나,"소고기다짐육 300g, 밥 2공기, 유부 1팩, 쪽파 1줄, 통깨 약간, 진간장 3...","니트릴장갑, 볼, 키친타올, 도마, 조리용나이프, 조리주걱, 프라이팬, 숟가락, 접시",https://www.youtube.com/embed/k8_iuVqyNNM,"[{'text': '유부는 물기를 꼭 짜요.\n니트릴장갑 , 볼\n유부 손질법', ...",['https://recipe1.ezmember.co.kr/cache/recipe/...,NaN,일식
34,https://www.10000recipe.com/recipe/6894323,https://recipe1.ezmember.co.kr/cache/recipe/20...,뽀유TV,새송이버섯 간장버터구이,마땅한 반찬 없을때 새송이버섯 간장버터구이 한번 만들어 보세요!단짠단짠 양념에 고기...,2,10,아무나,"새송이버섯 3송이, 청양고추 1개, 대파 1/2대, 버터 1T, 간장 5T, 올리고...","나무도마, 믹싱볼, 요리스푼, 프라이팬, 사각접시",https://www.youtube.com/embed/qkgpxo2-DaQ,[{'text': '먼저 새송이 버섯 3동은 밑동을 제거하고 일정한 두께로 잘라 줍...,['https://recipe1.ezmember.co.kr/cache/recipe/...,버섯을 구울때 수분이 빠져나가 쫄깃해질때까지 구워 주세요,양식
52,https://www.10000recipe.com/recipe/7027008,https://recipe1.ezmember.co.kr/cache/recipe/20...,만개의레시피,부추비빔밥,"된장소스로 고소하고 감칠맛 있는 비빔밥 참치, 부추, 계란에 특제 된장소스를 넣고 ...",1,15,아무나,"부추 50g, 참치85g 1캔, 달걀 1개, 밥 1공기, 된장15g 1숟가락, 식초...","도마, 조리용나이프, 볼, 건지기채망, 조리용스푼, 소스볼, 프라이팬, 뒤집개, 면기",https://www.youtube.com/embed/u5f0dndiSP8,"[{'text': '부추는 잘게 잘라요.\n도마 , 조리용나이프\n부추 손질법', ...",['https://recipe1.ezmember.co.kr/cache/recipe/...,NaN,한식
58,https://www.10000recipe.com/recipe/7044761,https://recipe1.ezmember.co.kr/cache/recipe/20...,햇살머금은집,참치 양파볶음,그냥 먹어도 맛있는 참치양파볶음 만들기 해 볼께요.,4,5,아무나,"참치캔 1개, 양파 1개, 후추 약간, 통깨 약간, 설탕 1꼬집, 소금 1/2t","도마, 조리용나이프, 프라이팬, 숟가락, 요리스푼, 접시",https://tv.naver.com/embed/68654645?autoPlay=true,"[{'text': '양파 넣어서 더욱 맛있는 참치 양파볶음 만들기 해 볼께요.', ...",[],NaN,중식
62,https://www.10000recipe.com/recipe/7056654,https://recipe1.ezmember.co.kr/cache/recipe/20...,smallhealing,애호박 간장국수,언니네 산지직송 방송에서 영화배우 박정민이 쉬지 않고 먹으며 감탄한 반할 수밖에 없...,2,30,초급,"소면2인분 200g, 애호박 1개, 소금 2꼬집, 대파 1/2대, 청양고추 1/2개...","니트릴장갑, 도마, 조리용나이프, 믹싱볼, 궁중팬, 요리스푼, 숟가락, 볼, 냄비,...",https://www.youtube.com/embed/NzpIT-4s5fo,"[{'text': '애호박 1개 적당한 두께로 채 썬다.\n니트릴장갑 , 도마 , ...",['https://recipe1.ezmember.co.kr/cache/recipe/...,NaN,일식
67,https://www.10000recipe.com/recipe/7039774,https://recipe1.ezmember.co.kr/cache/recipe/20...,푸드디렉터요알남,차돌배기떡볶음,달콤하고 짭조름한 맛이 일품인 차돌박이 떡볶음입니다. 매운 거 못 드시는 분들은 한...,2,20,아무나,"떡국떡 300g, 차돌박이 200g, 새송이버섯 2개, 대파 1대, 청양고추 1개,...","볼, 도마, 조리용나이프, 채반, 볶음팬, 요리집게, 조리용스푼, 접시",https://www.youtube.com/embed/xLkkawphdE0,"[{'text': '떡국떡은 물에 10분 정도 불린다.\n볼', 'images': ...",[],NaN,한식
72,https://www.10000recipe.com/recipe/7020548,https://recipe1.ezmember.co.kr/cache/recipe/20...,아임레시피,표고버섯꽈리고추볶음,쫄깃쫄깃한 표고버섯에 꽈리고추를 볶아 밑반찬을 만들어보세요 이거 정말 너무너무 맛있...,2,15,아무나,"표고버섯 200g, 꽈리고추 90g, 홍고추 1개, 양파 1/4개, 진간장 2큰술,...","도마, 조리용나이프, 계량스푼, 유리계량컵, 프라이팬, 조리용스푼, 접시",https://www.youtube.com/embed/gXdkB28pkwo,[{'text': '표고버섯은 밑둥을 제거하고 슬라이스로 썰어주세요 (다른 야채들 ...,['https://recipe1.ezmember.co.kr/cache/recipe/...,NaN,한식
82,https://www.10000recipe.com/recipe/7004654,https://recipe1.ezmember.co.kr/cache/recipe/20...,만개의레시피,차돌박이부추무침,날씨가 더워지면 입맛이 떨어지곤 하는데요. 이럴때 새콤한 음식을 먹으면 침샘이 자극...,3,15,아무나,"차돌박이 200g, 부추 100g, 양파 1/2개, 홍고추 1개, 통깨 1숟가락, ...","믹싱볼, 도마, 프라이팬, 요리집게, 키친타올, 유리볼, 위생장갑, 가위",https://www.youtube.com/embed/QRfiJWQC3kM,"[{'text': '부추는 깨끗하게 세척한 후 3cm 정도로 썰어요', 'image...",[],NaN,한식
84,https://www.10000recipe.com/recipe/7010976,https://recipe1.ezmember.co.kr/cache/recipe/20...,즐거운날랄라,새송이버섯소고기볶음,새송이버섯과 소고기를 볶아보세요~! 정말 맛있습니다 ^^,3,15,아무나,"새송이버섯 4개, 국거리소고기 150g, 양파 1/2개, 대파 1/2대, 청양고추 ...","요리용스푼, 볼, 도마, 요리용나이프, 냄비, 프라이팬, 플레이팅접시",https://www.youtube.com/embed/XDnnMi4R_xk,"[{'text': '소고기 150g 진간장 1큰술, 참기름 1큰술 넣어 조물조물 밑...",[],NaN,중식
91,https://www.10000recipe.com/recipe/6925795,https://recipe1.ezmember.co.kr/cache/recipe/20...,두율이아빠,목살 양념구이,즉석양념장으로 간장베이스 소스를 만들어 돼지목살을 졸여 봤어요~ 양념장에 숙성시킨 ...,2,20,초급,"돼지목살 300g, 설탕 1T, 진간장 1-1/4T, 물엿 2T, 간마늘 1/2큰술...","믹싱볼, 요리스푼, 프라이팬, 휴대용가스렌지, 요리용집게, 주방가위, 계량컵",https://www.youtube.com/embed/OLB8shnr3Nc,[{'text': '페이지속 레시피 동영상 시청과!! 유튜브 구독은 레시피 제작에 ...,[],생강가루가 없으시면 간생강을 1/10T 정도 아주 소량만 넣어 주시면 됩니다~ 목살...,한식
101,https://www.10000recipe.com/recipe/7002443,https://recipe1.ezmember.co.kr/cache/recipe/20...,만개의레시피,닭고기 스테이크,닭다리살을 활용한 닭고기스테이크 큼직한 닭다리살과 가니쉬를 노릇하게 굽고 간장과 케...,2,30,아무나,"닭다리살 정육 300g, 소금 약간, 후추 약간, 바질가루 약간, 버터 1숟가락, ...","밧드트레이, 도마, 프라이팬, 주방집게, 요리스푼, 원형접시",https://www.youtube.com/embed/Uhz_YZzY88s,"[{'text': '닭다리살은 소금, 후추, 바질가루를 뿌려 재료 준비하는 동안 재...",['https://recipe1.ezmember.co.kr/cache/recipe/...,NaN,양식
108,https://www.10000recipe.com/recipe/7000243,https://recipe1.ezmember.co.kr/cache/recipe/20...,즐거운날랄라,양배추쌈,양배추와 두부 건강에도 좋고 다이어트에도 좋은 식재료이죠~ 양배추 두부 이렇게 먹으...,3,20,아무나,"양배추 적당히, 두부 1/2모, 참치 180g 1캔, 양파 1/2개, 대파 1/2대...","접시, 도마, 믹싱볼, 프라이팬, 조리용스푼, 전자레인지, 전자레인지용기",https://www.youtube.com/embed/u5Q4aBWqPDA,"[{'text': '양파 1/2개, 대파 1/2대, 청양고추 1~2개는 잘게 썰어주...",['https://recipe1.ezmember.co.kr/cache/recipe/...,NaN,한식
110,https://www.10000recipe.com/recipe/7020842,https://recipe1.ezmember.co.kr/cache/recipe/20...,만개의레시피,돼지고기마늘조림,구운마늘 듬뿍 넣어 만드는 돼지고기조림\r\n쫄깃한 목살로 맛있게 만드는 밥반찬\r...,2,30,아무나,"돼지목살 300g, 통마늘 1줌 45g, 전분가루1숟가락 20g, 맛술8g 1/2숟...","도마, 조리용나이프, 볼, 요리젓가락, 소스볼, 요리스푼, 프라이팬, 플레이팅접시",https://www.youtube.com/embed/p3XwzBIHqZY,"[{'text': '목살은 한 입 크기로 잘라요.', 'images': ['http...",[],NaN,한식
112,https://www.10000recipe.com/recipe/7054093,https://recipe1.ezmember.co.kr/cache/recipe/20...,만개의레시피,두부쉐이크,아침을 챙겨 먹는 건 정말 힘든 일이에요! 바쁜 아침에 간단하게 뭘 먹을 수 있을까...,2,15,아무나,"바나나 2개, 두부 1/2모, 땅콩버터 60g, 우유 300ml, 소금 약간, 알룰...","키친타올, 도마, 조리용나이프, 믹서기, 컵",https://www.youtube.com/embed/TNR_fOHVBSo,"[{'text': '두부는 가볍게 물기를 닦아요.\n키친타올', 'images': ...",['https://recipe1.ezmember.co.kr/cache/recipe/...,NaN,간식
121,https://www.10000recipe.com/recipe/7027181,https://recipe1.ezmember.co.kr/cache/recipe/20...,동주키친,통마늘표고버섯볶음,"나이가 들면 피로가 쌓이면, 면역력이 저하되면 각종 질병에 노출이 되기 때문에 고생...",4,30,아무나,"마늘 20개, 표고버섯 8개, 식용유 3T, 고추장 2T, 고춧가루 2T, 올리고당...","도마, 조리용나이프, 소스볼, 프라이팬, 요리스푼, 접시",https://www.youtube.com/embed/4OorT8GVXx4,"[{'text': '표고버섯은 0.5cm 간격으로 썰어 준비합니다.\n도마 , 조리...",['https://recipe1.ezmember.co.kr/cache/recipe/...,NaN,한식
127,https://www.10000recipe.com/recipe/7022304,https://recipe1.ezmember.co.kr/cache/recipe/20...,콩설기,감자전,평소에도 감자전을 참 좋아해요. 원조 감자전인 갈아서 만드는 게 제일 맛있지만 조금...,3,30,아무나,"감자 900g, 모짜렐라 치즈 600g, 청양고추 1-2개","감자칼, 믹싱볼, 도마, 조리용나이프, 채반, 요리스푼, 프라이팬, 뒤집개, 접시",https://tv.naver.com/embed/26304231?autoPlay=true,"[{'text': '감자는 깨끗이 씻어 껍질을 벗겨 주세요.\n감자칼 , 믹싱볼',...",[],NaN,한식
135,https://www.10000recipe.com/recipe/7031537,https://recipe1.ezmember.co.kr/cache/recipe/20...,냠냠간단요리,물비빔국수,새콤달콤 무더운 여름에 입맛 당기는 레시피 입니다!,1,10,초급,"소면120g 1인분, 냉면육수 1개, 대파 1줌, 진간장 2스푼, 설탕 4스푼, 고...","냄비, 요리젓가락, 채반, 플레이팅접시",https://www.youtube.com/embed/8lWCQpMkjMc,"[{'text': '소면을 삶아 찬물에 씻는다.', 'images': []}, {'...",[],NaN,한식
145,https://www.10000recipe.com/recipe/7035279,https://recipe1.ezmember.co.kr/cache/recipe/20...,만개의레시피,애호박 새우마요 볶음,탱글탱글한 새우와 부드러운 애호박의 환상 조화! 새우와 애호박을 마요네즈로 부드럽게...,1,20,아무나,"새우 300g, 애호박 1개, 올리브유 2T, 참기름 2T, 맛술 1T, 간장 1T...","볼, 니트릴장갑, 도마, 조리용나이프, 프라이팬, 조리용스푼, 접시",https://www.youtube.com/embed/nWQO8s-rTBE,"[{'text': '새우는 꼬리를 제거해 준비해요.\n볼 , 니트릴장갑\n새우 손질...",['https://recipe1.ezmember.co.kr/cache/recipe/...,NaN,한식
155,https://www.10000recipe.com/recipe/7028555,https://recipe1.ezmember.co.kr/cache/recipe/20...,만개의레시피,오일파스타,제오리를 볶아 나온 기름에 달달 볶은 시금치가 감칠맛을 더한 간단한 파스타에요. 훈...,1,30,아무나,"파스타면 1인분, 훈제오리 130g, 시금치 100g, 페페론치노 1t, 올리브오일...","도마, 조리용나이프, 냄비, 요리집게, 프라이팬, 플레이팅접시",https://www.youtube.com/embed/h8SdqVYYHbI,"[{'text': '시금치는 끝부분을 잘라 손질해요.\n도마 , 조리용나이프\n시금...",[],NaN,양식
166,https://www.10000recipe.com/recipe/7039931,https://recipe1.ezmember.co.kr/cache/recipe/20...,lemontree,"참치 파스타, 두부면 파스타",살 찔 걱정 없이 스트레스를 날려줄 매콤한 토마토 참치 파스타 소개해요:) 매콤한 ...,2,20,초급,"두부면 200g, 참치캔 150g, 토마토퓨레 250g, 엔초비선택 2마리, 양파 ...","도마, 조리용나이프, 볼, 프라이팬, 조리용스푼, 플레이팅접시, 요리젓가락",https://www.youtube.com/embed/Fx1I1nTSbgI,"[{'text': '양파는 작은 큐브모양으로 썰어주세요.\n도마 , 조리용나이프',...",['https://recipe1.ezmember.co.kr/cache/recipe/...,NaN,양식
185,https://www.10000recipe.com/recipe/6998851,https://recipe1.ezmember.co.kr/cache/recipe/20...,만개의레시피,어묵비빔국수,"간단하고 맛있는 비빔국수 만드는 법! 양념장, 어묵, 소면으로 순식간에 한끼 완성 ...",1,15,아무나,"소면 1인분, 어묵 3장, 깻잎 3장, 통깨 약간, 고추장 2숟가락, 고춧가루 1/...","유리볼, 조리용스푼, 도마, 조리용나이프, 냄비, 채망, 조리용젓가락, 위생장갑, 면기",https://www.youtube.com/embed/S86xXH74dMg,"[{'text': '양념 재료를 섞어 양념장을 만들어요\n유리볼 , 조리용스푼\n양...",['https://recipe1.ezmember.co.kr/cache/recipe/...,NaN,간식
188,https://www.10000recipe.com/recipe/7045801,https://recipe1.ezmember.co.kr/cache/recipe/20...,만개의레시피,소고기볶음,"장조림인 것 같지만 조금 다른 꽈리고추 소고기볶음 레시피에요. 간장, 굴소스로 간을...",2,30,아무나,"소고기 불고기용 200g, 꽈리고추 10개, 통깨 약간, 간장 3T, 다진마늘 1T...","도마, 키친타올, 프라이팬, 조리주걱, 접시, 소스볼, 계량스푼",https://www.youtube.com/embed/Oun20Noj6Qw,"[{'text': '꽈리고추는 꼭지를 떼서 손질해요. .\n나무도마', 'image...",[],간장양념의 경우 양에따라 간보면서 조금씩만 추가해주세요^^,한식
209,https://www.10000recipe.com/recipe/7044002,https://recipe1.ezmember.co.kr/cache/recipe/20...,만개의레시피,계란탕,다시 기온이 훅 떨어지고나니 따뜻한 국물이 당기는 건..역시나..\r\n몽글몽글 계...,4,30,아무나,"달걀 3개, 미림 1T, 표고버섯 2개, 대파 2대, 양파 1개, 당면 한줌 100...","나무도마, 조리용나이프, 볼, 컵, 프라이팬, 조리주걱, 그릇",https://www.youtube.com/embed/ywtrH2KQwVk,"[{'text': '대파는 반으로 갈라 5cm 길이로 넓게 썰어요.\n나무도마 , ...",[],NaN,한식
211,https://www.10000recipe.com/recipe/7004106,https://recipe1.ezmember.co.kr/cache/recipe/20...,즐거운날랄라,가지덮밥,가지의 폴리페놀 성분이 혈당 수치 조절하는데 도움이 되고 섬유질 함량이 높아 포만감...,1,10,아무나,"가지 1~2개, 양파 1/2개, 밥 1~2공기, 버터 1~1.5큰술, 참치액젓 1큰...","계량컵, 요리스푼, 도마, 프라이팬, 계량스푼, 면기",https://www.youtube.com/embed/e9GMAH6WQU0,"[{'text': '분량의 양념을 미리 만들어 주세요. 진간장 2큰술, 설탕 1/2...",['https://recipe1.ezmember.co.kr/cache/recipe/...,?? 양념 재료 (2인분) : 참치액젓 1.5큰술 진간장 3큰술 설탕 2/3큰술 올...,일식
221,https://www.10000recipe.com/recipe/6899335,https://recipe1.ezmember.co.kr/cache/recipe/20...,집밥이박사,양배추어묵볶음,어묵볶음의 부족한 아삭함을 양배추가 확실히 잡아주네요.,2,10,아무나,"어묵 4장, 양배추 2장, 당근 조금, 대파 1개, 간장 3T, 굴소스 1T, 물엿...","채칼, 프라이팬, 뒤집기, 원형접시",https://www.youtube.com/embed/ToHeC_WVnuo,"[{'text': '분량의 재료를 채 썰어주세요. 대파는 송송송', 'images'...",['https://recipe1.ezmember.co.kr/cache/recipe/...,간장을 살짝 눌리면 간장향이 더욱 풍부해져요~,한식

In [23]:
recipes.shape

(40, 15)

In [24]:
recipes_tools = (
    recipes.assign(tools=lambda df: df['tools'].str.split(','))
          .explode('tools')
          .assign(tools=lambda df: df['tools'].str.strip())
          .reset_index(drop=True)[['title', 'tools']]
)
recipes_tools[['title', 'tools']]

       title   tools
0    소고기 고추장    키친타올
1    소고기 고추장     믹싱볼
2    소고기 고추장      도마
3    소고기 고추장  조리용나이프
4    소고기 고추장    계량스푼
..       ...     ...
272     가지덮밥      면기
273  양배추어묵볶음      채칼
274  양배추어묵볶음    프라이팬
275  양배추어묵볶음     뒤집기
276  양배추어묵볶음    원형접시

[277 rows x 2 columns]

In [28]:
recipes_tools['tools'].unique()

array(['키친타올', '믹싱볼', '도마', '조리용나이프', '계량스푼', '프라이팬', '요리스푼', '완성그릇', '볼',
       '냄비', '조리주걱', '채반', '접시', '인덱스도마', '볶음팬', '나무도마', '찬기', '숟가락',
       '소스볼', '조리용집게', '니트릴장갑', '조리용스푼', '위생장갑', '유리볼', '요리젓가락', '플레이팅접시',
       '뒤집개', '내열용기', '전자레인지', '요리주걱', '휴대용가스버너', '면기', '비닐봉지', '사각접시',
       '건지기채망', '궁중팬', '요리집게', '유리계량컵', '가위', '요리용스푼', '요리용나이프',
       '휴대용가스렌지', '요리용집게', '주방가위', '계량컵', '밧드트레이', '주방집게', '원형접시',
       '전자레인지용기', '믹서기', '컵', '감자칼', '채망', '조리용젓가락', '그릇', '채칼', '뒤집기'],
      dtype=object)

In [47]:
recipes_tools.to_csv('recipes_tools.csv', index=False)

In [33]:
recipes.head(1)

,url,main_image,author,title,description,servings,time,difficulty,materials,tools,video_url,steps,final_images,tips,category
0,https://www.10000recipe.com/recipe/7056958,https://recipe1.ezmember.co.kr/cache/recipe/20...,반이짝이,소고기 고추장,더운 여름에 입맛 없을 때 열무김치나 생야채 넣고 비빔밥 만들어먹거나 달걀프라이만 ...,2,20,초급,"다진소고기 200g, 양파 1/4개, 대파 1/4대, 다진마늘 1큰술, 진간장 1/...","키친타올, 믹싱볼, 도마, 조리용나이프, 계량스푼, 프라이팬, 요리스푼, 완성그릇",https://tv.naver.com/embed/21142287?autoPlay=true,[{'text': '다짐육 200g 정도를 준비한 다음 먼저 키친타월로 핏물을 제거...,['https://recipe1.ezmember.co.kr/cache/recipe/...,나물 반찬 만들어둔게 있어서 비빔밥 만들어먹을 때 약고추장 넣고 슥슥 비벼서 먹었더...,한식

In [48]:
# 정규표현식 패턴
pattern = r"^(?P<ingredients>[^\d]+?)\s*(?P<quantity>\d+(?:/\d+)?)?\s*(?P<unit>[가-힣a-zA-Z]+)?$"

recipes_ingredients = (
    recipes
    .assign(ingredients=lambda df: df['materials'].str.split(','))  # 재료 리스트 분리
    .explode('ingredients')                                         # 행으로 펼치기
    .assign(ingredients=lambda df: df['ingredients'].str.strip())     # 공백 제거
    .reset_index(drop=True)[['title', 'ingredients']]
)

recipes_ingredients = pd.concat([recipes_ingredients['title'], recipes_ingredients['ingredients'].str.extract(pattern)], axis=1)

recipes_ingredients

       title ingredients quantity unit
0    소고기 고추장       다진소고기      200    g
1    소고기 고추장          양파      1/4    개
2    소고기 고추장          대파      1/4    대
3    소고기 고추장        다진마늘        1   큰술
4    소고기 고추장         진간장      1/2   큰술
..       ...         ...      ...  ...
382  양배추어묵볶음          대파        1    개
383  양배추어묵볶음          간장        3    T
384  양배추어묵볶음         굴소스        1    T
385  양배추어묵볶음          물엿        3    T
386  양배추어묵볶음         참기름        1    T

[387 rows x 4 columns]

In [49]:
recipes_ingredients.to_csv('recipes_ingredients.csv', index=False)