## 이름 정제

In [1]:
import pandas as pd
from openai import OpenAI
import time

client = OpenAI(api_key="sktax-XyeKFrq67ZjS4EpsDlrHHXV8it", base_url="https://guest-api.sktax.chat/v1")

# CSV 읽기
recipes = pd.read_csv("recipes_easy.csv")

def clean_title_with_ai(title: str) -> str:
    prompt = (
        f"다음 요리 제목에서 불필요한 설명, 괄호 속 내용, 수식어를 제거하고 "
        f"순수한 음식 이름만 추출하세요.\n"
        f"순수한 음식 이름만 출력하고, 다른 말은 절대 하지 마세요.\n"
        f"입력: {title}\n"
        f"출력:"
    )

    completion = client.chat.completions.create(
        model="ax4",
        messages=[
            {"role": "user", "content": prompt}
        ]
    )

    return completion.choices[0].message.content.strip()

# 한 행씩 처리
cleaned_titles = []
for idx, row in recipes[:30].iterrows():
    cleaned = clean_title_with_ai(row["title"])
    cleaned_titles.append(cleaned)
    
    print(f"{idx+1}/{len(recipes)} 처리 완료: {cleaned}")

1/113 처리 완료: 떡꼬치
2/113 처리 완료: 계란빵 꿀빵
3/113 처리 완료: 고구마 빵
4/113 처리 완료: 코울슬로, 사라다빵
5/113 처리 완료: 또띠아 피자
6/113 처리 완료: 스파게티 샌드위치
7/113 처리 완료: 치즈 샌드위치
8/113 처리 완료: 양배추샌드위치
9/113 처리 완료: 샌드위치
10/113 처리 완료: 연어 샌드위치
11/113 처리 완료: 샌드위치
12/113 처리 완료: 닭가슴살샌드위치
13/113 처리 완료: 닭가슴살브리또
14/113 처리 완료: 샌드위치
15/113 처리 완료: 딸기롤샌드위치
16/113 처리 완료: 에그 샌드위치
17/113 처리 완료: 두부 계란찜
18/113 처리 완료: 몬테크리스토 샌드위치
19/113 처리 완료: 딸기샌드위치
20/113 처리 완료: 오픈샌드위치
21/113 처리 완료: 닭 가슴살 샐러드, 샌드위치
22/113 처리 완료: 아보카도 샌드위치
23/113 처리 완료: 베이컨 샌드위치
24/113 처리 완료: 스파이시슈림프샌드위치
25/113 처리 완료: 연어샌드위치
26/113 처리 완료: 오픈 샌드위치
27/113 처리 완료: 메추리알맛살샌드위치
28/113 처리 완료: 모닝롤
29/113 처리 완료: 버터비빔밥
30/113 처리 완료: 파니니샌드위치

In [4]:

for idx, row in recipes[30:60].iterrows():
    cleaned = clean_title_with_ai(row["title"])
    cleaned_titles.append(cleaned)
    
    print(f"{idx+1}/{len(recipes)} 처리 완료: {cleaned}")

31/113 처리 완료: 치즈샌드위치
32/113 처리 완료: 오징어 샐러드
33/113 처리 완료: 닭가슴살 무침
34/113 처리 완료: 게맛살 또띠아 샌드위치
35/113 처리 완료: 견과아몬드쿠키
36/113 처리 완료: 콩나물무침
37/113 처리 완료: 통 삼겹살
38/113 처리 완료: 옥수수치즈
39/113 처리 완료: 소고기
고구마
40/113 처리 완료: 웨지고구마
41/113 처리 완료: 누룽지
42/113 처리 완료: 떡꼬치
43/113 처리 완료: 크로크무슈
44/113 처리 완료: 브라질 치즈빵
45/113 처리 완료: 얼그레이 사브레 쿠키
46/113 처리 완료: 카레구이
47/113 처리 완료: 숙주나물무침
48/113 처리 완료: 마약달걀장
49/113 처리 완료: 멸치고추지볶음
50/113 처리 완료: 삼겹살김치파스타
51/113 처리 완료: 오믈렛
52/113 처리 완료: 볶음밥
53/113 처리 완료: 토마토 계란 피자
54/113 처리 완료: 마늘볶음밥
55/113 처리 완료: 알리오 올리오
56/113 처리 완료: 해물 토스트
57/113 처리 완료: 명란젓 마요계란밥
58/113 처리 완료: 메밀소바
59/113 처리 완료: 모짜프렌치토스트
60/113 처리 완료: 참치마요 주먹밥

In [6]:

for idx, row in recipes[60:90].iterrows():
    cleaned = clean_title_with_ai(row["title"])
    cleaned_titles.append(cleaned)
    
    print(f"{idx+1}/{len(recipes)} 처리 완료: {cleaned}")

61/113 처리 완료: 상추 주먹밥
62/113 처리 완료: 들기름 막국수
간장비빔메밀국수
63/113 처리 완료: 아보카도 참치마요 덮밥
64/113 처리 완료: 두부 덮밥
65/113 처리 완료: 마요네즈계란밥
66/113 처리 완료: 볶음밥
67/113 처리 완료: 버터비빔밥
68/113 처리 완료: 찹스테이크
69/113 처리 완료: 삼겹살 상추 조림
70/113 처리 완료: 야채 김 계란말이
71/113 처리 완료: 돈까스 샌드위치
72/113 처리 완료: 양배추 만둣국
73/113 처리 완료: 명란,된장
74/113 처리 완료: 참치샐러드
75/113 처리 완료: 카레 주먹밥
76/113 처리 완료: 열무김치국수
77/113 처리 완료: 치즈떡 계란말이
78/113 처리 완료: 비빔국수
79/113 처리 완료: 김치찌개
80/113 처리 완료: 콩나물국
81/113 처리 완료: 간장파스타
82/113 처리 완료: 국물떡볶이
83/113 처리 완료: 계란빵, 꿀빵
84/113 처리 완료: 연어 샐러드
85/113 처리 완료: 소세지야채볶음
86/113 처리 완료: 달걀 볶음밥
87/113 처리 완료: 두부찌개
88/113 처리 완료: 데리야키 닭고기
89/113 처리 완료: 몬테크리스토 시리얼 토스트
90/113 처리 완료: 김밥

In [7]:

for idx, row in recipes[90:113].iterrows():
    cleaned = clean_title_with_ai(row["title"])
    cleaned_titles.append(cleaned)
    
    print(f"{idx+1}/{len(recipes)} 처리 완료: {cleaned}")

91/113 처리 완료: 카레라이스
92/113 처리 완료: 쇠고기볶음
93/113 처리 완료: 김치부침개피자
94/113 처리 완료: 식빵피자
95/113 처리 완료: 콘치즈
96/113 처리 완료: 김치볶음밥
97/113 처리 완료: 꿀피자
98/113 처리 완료: 계란프라이
99/113 처리 완료: 프렌치 토스트
100/113 처리 완료: 감자
101/113 처리 완료: 계란죽
102/113 처리 완료: 크림우동
103/113 처리 완료: 밥버거
104/113 처리 완료: 스파게티
105/113 처리 완료: 계란찜
106/113 처리 완료: 토스트
107/113 처리 완료: 로제떡볶이
108/113 처리 완료: 꿀빵
109/113 처리 완료: 토스트
110/113 처리 완료: 피자계란밥
111/113 처리 완료: 볶음밥
112/113 처리 완료: 스팸계란밥
113/113 처리 완료: 계란찜

In [ ]:

# for idx, row in recipes[120:150].iterrows():
#     cleaned = clean_title_with_ai(row["title"])
#     cleaned_titles.append(cleaned)
    
#     print(f"{idx+1}/{len(recipes)} 처리 완료: {cleaned}")

121/251 처리 완료: 비빔만두
122/251 처리 완료: 부타동
123/251 처리 완료: 오레오 치즈케이크
124/251 처리 완료: 스팸 맛탕
125/251 처리 완료: 카레주먹밥
126/251 처리 완료: 부타동
127/251 처리 완료: 토마토부르스케타
128/251 처리 완료: 장떡만둣국
129/251 처리 완료: 식빵팝콘
130/251 처리 완료: 통마늘표고버섯볶음
131/251 처리 완료: 두부 파프리카전, 두부, 달걀
132/251 처리 완료: 고구마에그슬럿
133/251 처리 완료: 빨간 오뎅 / Spicy fish cakes
134/251 처리 완료: 고구마채전
135/251 처리 완료: 바치 디 다마
136/251 처리 완료: 파프리카 피자
137/251 처리 완료: 허니윙
138/251 처리 완료: 감자전
139/251 처리 완료: 토스트
140/251 처리 완료: 야채샐러드빵
141/251 처리 완료: 무침만두
142/251 처리 완료: 떡볶음
143/251 처리 완료: 버섯볶음두부면
144/251 처리 완료: 카페모카쿠키슈
145/251 처리 완료: 양파덮밥
146/251 처리 완료: 컵케이크
147/251 처리 완료: 오이들깨무침
148/251 처리 완료: 물비빔국수
149/251 처리 완료: 불참치장
150/251 처리 완료: 치즈 공구마

In [ ]:

# for idx, row in recipes[150:180].iterrows():
#     cleaned = clean_title_with_ai(row["title"])
#     cleaned_titles.append(cleaned)
    
#     print(f"{idx+1}/{len(recipes)} 처리 완료: {cleaned}")

151/251 처리 완료: 모카 케이크
152/251 처리 완료: 숙주볶음
153/251 처리 완료: 치즈 쿠키
154/251 처리 완료: 초코 비스코티
155/251 처리 완료: 고추장황태채볶음
156/251 처리 완료: 된장삼겹살덮밥
157/251 처리 완료: 오징어말이
158/251 처리 완료: 애호박 새우마요 볶음
159/251 처리 완료: 돼지갈비
160/251 처리 완료: 두부스테이크
161/251 처리 완료: 두부 마요네즈
162/251 처리 완료: 크림 새송이
163/251 처리 완료: 오이롤초밥
164/251 처리 완료: 콘치즈 고로케
165/251 처리 완료: 표고버섯 덮밥
166/251 처리 완료: 가지탕수
167/251 처리 완료: 그라탱
168/251 처리 완료: 우유달걀카레
169/251 처리 완료: 오일파스타
170/251 처리 완료: 황태채 버터구이
171/251 처리 완료: 대패대파구이
172/251 처리 완료: 베이컨치즈밥말이
173/251 처리 완료: 양파튀김
174/251 처리 완료: 사과 케이크
175/251 처리 완료: 새송이
176/251 처리 완료: 훈제오리볶음
오리훈제볶음
양배추볶음
177/251 처리 완료: 파프리카된장무침
178/251 처리 완료: 닭마볶음밥
179/251 처리 완료: 우삼겹 덮밥 규동
180/251 처리 완료: 가지 라자냐

In [ ]:
# for idx, row in recipes[180:210].iterrows():
#     cleaned = clean_title_with_ai(row["title"])
#     cleaned_titles.append(cleaned)
    
#     print(f"{idx+1}/{len(recipes)} 처리 완료: {cleaned}")

181/251 처리 완료: 닭죽
182/251 처리 완료: 참치 파스타, 두부면 파스타
183/251 처리 완료: 떡감자
184/251 처리 완료: 느타리두루치기
185/251 처리 완료: 오이무침
186/251 처리 완료: 콩나물무침
187/251 처리 완료: 간장두부장
188/251 처리 완료: 돈까스 김치나베
189/251 처리 완료: 얼큰만둣국
190/251 처리 완료: 시금치 플랫브레드 피자
191/251 처리 완료: 마늘빵
마늘빵
마늘빵
식빵
192/251 처리 완료: 돼지불백
193/251 처리 완료: 녹차머핀
194/251 처리 완료: 참치맛나니
195/251 처리 완료: 프리타타
196/251 처리 완료: 아망디오 쇼콜라
197/251 처리 완료: 할로윈 브라우니 쿠키
198/251 처리 완료: 연어 파피요트
199/251 처리 완료: 새송이버섯 고추장구이
200/251 처리 완료: 뢰스티
201/251 처리 완료: 츄러스
202/251 처리 완료: 어묵비빔국수
203/251 처리 완료: 김치마요우동
204/251 처리 완료: 하트파이 팔미에
205/251 처리 완료: 달걀떡볶이
206/251 처리 완료: 소고기볶음
207/251 처리 완료: 양파햄치즈빵
208/251 처리 완료: 게살버거
209/251 처리 완료: 크랜베리 화이트 초코 쿠키
210/251 처리 완료: 모카 컵케이크

In [ ]:

# for idx, row in recipes[210:240].iterrows():
#     cleaned = clean_title_with_ai(row["title"])
#     cleaned_titles.append(cleaned)
    
#     print(f"{idx+1}/{len(recipes)} 처리 완료: {cleaned}")

211/251 처리 완료: 어향치킨
212/251 처리 완료: 체리클라푸티
213/251 처리 완료: 순두부 계란
214/251 처리 완료: 투움바파스타
215/251 처리 완료: 오레오 크림치즈 머핀
216/251 처리 완료: 버터구이 진미채
217/251 처리 완료: 함양파 링전
218/251 처리 완료: 스팸아보카도덮밥
219/251 처리 완료: 고추참치비빔우동
220/251 처리 완료: 면두부 크림파스타
221/251 처리 완료: 스팸마요 덮밥
222/251 처리 완료: 사과 크렘블 파이
223/251 처리 완료: 스카레
224/251 처리 완료: 어묵노미야끼
225/251 처리 완료: 콘치즈
226/251 처리 완료: 식빵 러스크 (에어프라이어)
227/251 처리 완료: 소고기쪽파말이
228/251 처리 완료: 딸기잼 쿠키
과일잼 쿠키
229/251 처리 완료: 계란탕
230/251 처리 완료: 오징어볶음
231/251 처리 완료: 시나몬 롤 쿠키
232/251 처리 완료: 가지덮밥
233/251 처리 완료: 시래기지짐
234/251 처리 완료: 파마산 치즈 쿠키
235/251 처리 완료: 소시지강정
236/251 처리 완료: 식빵팝콘
237/251 처리 완료: 베이컨말이
238/251 처리 완료: 퍼지 브라우니
239/251 처리 완료: 대파토스트
240/251 처리 완료: 소시지콩나물찜

In [ ]:

# for idx, row in recipes[240:251].iterrows():
#     cleaned = clean_title_with_ai(row["title"])
#     cleaned_titles.append(cleaned)
    
#     print(f"{idx+1}/{len(recipes)} 처리 완료: {cleaned}")

241/251 처리 완료: 아보카도 베이컨구이
242/251 처리 완료: 고구마조림
243/251 처리 완료: 주먹밥
244/251 처리 완료: 양배추어묵볶음
245/251 처리 완료: 구운 참치 주먹밥
246/251 처리 완료: 퐁크러쉬 쉐이크
247/251 처리 완료: 소시지 배추 롤
248/251 처리 완료: 돼지불백
249/251 처리 완료: 등갈비
250/251 처리 완료: 초코칩쿠키
251/251 처리 완료: 커피콩 쿠키

In [8]:

recipes["title"] = cleaned_titles
recipes

,Unnamed: 0,url,title,description,servings,time,difficulty,materials,tools,steps,final_images,tips,danger
0,1,https://www.10000recipe.com/recipe/6953727,떡꼬치,떡꼬치를 너무 좋아하는데 요즘 파는곳이 별로 없어서\n간단하게 집에서 한번 만들어봤...,2인분,15분 이내,초급,"가래떡 7개, 기름 조금, 케찹 3큰술, 진간장 1/2큰술, 고추장 1큰술, 올리고...",에어프라이어,[{'text': '떡에 기름을 골고루 조금씩 묻혀 에어프라이어에 돌려줍니다\n18...,[],"저는 이마트에서 2,000원짜리 떡 한팩을 사와서 냉동에 넣지않고 바로 뒷날 해먹었...",0
1,3,https://www.10000recipe.com/recipe/6928779,계란빵 꿀빵,계란빵도 먹고 꿀빵도 먹고 즐거운 간식 타임에 모양틀을 이용해 아이와 함께 또는 혼...,2인분,15분 이내,초급,"빵 4장, 달걀 2개, 슬라이스 치즈 2장, 소금 톡톡, 꿀 듬뿍","오븐, 숟가락","[{'text': '1 계란빵 만들기\n빵에 구멍을 냅니다', 'images': [...",['https://recipe1.ezmember.co.kr/cache/recipe/...,큼직한 식빵에 만들면 더 쉬워요,0
2,5,https://www.10000recipe.com/recipe/6728751,고구마 빵,"초간단 노오븐 베이킹. 노버터, 노밀가루라 아기에게 딱!! 건강한 간식이예요",2인분,30분 이내,초급,"고구마 2개, 계란 흰자 2개, 올리브오일 약간","오븐, 숟가락",[{'text': '고구마는 껍질을 까고 쪄낸 후 뜨거울때 으깨주세요. 고구마가 달...,['https://recipe1.ezmember.co.kr/cache/recipe/...,NaN,0
3,10,https://www.10000recipe.com/recipe/6881646,"코울슬로, 사라다빵",새콤달콤한 양배추 샐러드 '코울슬로'와\n모닝빵 대신 통식빵을 이용한 '사라다빵'을...,6인분 이상,30분 이내,초급,"양배추 350g, 사과 1/2개, 캔옥수수 100g, 마요네즈 5큰술, 레몬즙 3큰...","오븐, 숟가락","[{'text': '분량의 마요네즈, 레몬즙, 연유, 천일염을 잘 섞고 통후추도 갈...",['https://recipe1.ezmember.co.kr/cache/recipe/...,서너시간 지나 맛을 보고 좀 더 새콤달콤한 맛을 원한다면 레몬즙과 연유를 입맛에 맞...,0
4,15,https://www.10000recipe.com/recipe/6880305,또띠아 피자,달걀지단이 들어간\n사과 또띠아 피자!,2인분,15분 이내,초급,"사과 1/4개, 사과잼 3T, 또띠아 1개, 미트스파게티소스 3T, 달걀 1개, 견...","전자레인지,에어프라이어",[{'text': '* 재료 준비\n또띠아 1개\n사과 1/4개\n사과잼 3T\n미...,['https://recipe1.ezmember.co.kr/cache/recipe/...,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
108,123,https://youtu.be/nKZ_bKiDeVY?list=TLGGgpMG1C4C...,토스트,NaN,NaN,NaN,NaN,"식빵, 달걀, 샌드위치 햄, 설탕, 케첩, 마요네즈","숟가락, 전자레인지",NaN,NaN,NaN,0
109,124,https://youtu.be/Z2vjsJZnXog?list=TLGGk0UrLaeB...,피자계란밥,NaN,NaN,NaN,NaN,"밥 100g, 계란 1알, 케첩, 모짜렐라 치즈","숟가락, 전자레인지",NaN,NaN,NaN,0
110,125,https://youtu.be/YQZn6dQV0xg?list=TLGGSlnnq6am...,볶음밥,NaN,NaN,NaN,NaN,"즉석밥 1개, 계란 2알, 스팸, 김치","숟가락, 가위, 전자레인지, 깊은 그릇(유리, 사기)","1. 재료 준비\n- 즉석밥 1개, 계란 2알, 스팸, 김치\n2. 조리도구준비\n...",NaN,NaN,0
111,126,https://youtu.be/e9VVSZei8hU?list=TLGGLCgQyHYh...,스팸계란밥,NaN,NaN,NaN,NaN,"계란 2알, 즉석밥 1개, 스팸, 파, 소금, 간장","깊은 그릇, 전자레인지, 비닐랩",NaN,NaN,NaN,0
112,127,https://youtu.be/j1JVxiuNSuU?list=TLGGfkA0RV52...,계란찜,NaN,NaN,NaN,NaN,"계란 1알, 우유 200ml, 카레가루, 파, 즉석밥 1","숫가락, 전자레인지, 가위",NaN,NaN,NaN,0

In [9]:

recipes.to_csv("recipes_cleaned.csv")

In [36]:
# title 길이가 15 이하인 행만 남기기
recipes = recipes[recipes['title'].str.len() <= 15]

# 결과 저장
recipes.to_csv("recipes_cleaned.csv", index=False)

## 카테고리 추가

In [7]:
import pandas as pd
from openai import OpenAI
import time

client = OpenAI(api_key="sktax-XyeKFrq67ZjS4EpsDlrHHXV8it", base_url="https://guest-api.sktax.chat/v1")

In [10]:
# AI에게 카테고리 분류 요청
def categorize_with_ai(title):
    """
    title을 입력하면 AI가 한식, 중식, 양식, 디저트, 음료 등으로 분류
    """
    prompt = f"다음 음식 제목을 보고 [한식, 중식, 양식, 일식, 간식, 기타] 중 가장 적절한 카테고리 하나만 선택하세요.\n선택한 카테고리의 단어만 출력하고, 다른 말은 절대 하지 마세요.\n\n음식 제목: {title}"
    completion = client.chat.completions.create(
        model="ax4",
        messages=[{"role": "user", "content": prompt}]
    )
    # AI 응답에서 텍스트 추출
    category = completion.choices[0].message.content.strip()
    return category

In [11]:
# CSV 불러오기
recipes = pd.read_csv("recipes_cleaned.csv")

# category 컬럼 초기화
categories = []

In [12]:
for idx, row in recipes[:30].iterrows():
    cat = categorize_with_ai(row["title"])
    categories.append(cat)
    print(f"{idx+1}/{len(recipes)} 처리 완료: {row['title']} -> {cat}")

1/113 처리 완료: 떡꼬치 -> 간식
2/113 처리 완료: 계란빵 꿀빵 -> 간식
3/113 처리 완료: 고구마 빵 -> 간식
4/113 처리 완료: 코울슬로, 사라다빵 -> 양식
5/113 처리 완료: 또띠아 피자 -> 간식
6/113 처리 완료: 스파게티 샌드위치 -> 양식
7/113 처리 완료: 치즈 샌드위치 -> 양식
8/113 처리 완료: 양배추샌드위치 -> 양식
9/113 처리 완료: 샌드위치 -> 양식
10/113 처리 완료: 연어 샌드위치 -> 양식
11/113 처리 완료: 샌드위치 -> 양식
12/113 처리 완료: 닭가슴살샌드위치 -> 양식
13/113 처리 완료: 닭가슴살브리또 -> 양식
14/113 처리 완료: 샌드위치 -> 양식
15/113 처리 완료: 딸기롤샌드위치 -> 간식
16/113 처리 완료: 에그 샌드위치 -> 양식
17/113 처리 완료: 두부 계란찜 -> 한식
18/113 처리 완료: 몬테크리스토 샌드위치 -> 양식
19/113 처리 완료: 딸기샌드위치 -> 간식
20/113 처리 완료: 오픈샌드위치 -> 양식
21/113 처리 완료: 닭 가슴살 샐러드, 샌드위치 -> 간식
22/113 처리 완료: 아보카도 샌드위치 -> 양식
23/113 처리 완료: 베이컨 샌드위치 -> 양식
24/113 처리 완료: 스파이시슈림프샌드위치 -> 양식
25/113 처리 완료: 연어샌드위치 -> 양식
26/113 처리 완료: 오픈 샌드위치 -> 양식
27/113 처리 완료: 메추리알맛살샌드위치 -> 양식
28/113 처리 완료: 모닝롤 -> 간식
29/113 처리 완료: 버터비빔밥 -> 한식
30/113 처리 완료: 파니니샌드위치 -> 양식

In [13]:
for idx, row in recipes[30:60].iterrows():
    cat = categorize_with_ai(row["title"])
    categories.append(cat)
    print(f"{idx+1}/{len(recipes)} 처리 완료: {row['title']} -> {cat}")

31/113 처리 완료: 치즈샌드위치 -> 양식
32/113 처리 완료: 오징어 샐러드 -> 양식
33/113 처리 완료: 닭가슴살 무침 -> 한식
34/113 처리 완료: 게맛살 또띠아 샌드위치 -> 간식
35/113 처리 완료: 견과아몬드쿠키 -> 간식
36/113 처리 완료: 콩나물무침 -> 한식
37/113 처리 완료: 통 삼겹살 -> 한식
38/113 처리 완료: 옥수수치즈 -> 간식
39/113 처리 완료: 소고기
고구마 -> 간식
40/113 처리 완료: 웨지고구마 -> 간식
41/113 처리 완료: 누룽지 -> 한식
42/113 처리 완료: 떡꼬치 -> 간식
43/113 처리 완료: 크로크무슈 -> 양식
44/113 처리 완료: 브라질 치즈빵 -> 간식
45/113 처리 완료: 얼그레이 사브레 쿠키 -> 간식
46/113 처리 완료: 카레구이 -> 중식
47/113 처리 완료: 숙주나물무침 -> 한식
48/113 처리 완료: 마약달걀장 -> 중식
49/113 처리 완료: 멸치고추지볶음 -> 한식
50/113 처리 완료: 삼겹살김치파스타 -> 양식
51/113 처리 완료: 오믈렛 -> 양식
52/113 처리 완료: 볶음밥 -> 중식
53/113 처리 완료: 토마토 계란 피자 -> 양식
54/113 처리 완료: 마늘볶음밥 -> 중식
55/113 처리 완료: 알리오 올리오 -> 양식
56/113 처리 완료: 해물 토스트 -> 간식
57/113 처리 완료: 명란젓 마요계란밥 -> 한식
58/113 처리 완료: 메밀소바 -> 일식
59/113 처리 완료: 모짜프렌치토스트 -> 간식
60/113 처리 완료: 참치마요 주먹밥 -> 한식

In [14]:
print(len(categories))

60

In [15]:
c = []
for idx, row in recipes[60:90].iterrows():
    cat = categorize_with_ai(row["title"])
    c.append(cat)
    print(f"{idx+1}/{len(recipes)} 처리 완료: {row['title']} -> {cat}")

categories += c
len(categories)

61/113 처리 완료: 상추 주먹밥 -> 한식
62/113 처리 완료: 들기름 막국수
간장비빔메밀국수 -> 한식
63/113 처리 완료: 아보카도 참치마요 덮밥 -> 일식
64/113 처리 완료: 두부 덮밥 -> 일식
65/113 처리 완료: 마요네즈계란밥 -> 한식
66/113 처리 완료: 볶음밥 -> 중식
67/113 처리 완료: 버터비빔밥 -> 한식
68/113 처리 완료: 찹스테이크 -> 양식
69/113 처리 완료: 삼겹살 상추 조림 -> 한식
70/113 처리 완료: 야채 김 계란말이 -> 간식
71/113 처리 완료: 돈까스 샌드위치 -> 양식
72/113 처리 완료: 양배추 만둣국 -> 한식
73/113 처리 완료: 명란,된장 -> 한식
74/113 처리 완료: 참치샐러드 -> 양식
75/113 처리 완료: 카레 주먹밥 -> 일식
76/113 처리 완료: 열무김치국수 -> 한식
77/113 처리 완료: 치즈떡 계란말이 -> 간식
78/113 처리 완료: 비빔국수 -> 한식
79/113 처리 완료: 김치찌개 -> 한식
80/113 처리 완료: 콩나물국 -> 한식
81/113 처리 완료: 간장파스타 -> 양식
82/113 처리 완료: 국물떡볶이 -> 한식
83/113 처리 완료: 계란빵, 꿀빵 -> 간식
84/113 처리 완료: 연어 샐러드 -> 양식
85/113 처리 완료: 소세지야채볶음 -> 양식
86/113 처리 완료: 달걀 볶음밥 -> 양식
87/113 처리 완료: 두부찌개 -> 한식
88/113 처리 완료: 데리야키 닭고기 -> 일식
89/113 처리 완료: 몬테크리스토 시리얼 토스트 -> 간식
90/113 처리 완료: 김밥 -> 간식

90

In [18]:
c = []
for idx, row in recipes[90:113].iterrows():
    cat = categorize_with_ai(row["title"])
    c.append(cat)
    print(f"{idx+1}/{len(recipes)} 처리 완료: {row['title']} -> {cat}")

categories += c
len(categories)

91/113 처리 완료: 카레라이스 -> 양식
92/113 처리 완료: 쇠고기볶음 -> 한식
93/113 처리 완료: 김치부침개피자 -> 한식
94/113 처리 완료: 식빵피자 -> 간식
95/113 처리 완료: 콘치즈 -> 간식
96/113 처리 완료: 김치볶음밥 -> 한식
97/113 처리 완료: 꿀피자 -> 간식
98/113 처리 완료: 계란프라이 -> 간식
99/113 처리 완료: 프렌치 토스트 -> 양식
100/113 처리 완료: 감자 -> 간식
101/113 처리 완료: 계란죽 -> 한식
102/113 처리 완료: 크림우동 -> 일식
103/113 처리 완료: 밥버거 -> 간식
104/113 처리 완료: 스파게티 -> 양식
105/113 처리 완료: 계란찜 -> 한식
106/113 처리 완료: 토스트 -> 간식
107/113 처리 완료: 로제떡볶이 -> 한식
108/113 처리 완료: 꿀빵 -> 간식
109/113 처리 완료: 토스트 -> 간식
110/113 처리 완료: 피자계란밥 -> 한식
111/113 처리 완료: 볶음밥 -> 중식
112/113 처리 완료: 스팸계란밥 -> 한식
113/113 처리 완료: 계란찜 -> 한식

113

In [ ]:
# c = []
# for idx, row in recipes[120:150].iterrows():
#     cat = categorize_with_ai(row["title"])
#     c.append(cat)
#     print(f"{idx+1}/{len(recipes)} 처리 완료: {row['title']} -> {cat}")

# categories += c
# len(categories)

121/246 처리 완료: 오레오 치즈케이크 -> 간식
122/246 처리 완료: 스팸 맛탕 -> 간식
123/246 처리 완료: 카레주먹밥 -> 간식
124/246 처리 완료: 부타동 -> 일식
125/246 처리 완료: 토마토부르스케타 -> 양식
126/246 처리 완료: 장떡만둣국 -> 한식
127/246 처리 완료: 식빵팝콘 -> 간식
128/246 처리 완료: 통마늘표고버섯볶음 -> 한식
129/246 처리 완료: 고구마에그슬럿 -> 간식
130/246 처리 완료: 고구마채전 -> 간식
131/246 처리 완료: 바치 디 다마 -> 중식
132/246 처리 완료: 파프리카 피자 -> 양식
133/246 처리 완료: 허니윙 -> 간식
134/246 처리 완료: 감자전 -> 한식
135/246 처리 완료: 토스트 -> 간식
136/246 처리 완료: 야채샐러드빵 -> 간식
137/246 처리 완료: 무침만두 -> 한식
138/246 처리 완료: 떡볶음 -> 한식
139/246 처리 완료: 버섯볶음두부면 -> 한식
140/246 처리 완료: 카페모카쿠키슈 -> 간식
141/246 처리 완료: 양파덮밥 -> 일식
142/246 처리 완료: 컵케이크 -> 간식
143/246 처리 완료: 오이들깨무침 -> 한식
144/246 처리 완료: 물비빔국수 -> 한식
145/246 처리 완료: 불참치장 -> 일식
146/246 처리 완료: 치즈 공구마 -> 간식
147/246 처리 완료: 모카 케이크 -> 간식
148/246 처리 완료: 숙주볶음 -> 중식
149/246 처리 완료: 치즈 쿠키 -> 간식
150/246 처리 완료: 초코 비스코티 -> 간식

150

In [ ]:
# c = []
# for idx, row in recipes[150:180].iterrows():
#     cat = categorize_with_ai(row["title"])
#     c.append(cat)
#     print(f"{idx+1}/{len(recipes)} 처리 완료: {row['title']} -> {cat}")

# categories += c
# len(categories)

151/246 처리 완료: 고추장황태채볶음 -> 한식
152/246 처리 완료: 된장삼겹살덮밥 -> 한식
153/246 처리 완료: 오징어말이 -> 일식
154/246 처리 완료: 애호박 새우마요 볶음 -> 한식
155/246 처리 완료: 돼지갈비 -> 한식
156/246 처리 완료: 두부스테이크 -> 양식
157/246 처리 완료: 두부 마요네즈 -> 한식
158/246 처리 완료: 크림 새송이 -> 양식
159/246 처리 완료: 오이롤초밥 -> 일식
160/246 처리 완료: 콘치즈 고로케 -> 간식
161/246 처리 완료: 표고버섯 덮밥 -> 일식
162/246 처리 완료: 가지탕수 -> 중식
163/246 처리 완료: 그라탱 -> 양식
164/246 처리 완료: 우유달걀카레 -> 간식
165/246 처리 완료: 오일파스타 -> 양식
166/246 처리 완료: 황태채 버터구이 -> 한식
167/246 처리 완료: 대패대파구이 -> 한식
168/246 처리 완료: 베이컨치즈밥말이 -> 양식
169/246 처리 완료: 양파튀김 -> 간식
170/246 처리 완료: 사과 케이크 -> 간식
171/246 처리 완료: 새송이 -> 한식
172/246 처리 완료: 파프리카된장무침 -> 한식
173/246 처리 완료: 닭마볶음밥 -> 중식
174/246 처리 완료: 우삼겹 덮밥 규동 -> 일식
175/246 처리 완료: 가지 라자냐 -> 양식
176/246 처리 완료: 닭죽 -> 한식
177/246 처리 완료: 참치 파스타, 두부면 파스타 -> 양식
178/246 처리 완료: 떡감자 -> 간식
179/246 처리 완료: 느타리두루치기 -> 한식
180/246 처리 완료: 오이무침 -> 한식

180

In [ ]:
# c = []
# for idx, row in recipes[180:210].iterrows():
#     cat = categorize_with_ai(row["title"])
#     c.append(cat)
#     print(f"{idx+1}/{len(recipes)} 처리 완료: {row['title']} -> {cat}")

# categories += c
# len(categories)

181/246 처리 완료: 콩나물무침 -> 한식
182/246 처리 완료: 간장두부장 -> 중식
183/246 처리 완료: 돈까스 김치나베 -> 일식
184/246 처리 완료: 얼큰만둣국 -> 한식
185/246 처리 완료: 시금치 플랫브레드 피자 -> 양식
186/246 처리 완료: 마늘빵
마늘빵
마늘빵
식빵 -> 양식
187/246 처리 완료: 돼지불백 -> 한식
188/246 처리 완료: 녹차머핀 -> 간식
189/246 처리 완료: 참치맛나니 -> 일식
190/246 처리 완료: 프리타타 -> 양식
191/246 처리 완료: 아망디오 쇼콜라 -> 간식
192/246 처리 완료: 할로윈 브라우니 쿠키 -> 간식
193/246 처리 완료: 연어 파피요트 -> 양식
194/246 처리 완료: 새송이버섯 고추장구이 -> 한식
195/246 처리 완료: 뢰스티 -> 간식
196/246 처리 완료: 츄러스 -> 간식
197/246 처리 완료: 어묵비빔국수 -> 간식
198/246 처리 완료: 김치마요우동 -> 일식
199/246 처리 완료: 하트파이 팔미에 -> 간식
200/246 처리 완료: 달걀떡볶이 -> 한식
201/246 처리 완료: 소고기볶음 -> 한식
202/246 처리 완료: 양파햄치즈빵 -> 간식
203/246 처리 완료: 게살버거 -> 양식
204/246 처리 완료: 크랜베리 화이트 초코 쿠키 -> 간식
205/246 처리 완료: 모카 컵케이크 -> 간식
206/246 처리 완료: 어향치킨 -> 중식
207/246 처리 완료: 체리클라푸티 -> 간식
208/246 처리 완료: 순두부 계란 -> 한식
209/246 처리 완료: 투움바파스타 -> 양식
210/246 처리 완료: 오레오 크림치즈 머핀 -> 간식

210

In [ ]:
# c = []
# for idx, row in recipes[210:246].iterrows():
#     cat = categorize_with_ai(row["title"])
#     c.append(cat)
#     print(f"{idx+1}/{len(recipes)} 처리 완료: {row['title']} -> {cat}")

# categories += c
# len(categories)

211/246 처리 완료: 버터구이 진미채 -> 간식
212/246 처리 완료: 함양파 링전 -> 한식
213/246 처리 완료: 스팸아보카도덮밥 -> 일식
214/246 처리 완료: 고추참치비빔우동 -> 일식
215/246 처리 완료: 면두부 크림파스타 -> 양식
216/246 처리 완료: 스팸마요 덮밥 -> 일식
217/246 처리 완료: 사과 크렘블 파이 -> 간식
218/246 처리 완료: 스카레 -> 아라비아
219/246 처리 완료: 어묵노미야끼 -> 기타
220/246 처리 완료: 콘치즈 -> 간식
221/246 처리 완료: 식빵 러스크 (에어프라이어) -> 간식
222/246 처리 완료: 소고기쪽파말이 -> 한식
223/246 처리 완료: 딸기잼 쿠키
과일잼 쿠키 -> 간식
224/246 처리 완료: 계란탕 -> 한식
225/246 처리 완료: 오징어볶음 -> 한식
226/246 처리 완료: 시나몬 롤 쿠키 -> 간식
227/246 처리 완료: 가지덮밥 -> 일식
228/246 처리 완료: 시래기지짐 -> 한식
229/246 처리 완료: 파마산 치즈 쿠키 -> 간식
230/246 처리 완료: 소시지강정 -> 간식
231/246 처리 완료: 식빵팝콘 -> 간식
232/246 처리 완료: 베이컨말이 -> 간식
233/246 처리 완료: 퍼지 브라우니 -> 간식
234/246 처리 완료: 대파토스트 -> 간식
235/246 처리 완료: 소시지콩나물찜 -> 한식
236/246 처리 완료: 아보카도 베이컨구이 -> 양식
237/246 처리 완료: 고구마조림 -> 간식
238/246 처리 완료: 주먹밥 -> 한식
239/246 처리 완료: 양배추어묵볶음 -> 한식
240/246 처리 완료: 구운 참치 주먹밥 -> 일식
241/246 처리 완료: 퐁크러쉬 쉐이크 -> 간식
242/246 처리 완료: 소시지 배추 롤 -> 간식
243/246 처리 완료: 돼지불백 -> 한식
244/246 처리 완료: 등갈비 -> 한식
245/246 처리 완료: 초코칩쿠키 -> 간식
246/246 처리 완료: 커피콩 쿠키 -> 간식

246

In [19]:
len(categories)

113

In [22]:
recipes1 = recipes
recipes1.drop(columns=["Unnamed: 0", "Unnamed: 0.1"], inplace=True, errors='ignore')
recipes1.head(1)

,url,title,description,servings,time,difficulty,materials,tools,steps,final_images,tips,danger
0,https://www.10000recipe.com/recipe/6953727,떡꼬치,떡꼬치를 너무 좋아하는데 요즘 파는곳이 별로 없어서\n간단하게 집에서 한번 만들어봤...,2인분,15분 이내,초급,"가래떡 7개, 기름 조금, 케찹 3큰술, 진간장 1/2큰술, 고추장 1큰술, 올리고...",에어프라이어,[{'text': '떡에 기름을 골고루 조금씩 묻혀 에어프라이어에 돌려줍니다\n18...,[],"저는 이마트에서 2,000원짜리 떡 한팩을 사와서 냉동에 넣지않고 바로 뒷날 해먹었...",0

In [23]:
recipes

,url,title,description,servings,time,difficulty,materials,tools,steps,final_images,tips,danger
0,https://www.10000recipe.com/recipe/6953727,떡꼬치,떡꼬치를 너무 좋아하는데 요즘 파는곳이 별로 없어서\n간단하게 집에서 한번 만들어봤...,2인분,15분 이내,초급,"가래떡 7개, 기름 조금, 케찹 3큰술, 진간장 1/2큰술, 고추장 1큰술, 올리고...",에어프라이어,[{'text': '떡에 기름을 골고루 조금씩 묻혀 에어프라이어에 돌려줍니다\n18...,[],"저는 이마트에서 2,000원짜리 떡 한팩을 사와서 냉동에 넣지않고 바로 뒷날 해먹었...",0
1,https://www.10000recipe.com/recipe/6928779,계란빵 꿀빵,계란빵도 먹고 꿀빵도 먹고 즐거운 간식 타임에 모양틀을 이용해 아이와 함께 또는 혼...,2인분,15분 이내,초급,"빵 4장, 달걀 2개, 슬라이스 치즈 2장, 소금 톡톡, 꿀 듬뿍","오븐, 숟가락","[{'text': '1 계란빵 만들기\n빵에 구멍을 냅니다', 'images': [...",['https://recipe1.ezmember.co.kr/cache/recipe/...,큼직한 식빵에 만들면 더 쉬워요,0
2,https://www.10000recipe.com/recipe/6728751,고구마 빵,"초간단 노오븐 베이킹. 노버터, 노밀가루라 아기에게 딱!! 건강한 간식이예요",2인분,30분 이내,초급,"고구마 2개, 계란 흰자 2개, 올리브오일 약간","오븐, 숟가락",[{'text': '고구마는 껍질을 까고 쪄낸 후 뜨거울때 으깨주세요. 고구마가 달...,['https://recipe1.ezmember.co.kr/cache/recipe/...,NaN,0
3,https://www.10000recipe.com/recipe/6881646,"코울슬로, 사라다빵",새콤달콤한 양배추 샐러드 '코울슬로'와\n모닝빵 대신 통식빵을 이용한 '사라다빵'을...,6인분 이상,30분 이내,초급,"양배추 350g, 사과 1/2개, 캔옥수수 100g, 마요네즈 5큰술, 레몬즙 3큰...","오븐, 숟가락","[{'text': '분량의 마요네즈, 레몬즙, 연유, 천일염을 잘 섞고 통후추도 갈...",['https://recipe1.ezmember.co.kr/cache/recipe/...,서너시간 지나 맛을 보고 좀 더 새콤달콤한 맛을 원한다면 레몬즙과 연유를 입맛에 맞...,0
4,https://www.10000recipe.com/recipe/6880305,또띠아 피자,달걀지단이 들어간\n사과 또띠아 피자!,2인분,15분 이내,초급,"사과 1/4개, 사과잼 3T, 또띠아 1개, 미트스파게티소스 3T, 달걀 1개, 견...","전자레인지,에어프라이어",[{'text': '* 재료 준비\n또띠아 1개\n사과 1/4개\n사과잼 3T\n미...,['https://recipe1.ezmember.co.kr/cache/recipe/...,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...
108,https://youtu.be/nKZ_bKiDeVY?list=TLGGgpMG1C4C...,토스트,NaN,NaN,NaN,NaN,"식빵, 달걀, 샌드위치 햄, 설탕, 케첩, 마요네즈","숟가락, 전자레인지",NaN,NaN,NaN,0
109,https://youtu.be/Z2vjsJZnXog?list=TLGGk0UrLaeB...,피자계란밥,NaN,NaN,NaN,NaN,"밥 100g, 계란 1알, 케첩, 모짜렐라 치즈","숟가락, 전자레인지",NaN,NaN,NaN,0
110,https://youtu.be/YQZn6dQV0xg?list=TLGGSlnnq6am...,볶음밥,NaN,NaN,NaN,NaN,"즉석밥 1개, 계란 2알, 스팸, 김치","숟가락, 가위, 전자레인지, 깊은 그릇(유리, 사기)","1. 재료 준비\n- 즉석밥 1개, 계란 2알, 스팸, 김치\n2. 조리도구준비\n...",NaN,NaN,0
111,https://youtu.be/e9VVSZei8hU?list=TLGGLCgQyHYh...,스팸계란밥,NaN,NaN,NaN,NaN,"계란 2알, 즉석밥 1개, 스팸, 파, 소금, 간장","깊은 그릇, 전자레인지, 비닐랩",NaN,NaN,NaN,0
112,https://youtu.be/j1JVxiuNSuU?list=TLGGfkA0RV52...,계란찜,NaN,NaN,NaN,NaN,"계란 1알, 우유 200ml, 카레가루, 파, 즉석밥 1","숫가락, 전자레인지, 가위",NaN,NaN,NaN,0

In [24]:
recipes["category"] = categories
recipes.head(1)

,url,title,description,servings,time,difficulty,materials,tools,steps,final_images,tips,danger,category
0,https://www.10000recipe.com/recipe/6953727,떡꼬치,떡꼬치를 너무 좋아하는데 요즘 파는곳이 별로 없어서\n간단하게 집에서 한번 만들어봤...,2인분,15분 이내,초급,"가래떡 7개, 기름 조금, 케찹 3큰술, 진간장 1/2큰술, 고추장 1큰술, 올리고...",에어프라이어,[{'text': '떡에 기름을 골고루 조금씩 묻혀 에어프라이어에 돌려줍니다\n18...,[],"저는 이마트에서 2,000원짜리 떡 한팩을 사와서 냉동에 넣지않고 바로 뒷날 해먹었...",0,간식

In [25]:
recipes.to_csv("recipes_with_categories.csv", index=False)

## 시간, 인분 int화

In [1]:
import pandas as pd

In [26]:
recipes = pd.read_csv('recipes_with_categories.csv')

In [48]:
# 널 제거
len(recipes.dropna(subset=["title", "servings", "time", "difficulty", "materials", "tools", "steps", "danger", "category"]))
# null인 행 개수
# len(recipes[recipes["difficulty"].isnull()])

87

In [49]:
recipes.dropna(subset=["title", "servings", "time", "difficulty", "materials", "tools", "steps", "danger", "category"], inplace=True)

In [50]:
# 허용 값 리스트
allowed_values = ['초급', '아무나', '중급', '고급']
# 조건 필터
recipes = recipes[recipes['difficulty'].isin(allowed_values)]


# '인분'으로 끝나는 행만 유지
recipes = recipes[recipes['servings'].str.endswith('인분', na=False)]
# '인분' 글자 제거
recipes['servings'] = recipes['servings'].str.replace('인분', '', regex=False)


# '분 이내'으로 끝나는 행만 유지
recipes = recipes[recipes['time'].str.endswith('분 이내', na=False)]
# '분 이내' 글자 제거
recipes['time'] = recipes['time'].str.replace('분 이내', '', regex=False)

recipes.head(3)

,url,title,description,servings,time,difficulty,materials,tools,steps,final_images,tips,danger,category
0,https://www.10000recipe.com/recipe/6953727,떡꼬치,떡꼬치를 너무 좋아하는데 요즘 파는곳이 별로 없어서\n간단하게 집에서 한번 만들어봤...,2,15,초급,"가래떡 7개, 기름 조금, 케찹 3큰술, 진간장 1/2큰술, 고추장 1큰술, 올리고...",에어프라이어,[{'text': '떡에 기름을 골고루 조금씩 묻혀 에어프라이어에 돌려줍니다\n18...,[],"저는 이마트에서 2,000원짜리 떡 한팩을 사와서 냉동에 넣지않고 바로 뒷날 해먹었...",0,간식
1,https://www.10000recipe.com/recipe/6928779,계란빵 꿀빵,계란빵도 먹고 꿀빵도 먹고 즐거운 간식 타임에 모양틀을 이용해 아이와 함께 또는 혼...,2,15,초급,"빵 4장, 달걀 2개, 슬라이스 치즈 2장, 소금 톡톡, 꿀 듬뿍","오븐, 숟가락","[{'text': '1 계란빵 만들기\n빵에 구멍을 냅니다', 'images': [...",['https://recipe1.ezmember.co.kr/cache/recipe/...,큼직한 식빵에 만들면 더 쉬워요,0,간식
2,https://www.10000recipe.com/recipe/6728751,고구마 빵,"초간단 노오븐 베이킹. 노버터, 노밀가루라 아기에게 딱!! 건강한 간식이예요",2,30,초급,"고구마 2개, 계란 흰자 2개, 올리브오일 약간","오븐, 숟가락",[{'text': '고구마는 껍질을 까고 쪄낸 후 뜨거울때 으깨주세요. 고구마가 달...,['https://recipe1.ezmember.co.kr/cache/recipe/...,NaN,0,간식

In [51]:
recipes.to_csv("recipes.csv", index=False)

In [52]:
recipes['tools'].unique()

array(['에어프라이어', '오븐, 숟가락', '전자레인지,에어프라이어', '칼, 도마, 불', '칼, 도마, 숟가락',
       '칼, 도마', '불, 찜기, 숟가락', '칼, 도마, 볼, 숟가락', '칼, 도마, 불, 오븐, 볼, 숟가락',
       '칼, 도마, 불, 숟가락', '불, 볼', '칼, 도마, 불, 볼, 숟가락', '불, 에어프라이어, 숟가락',
       '오븐, 에어프라이어, 숟가락', '불, 오븐, 숟가락', '불', '불, 숟가락', '불, 에어프라이어',
       '불, 볼, 숟가락', '칼, 도마, 불, 불, 볼, 숟가락', '칼, 도마, 불, 불, 숟가락',
       '칼, 도마, 오븐, 숟가락', '칼, 도마, 오븐, 볼, 숟가락', '칼, 도마, 불, 오븐, 숟가락',
       '칼, 도마, 볼', '칼, 불'], dtype=object)

## 도구 있는 레시피만 필터링

In [2]:
import pandas as pd

In [116]:
recipes = pd.read_csv('recipes_processed_tools.csv')
recipes = recipes.dropna(subset=['title', 'tools', 'materials'])
recipes

,url,title,description,servings,time,difficulty,materials,tools,steps,final_images,tips,danger,category
0,https://www.10000recipe.com/recipe/6953727,떡꼬치,떡꼬치를 너무 좋아하는데 요즘 파는곳이 별로 없어서\n간단하게 집에서 한번 만들어봤...,2,15,초급,"가래떡 7개, 기름 조금, 케찹 3큰술, 진간장 1/2큰술, 고추장 1큰술, 올리고...","에어프라이어, 프라이팬, 그릇",[{'text': '떡에 기름을 골고루 조금씩 묻혀 에어프라이어에 돌려줍니다\n18...,[],"저는 이마트에서 2,000원짜리 떡 한팩을 사와서 냉동에 넣지않고 바로 뒷날 해먹었...",0,간식
1,https://www.10000recipe.com/recipe/6928779,계란빵 꿀빵,계란빵도 먹고 꿀빵도 먹고 즐거운 간식 타임에 모양틀을 이용해 아이와 함께 또는 혼...,2,15,초급,"빵 4장, 달걀 2개, 슬라이스 치즈 2장, 소금 톡톡, 꿀 듬뿍","프라이팬, 주걱, 뒤집개, 계량도구","[{'text': '1 계란빵 만들기\n빵에 구멍을 냅니다', 'images': [...",['https://recipe1.ezmember.co.kr/cache/recipe/...,큼직한 식빵에 만들면 더 쉬워요,0,간식
2,https://www.10000recipe.com/recipe/6728751,고구마 빵,"초간단 노오븐 베이킹. 노버터, 노밀가루라 아기에게 딱!! 건강한 간식이예요",2,30,초급,"고구마 2개, 계란 흰자 2개, 올리브오일 약간","계량도구, 필러, 그릇, 주걱, 도마, 전자레인지",[{'text': '고구마는 껍질을 까고 쪄낸 후 뜨거울때 으깨주세요. 고구마가 달...,['https://recipe1.ezmember.co.kr/cache/recipe/...,NaN,0,간식
3,https://www.10000recipe.com/recipe/6880305,또띠아 피자,달걀지단이 들어간\n사과 또띠아 피자!,2,15,초급,"사과 1/4개, 사과잼 3T, 또띠아 1개, 미트스파게티소스 3T, 달걀 1개, 견...","그릇, 프라이팬, 도마, 칼, 전자레인지, 가위",[{'text': '* 재료 준비\n또띠아 1개\n사과 1/4개\n사과잼 3T\n미...,['https://recipe1.ezmember.co.kr/cache/recipe/...,NaN,0,간식
4,https://www.10000recipe.com/recipe/6966633,스파게티 샌드위치,"에미넴이 디트로이트에 오픈한 맘스 스파게티 식당에서 파는 ""스파게티 샌드위치"" 궁금...",1,20,아무나,"버터 20g, 다진마늘 1T, 설탕 1t, 파슬리가루 적당량, 토마토스파게티소스 적...","계량도구, 그릇, 전자레인지, 프라이팬",[{'text': '토마토 시판소스를 이용하여 빠르게 토마토스파게티를 만든다 (저는...,['https://recipe1.ezmember.co.kr/cache/recipe/...,마늘빵 사이에 끼워먹는 토마토스파게티\n탄수화물 역시 맛있어\n유투브 구독해줭......,1,양식
...,...,...,...,...,...,...,...,...,...,...,...,...,...
81,https://www.10000recipe.com/recipe/6952453,몬테크리스토 시리얼 토스트,누구나 가지고 있는 재료들로\n정말 맛있는 토스트를 만들어봤습니다.\n겉바속촉 토스...,1,20,초급,"식빵 3장, 통조림햄 4장, 슬라이스 치즈 2장, 계란 1개, 설탕 1큰술, 소금 ...","도마, 가위, 프라이팬","[{'text': '식빵 3장을 도마 위에 펼쳐 놓은 뒤\n한쪽 면에는 땅콩버터, ...",[],자세한 조리방법은 유튜브 영상으로 확인하실 수 있습니다.\n구독 & 좋아요 부탁드려요.,1,간식
82,https://www.10000recipe.com/recipe/6966278,김밥,당근밥으로 만드는 다이어트 김밥,3,20,초급,"밥 2공기, 매실액 1T, 김밥김 5장, 당근 2개, 소금 , 현미유 , 달걀 3개...","칼로,주방용 계량도구,도마,프라이팬,주걱",[{'text': '오이는 길쯕하게 썬다.\n오이씨는 물기가 많으니 잘라내버리세요....,['https://recipe1.ezmember.co.kr/cache/recipe/...,NaN,1,간식
83,https://www.10000recipe.com/recipe/6735763,카레라이스,얼마전 일본에서 사왔던 카레로 급 만들어본 일본식 카레라이스~ 물론 카레안에도 고기...,5,30,초급,"카레일본고형카레 고형카레의1/2개 100g, 물 700ml, 감자 2개, 당근 1개...","칼, 냄비, 주걱, 프라이팬","[{'text': '재료들은 먹기좋게 썰어 준비하세요.', 'images': ['h...",['https://recipe1.ezmember.co.kr/cache/recipe/...,NaN,1,양식
84,https://www.10000recipe.com/recipe/6881857,쇠고기볶음,아이들이 좋아하는 꼬기~~ 그냥 구워서도 맛있는데 향긋한 미나리 넣어서 볶았더니 향...,2,30,초급,"등심 500g, 미나리 1/2줌, 미니새송이 100g, 통마늘 10개, 청양고추 2...","계량도구, 칼, 도마, 프라이팬, 주걱","[{'text': '청주 2큰술로 샤워시켜 준 후, 후추와 바질가루 뿌려서 잠깐 재...",[],성장기 어린이들이나 보양식으로 좋은 소고기는 단백질이 풍부해서 입맛 잃기 쉬운 요즘...,1,한식
85,https://www.10000recipe.com/recipe/6881967,김치부침개피자,김치부침개 모두들 좋아하시지요~~~\n\n피자도 좋아하시지요~~~\n\n부침개와 피...,2,30,초급,"김치 1컵, 밀가루부침가루 2/3컵, 우유생수 1/2~2/3컵, 피자치즈 150g,...","계량도구, 칼, 도마, 프라이팬, 국자",[{'text': '페파로니 대신 베이컨을 사용하셔도 됩니다~!~\n냉장고에 있는 ...,['https://recipe1.ezmember.co.kr/cache/recipe/...,NaN,1,한식

In [117]:
recipes.shape

(86, 13)

In [104]:
recipes_tools = (
    recipes.assign(tools=lambda df: df['tools'].str.split(','))
          .explode('tools')
          .assign(tools=lambda df: df['tools'].str.strip())
          .reset_index(drop=True)[['title', 'tools']]
)
recipes_tools[['title', 'tools']]

       title   tools
0        떡꼬치  에어프라이어
1        떡꼬치    프라이팬
2        떡꼬치      그릇
3     계란빵 꿀빵    프라이팬
4     계란빵 꿀빵      주걱
..       ...     ...
365  김치부침개피자    계량도구
366  김치부침개피자       칼
367  김치부침개피자      도마
368  김치부침개피자    프라이팬
369  김치부침개피자      국자

[370 rows x 2 columns]

In [105]:
recipes_tools['tools'].unique()

array(['에어프라이어', '프라이팬', '그릇', '주걱', '뒤집개', '계량도구', '필러', '도마', '전자레인지',
       '칼', '가위', '국자', '체/거름망', '냄비', '에그슬라이서', '소스팬', '도구 없음', '체인/거름망',
       '계란 프라이를 기준으로 프라이팬', '칼이 필요합니다.', '팬', '집게', '오븐', '냉장고', '칼로',
       '주방용 계량도구'], dtype=object)

In [108]:
# recipes_tools["tools"] = recipes_tools["tools"].str.replace("계란 프라이를 기준으로 프라이팬", "프라이팬")
# recipes_tools["tools"] = recipes_tools["tools"].str.replace("칼이 필요합니다.", "칼")
# recipes_tools["tools"] = recipes_tools["tools"].str.replace("소스팬", "프라이팬")
# recipes_tools["tools"] = recipes_tools["tools"].str.replace("체인/거름망", "체/거름망")
# recipes_tools["tools"] = recipes_tools["tools"].str.replace("칼로", "칼")
# recipes_tools["tools"] = recipes_tools["tools"].str.replace("주방용 계량도구", "계량도구")
# # 에그슬라이서 행 삭제
# recipes_tools = recipes_tools[recipes_tools["tools"] != "에그슬라이서"]
# recipes_tools = recipes_tools[recipes_tools["tools"] != "도구 없음"]
# recipes_tools = recipes_tools[recipes_tools["tools"] != "냉장고"]

# 팬이라고 적힌 행을 프라이팬으로 변경
recipes_tools.loc[recipes_tools['tools'] == '팬', 'tools'] = '프라이팬'

recipes_tools['tools'].unique()

array(['에어프라이어', '프라이팬', '그릇', '주걱', '뒤집개', '계량도구', '필러', '도마', '전자레인지',
       '칼', '가위', '국자', '체/거름망', '냄비', '집게', '오븐'], dtype=object)

In [109]:
recipes_tools.to_csv('recipes_tools.csv', index=False)

In [110]:
recipes_tools.head(1)

  title   tools
0   떡꼬치  에어프라이어

## 재료 분리

In [ ]:
import pandas as pd

In [213]:
recipes = pd.read_csv('recipes_processed_tools.csv')
recipes = recipes.dropna(subset=['title', 'tools', 'materials'])
recipes

,url,title,description,servings,time,difficulty,materials,tools,steps,final_images,tips,danger,category
0,https://www.10000recipe.com/recipe/6953727,떡꼬치,떡꼬치를 너무 좋아하는데 요즘 파는곳이 별로 없어서\n간단하게 집에서 한번 만들어봤...,2,15,초급,"가래떡 7개, 식용유 1약간, 케찹 3큰술, 진간장 1/2큰술, 고추장 1큰술, 올...","에어프라이어, 프라이팬, 그릇",[{'text': '떡에 기름을 골고루 조금씩 묻혀 에어프라이어에 돌려줍니다\n18...,[],"저는 이마트에서 2,000원짜리 떡 한팩을 사와서 냉동에 넣지않고 바로 뒷날 해먹었...",0,간식
1,https://www.10000recipe.com/recipe/6928779,계란빵 꿀빵,계란빵도 먹고 꿀빵도 먹고 즐거운 간식 타임에 모양틀을 이용해 아이와 함께 또는 혼...,2,15,초급,"식빵 4장, 계란 2개, 슬라이스치즈 2장, 소금 1약간, 꿀 1적당량","프라이팬, 주걱, 뒤집개, 계량도구","[{'text': '1 계란빵 만들기\n빵에 구멍을 냅니다', 'images': [...",['https://recipe1.ezmember.co.kr/cache/recipe/...,큼직한 식빵에 만들면 더 쉬워요,0,간식
2,https://www.10000recipe.com/recipe/6728751,고구마 빵,"초간단 노오븐 베이킹. 노버터, 노밀가루라 아기에게 딱!! 건강한 간식이예요",2,30,초급,"고구마 2개, 계란 2개, 올리브유 1약간","계량도구, 필러, 그릇, 주걱, 도마, 전자레인지",[{'text': '고구마는 껍질을 까고 쪄낸 후 뜨거울때 으깨주세요. 고구마가 달...,['https://recipe1.ezmember.co.kr/cache/recipe/...,NaN,0,간식
3,https://www.10000recipe.com/recipe/6880305,또띠아 피자,달걀지단이 들어간\n사과 또띠아 피자!,2,15,초급,"사과 1/4개, 사과잼 3T, 또띠아 1개, 미트소스 3T, 계란 1개, 견과류가루...","그릇, 프라이팬, 도마, 칼, 전자레인지, 가위",[{'text': '* 재료 준비\n또띠아 1개\n사과 1/4개\n사과잼 3T\n미...,['https://recipe1.ezmember.co.kr/cache/recipe/...,NaN,0,간식
4,https://www.10000recipe.com/recipe/6966633,스파게티 샌드위치,"에미넴이 디트로이트에 오픈한 맘스 스파게티 식당에서 파는 ""스파게티 샌드위치"" 궁금...",1,20,아무나,"버터 20g, 다진마늘 1T, 설탕 1t, 파슬리가루 1적당량, 토마토소스 1적당량...","계량도구, 그릇, 전자레인지, 프라이팬",[{'text': '토마토 시판소스를 이용하여 빠르게 토마토스파게티를 만든다 (저는...,['https://recipe1.ezmember.co.kr/cache/recipe/...,마늘빵 사이에 끼워먹는 토마토스파게티\n탄수화물 역시 맛있어\n유투브 구독해줭......,1,양식
...,...,...,...,...,...,...,...,...,...,...,...,...,...
81,https://www.10000recipe.com/recipe/6952453,몬테크리스토 시리얼 토스트,누구나 가지고 있는 재료들로\n정말 맛있는 토스트를 만들어봤습니다.\n겉바속촉 토스...,1,20,초급,"식빵 3장, 슬라이스햄 4장, 슬라이스치즈 2장, 계란 1개, 설탕 1큰술, 소금 ...","도마, 가위, 프라이팬","[{'text': '식빵 3장을 도마 위에 펼쳐 놓은 뒤\n한쪽 면에는 땅콩버터, ...",[],자세한 조리방법은 유튜브 영상으로 확인하실 수 있습니다.\n구독 & 좋아요 부탁드려요.,1,간식
82,https://www.10000recipe.com/recipe/6966278,김밥,당근밥으로 만드는 다이어트 김밥,3,20,초급,"밥 2공기, 매실액 1T, 김밥김 5장, 당근 2개, 소금 , 식용유 , 계란 3개...","칼로,주방용 계량도구,도마,프라이팬,주걱",[{'text': '오이는 길쯕하게 썬다.\n오이씨는 물기가 많으니 잘라내버리세요....,['https://recipe1.ezmember.co.kr/cache/recipe/...,NaN,1,간식
83,https://www.10000recipe.com/recipe/6735763,카레라이스,얼마전 일본에서 사왔던 카레로 급 만들어본 일본식 카레라이스~ 물론 카레안에도 고기...,5,30,초급,"고형카레 100g, 물 700ml, 감자 2개, 당근 1개, 양파 1개, 돼지고기 ...","칼, 냄비, 주걱, 프라이팬","[{'text': '재료들은 먹기좋게 썰어 준비하세요.', 'images': ['h...",['https://recipe1.ezmember.co.kr/cache/recipe/...,NaN,1,양식
84,https://www.10000recipe.com/recipe/6881857,쇠고기볶음,아이들이 좋아하는 꼬기~~ 그냥 구워서도 맛있는데 향긋한 미나리 넣어서 볶았더니 향...,2,30,초급,"등심 500g, 미나리 1/2줌, 새송이버섯 100g, 마늘 10개, 청양고추 2개...","계량도구, 칼, 도마, 프라이팬, 주걱","[{'text': '청주 2큰술로 샤워시켜 준 후, 후추와 바질가루 뿌려서 잠깐 재...",[],성장기 어린이들이나 보양식으로 좋은 소고기는 단백질이 풍부해서 입맛 잃기 쉬운 요즘...,1,한식
85,https://www.10000recipe.com/recipe/6881967,김치부침개피자,김치부침개 모두들 좋아하시지요~~~\n\n피자도 좋아하시지요~~~\n\n부침개와 피...,2,30,초급,"김치 1컵, 밀가루 2/3컵, 우유 1/2컵, 모짜렐라 피자치즈 150g, 방울토마...","계량도구, 칼, 도마, 프라이팬, 국자",[{'text': '페파로니 대신 베이컨을 사용하셔도 됩니다~!~\n냉장고에 있는 ...,['https://recipe1.ezmember.co.kr/cache/recipe/...,NaN,1,한식

In [214]:
len(recipes)

86

In [ ]:
# recipes['materials'].to_csv("ingredients.csv", index=False)

In [215]:
ing = pd.read_csv("ingredients.csv", names=["ingredients"])
ing = ing[1:]
ing

                                          ingredients
1   가래떡 7개, 식용유 1약간, 케찹 3큰술, 진간장 1/2큰술, 고추장 1큰술, 올...
2             식빵 4장, 계란 2개, 슬라이스치즈 2장, 소금 1약간, 꿀 1적당량
3                             고구마 2개, 계란 2개, 올리브유 1약간
4   사과 1/4개, 사과잼 3T, 또띠아 1개, 미트소스 3T, 계란 1개, 견과류가루...
5   버터 20g, 다진마늘 1T, 설탕 1t, 파슬리가루 1적당량, 토마토소스 1적당량...
..                                                ...
82  식빵 3장, 슬라이스햄 4장, 슬라이스치즈 2장, 계란 1개, 설탕 1큰술, 소금 ...
83  밥 2공기, 매실액 1T, 김밥김 5장, 당근 2개, 소금 , 식용유 , 계란 3개...
84  고형카레 100g, 물 700ml, 감자 2개, 당근 1개, 양파 1개, 돼지고기 ...
85  등심 500g, 미나리 1/2줌, 새송이버섯 100g, 마늘 10개, 청양고추 2개...
86  김치 1컵, 밀가루 2/3컵, 우유 1/2컵, 모짜렐라 피자치즈 150g, 방울토마...

[86 rows x 1 columns]

In [216]:
recipes["materials"] = ing.values.flatten()
recipes

,url,title,description,servings,time,difficulty,materials,tools,steps,final_images,tips,danger,category
0,https://www.10000recipe.com/recipe/6953727,떡꼬치,떡꼬치를 너무 좋아하는데 요즘 파는곳이 별로 없어서\n간단하게 집에서 한번 만들어봤...,2,15,초급,"가래떡 7개, 식용유 1약간, 케찹 3큰술, 진간장 1/2큰술, 고추장 1큰술, 올...","에어프라이어, 프라이팬, 그릇",[{'text': '떡에 기름을 골고루 조금씩 묻혀 에어프라이어에 돌려줍니다\n18...,[],"저는 이마트에서 2,000원짜리 떡 한팩을 사와서 냉동에 넣지않고 바로 뒷날 해먹었...",0,간식
1,https://www.10000recipe.com/recipe/6928779,계란빵 꿀빵,계란빵도 먹고 꿀빵도 먹고 즐거운 간식 타임에 모양틀을 이용해 아이와 함께 또는 혼...,2,15,초급,"식빵 4장, 계란 2개, 슬라이스치즈 2장, 소금 1약간, 꿀 1적당량","프라이팬, 주걱, 뒤집개, 계량도구","[{'text': '1 계란빵 만들기\n빵에 구멍을 냅니다', 'images': [...",['https://recipe1.ezmember.co.kr/cache/recipe/...,큼직한 식빵에 만들면 더 쉬워요,0,간식
2,https://www.10000recipe.com/recipe/6728751,고구마 빵,"초간단 노오븐 베이킹. 노버터, 노밀가루라 아기에게 딱!! 건강한 간식이예요",2,30,초급,"고구마 2개, 계란 2개, 올리브유 1약간","계량도구, 필러, 그릇, 주걱, 도마, 전자레인지",[{'text': '고구마는 껍질을 까고 쪄낸 후 뜨거울때 으깨주세요. 고구마가 달...,['https://recipe1.ezmember.co.kr/cache/recipe/...,NaN,0,간식
3,https://www.10000recipe.com/recipe/6880305,또띠아 피자,달걀지단이 들어간\n사과 또띠아 피자!,2,15,초급,"사과 1/4개, 사과잼 3T, 또띠아 1개, 미트소스 3T, 계란 1개, 견과류가루...","그릇, 프라이팬, 도마, 칼, 전자레인지, 가위",[{'text': '* 재료 준비\n또띠아 1개\n사과 1/4개\n사과잼 3T\n미...,['https://recipe1.ezmember.co.kr/cache/recipe/...,NaN,0,간식
4,https://www.10000recipe.com/recipe/6966633,스파게티 샌드위치,"에미넴이 디트로이트에 오픈한 맘스 스파게티 식당에서 파는 ""스파게티 샌드위치"" 궁금...",1,20,아무나,"버터 20g, 다진마늘 1T, 설탕 1t, 파슬리가루 1적당량, 토마토소스 1적당량...","계량도구, 그릇, 전자레인지, 프라이팬",[{'text': '토마토 시판소스를 이용하여 빠르게 토마토스파게티를 만든다 (저는...,['https://recipe1.ezmember.co.kr/cache/recipe/...,마늘빵 사이에 끼워먹는 토마토스파게티\n탄수화물 역시 맛있어\n유투브 구독해줭......,1,양식
...,...,...,...,...,...,...,...,...,...,...,...,...,...
81,https://www.10000recipe.com/recipe/6952453,몬테크리스토 시리얼 토스트,누구나 가지고 있는 재료들로\n정말 맛있는 토스트를 만들어봤습니다.\n겉바속촉 토스...,1,20,초급,"식빵 3장, 슬라이스햄 4장, 슬라이스치즈 2장, 계란 1개, 설탕 1큰술, 소금 ...","도마, 가위, 프라이팬","[{'text': '식빵 3장을 도마 위에 펼쳐 놓은 뒤\n한쪽 면에는 땅콩버터, ...",[],자세한 조리방법은 유튜브 영상으로 확인하실 수 있습니다.\n구독 & 좋아요 부탁드려요.,1,간식
82,https://www.10000recipe.com/recipe/6966278,김밥,당근밥으로 만드는 다이어트 김밥,3,20,초급,"밥 2공기, 매실액 1T, 김밥김 5장, 당근 2개, 소금 , 식용유 , 계란 3개...","칼로,주방용 계량도구,도마,프라이팬,주걱",[{'text': '오이는 길쯕하게 썬다.\n오이씨는 물기가 많으니 잘라내버리세요....,['https://recipe1.ezmember.co.kr/cache/recipe/...,NaN,1,간식
83,https://www.10000recipe.com/recipe/6735763,카레라이스,얼마전 일본에서 사왔던 카레로 급 만들어본 일본식 카레라이스~ 물론 카레안에도 고기...,5,30,초급,"고형카레 100g, 물 700ml, 감자 2개, 당근 1개, 양파 1개, 돼지고기 ...","칼, 냄비, 주걱, 프라이팬","[{'text': '재료들은 먹기좋게 썰어 준비하세요.', 'images': ['h...",['https://recipe1.ezmember.co.kr/cache/recipe/...,NaN,1,양식
84,https://www.10000recipe.com/recipe/6881857,쇠고기볶음,아이들이 좋아하는 꼬기~~ 그냥 구워서도 맛있는데 향긋한 미나리 넣어서 볶았더니 향...,2,30,초급,"등심 500g, 미나리 1/2줌, 새송이버섯 100g, 마늘 10개, 청양고추 2개...","계량도구, 칼, 도마, 프라이팬, 주걱","[{'text': '청주 2큰술로 샤워시켜 준 후, 후추와 바질가루 뿌려서 잠깐 재...",[],성장기 어린이들이나 보양식으로 좋은 소고기는 단백질이 풍부해서 입맛 잃기 쉬운 요즘...,1,한식
85,https://www.10000recipe.com/recipe/6881967,김치부침개피자,김치부침개 모두들 좋아하시지요~~~\n\n피자도 좋아하시지요~~~\n\n부침개와 피...,2,30,초급,"김치 1컵, 밀가루 2/3컵, 우유 1/2컵, 모짜렐라 피자치즈 150g, 방울토마...","계량도구, 칼, 도마, 프라이팬, 국자",[{'text': '페파로니 대신 베이컨을 사용하셔도 됩니다~!~\n냉장고에 있는 ...,['https://recipe1.ezmember.co.kr/cache/recipe/...,NaN,1,한식

In [ ]:
recipes.to_csv("recipes.csv", index=False)

In [179]:
# 정규표현식 패턴
pattern = r"^(?P<ingredients>[가-힣a-zA-Z\s]+?)\s*(?:(?P<quantity>\d+(?:/\d+)?)(?P<unit>[가-힣a-zA-Z]+|적당량|약간))?$"

recipes_ingredients = (
    recipes
    .assign(ingredients=lambda df: df['materials'].str.split(','))  # 재료 리스트 분리
    .explode('ingredients')                                         # 행으로 펼치기
    .assign(ingredients=lambda df: df['ingredients'].str.strip())     # 공백 제거
    .reset_index(drop=True)[['title', 'ingredients']]
)

recipes_ingredients = pd.concat([recipes_ingredients['title'], recipes_ingredients['ingredients'].str.extract(pattern)], axis=1)

recipes_ingredients

       title ingredients quantity unit
0        떡꼬치         가래떡        7    개
1        떡꼬치         식용유        1   약간
2        떡꼬치          케찹        3   큰술
3        떡꼬치         진간장      1/2   큰술
4        떡꼬치         고추장        1   큰술
..       ...         ...      ...  ...
672  김치부침개피자       방울토마토        5    개
673  김치부침개피자         올리브        5    개
674  김치부침개피자        페퍼로니       10    개
675  김치부침개피자        새싹채소        1   약간
676  김치부침개피자         식용유        1   큰술

[677 rows x 4 columns]

In [180]:
recipes_ingredients['ingredients'].unique()

array(['가래떡', '식용유', '케찹', '진간장', '고추장', '올리고당', '설탕', '다진마늘', '깨', '식빵',
       '계란', '슬라이스치즈', '소금', '꿀', '고구마', '올리브유', '사과', '사과잼', '또띠아',
       '미트소스', '견과류가루', '모짜렐라 피자치즈', '버터', '파슬리가루', '토마토소스', '스파게티면',
       '슬라이스 모짜렐라', '크림치즈', '치커리', '딸기', '딸기잼', '양배추', '감자', '당근', '오이',
       '허니머스터드', '마요네즈', '후추', '양파', '감자전분', '우유', '연어 통조림', '모닝빵', '양상추',
       '씨겨자', '체더치즈', '슬라이스햄', '상추', '토마토', '닭가슴살', '베이컨', '허브솔트', '물',
       '돈까스소스', '머스터드', '맛술', '깻잎', '스리라차소스', '스윗씨겨자소스', '생크림', '딸기청',
       '슈가파우더', '두부', '다진 호박', '다진 당근', '다시마물', '그릭요거트', '아보카도퓨레',
       '방울토마토', '할라피뇨', '견과류', '새우', '청주', '레몬즙', '크러쉬드페퍼', '파슬리', '요거트',
       '샐러리', '피칸', '건크랜베리', '파프리카', '통밀빵', '아보카도', '페페론치노', '밥', '장조림',
       '무장아찌', '포도씨유', '후리가케', '장조림국물', '단호박', '새싹채소', '통오징어',
       '오리엔탈 샐러드 드레싱', '고춧가루', '간장', '식초', '겨자', '매실청', '게맛살', '쌀가루',
       '아몬드가루', '베이킹파우더', '황설탕', '콩나물', '다진파', '국간장', '참기름', '통삼겹살',
       '로즈마리', '애호박', '콘옥수수', '소고기 척아이롤', '야채', '파마산치즈가루', '파프리카파우더',
       '밀가루', '넛맥', '타피오카전분', '그라나파다노치즈', '카놀라유', '두유', '얼그레이 티백',
       '꽁치통조림', '카레가루', '숙주나물', '매실즙', '다진양파', '청양고추', '홍고추', '멸치', '고추',
       '소주', '돼지고기', '김치', '마늘', '버섯', '엔초비', '파스타', '허브믹스', '새송이버섯',
       '대파', '굴소스', '라이스페이퍼', '다진마늘 듬뿍', '피망', '소금 톡톡', '후추 톡톡', '명란젓',
       '메밀면', '쪽파', '쯔유', '무', '깔라만시원액', '쌀', '참치', '김', '김자반', '메밀국수',
       '깨소금', '매실액', '들기름', '생강', '비엔나소시지', '마늘쫑', '채끝살', '양송이버섯', '삼겹살',
       '건로즈마리', '양조간장', '액젓', '돈까스고기', '만두소', '떡국떡', '명란', '된장', '풋고추',
       '만두피', '케첩', '열무김치', '소면', '얼음', '중면', '부추', '참외', '냉면양념장', '순두부',
       nan, '떡', '만두', '어묵', '멸치가루', '다시마', '멸치액젓', '브로콜리', '연어', '올리브',
       '플레인요거트', '아스파라거스', '소세지', '후랑크소시지', '조미료', '닭', '데리야키소스', '땅콩버터',
       '시리얼', '김밥김', '단무지', '고형카레', '돼지고기 안심', '등심', '미나리', '페퍼로니'],
      dtype=object)

In [181]:
recipes_ingredients.to_csv('recipes_ingredients.csv', index=False)

## 도구 이름 정제

In [65]:
import pandas as pd
from openai import OpenAI
import time

client = OpenAI(api_key="sktax-XyeKFrq67ZjS4EpsDlrHHXV8it", base_url="https://guest-api.sktax.chat/v1")

In [88]:
# AI에게 카테고리 분류 요청
def categorize_with_ai(steps):
    """
    steps을 입력하면 AI가 필요한 조리 도구를 분류
    """
    prompt = f"다음 조리 단계를 보고 ['계량도구', '칼', '뒤집개', '필러', '냄비', '국자', '가위', '도마', '전자레인지', '체/거름망', '집게', '주걱', '에어프라이어', '그릇', '프라이팬'] 중 필요한 모든 조리 도구를 선택하세요. \n선택한 조리 도구들을 쉼표(,)로 구분하여 출력하고, 다른 말은 절대 하지 마세요.\n(예: 칼, 가위, 냄비)\n\n조리 단계: {steps}"
    completion = client.chat.completions.create(
        model="ax4",
        messages=[{"role": "user", "content": prompt}]
    )
    # AI 응답에서 텍스트 추출
    tool = completion.choices[0].message.content.strip()
    return tool

In [89]:
# CSV 불러오기
recipes = pd.read_csv("recipes.csv")

# tools 컬럼 초기화
tools = []

In [90]:
for idx, row in recipes[:30].iterrows():
    tool = categorize_with_ai(row["steps"])
    tools.append(tool)
    print(f"{idx+1}/{len(recipes)} 처리 완료: {tool}")

1/86 처리 완료: 에어프라이어, 프라이팬, 그릇
2/86 처리 완료: 프라이팬, 주걱, 뒤집개, 계량도구
3/86 처리 완료: 계량도구, 필러, 그릇, 주걱, 도마, 전자레인지
4/86 처리 완료: 그릇, 프라이팬, 도마, 칼, 전자레인지, 가위
5/86 처리 완료: 계량도구, 그릇, 전자레인지, 프라이팬
6/86 처리 완료: 도마, 칼, 그릇
7/86 처리 완료: 칼, 도마, 프라이팬, 전자레인지, 그릇
8/86 처리 완료: 도마, 칼, 프라이팬, 주걱, 국자, 그릇
9/86 처리 완료: 체/거름망, 냄비, 그릇
10/86 처리 완료: 프라이팬, 뒤집개, 도마, 칼
11/86 처리 완료: 냄비, 국자, 도마, 칼, 가위, 그릇
12/86 처리 완료: 체/거름망, 프라이팬, 도마, 주걱
13/86 처리 완료: 계량도구, 칼, 도마, 그릇
14/86 처리 완료: 칼, 그릇, 도마
15/86 처리 완료: 체/거름망, 전자레인지, 그릇
16/86 처리 완료: 체/거름망, 그릇, 국자, 주걱
17/86 처리 완료: 주걱, 프라이팬, 그릇, 칼
18/86 처리 완료: 체/거름망, 그릇, 도마, 칼
19/86 처리 완료: 칼, 국자, 도마, 프라이팬
20/86 처리 완료: 냄비, 국자, 그릇, 칼, 도마
21/86 처리 완료: 칼, 그릇, 프라이팬
22/86 처리 완료: 칼, 에그슬라이서, 프라이팬, 그릇, 주걱
23/86 처리 완료: 칼, 주걱, 프라이팬
24/86 처리 완료: 프라이팬, 주걱
25/86 처리 완료: 에어프라이어, 그릇
26/86 처리 완료: 주걱, 냄비, 그릇, 도마, 칼
27/86 처리 완료: 프라이팬, 도마, 칼
28/86 처리 완료: 체/거름망, 계량도구, 칼, 주걱, 프라이팬, 에어프라이어
29/86 처리 완료: 체/거름망, 그릇, 프라이팬
30/86 처리 완료: 칼, 에어프라이어, 그릇

In [91]:
for idx, row in recipes[30:60].iterrows():
    tool = categorize_with_ai(row["steps"])
    tools.append(tool)
    print(f"{idx+1}/{len(recipes)} 처리 완료: {tool}")

31/86 처리 완료: 체/거름망, 그릇, 에어프라이어
32/86 처리 완료: 에어프라이어, 도마, 칼, 주걱, 프라이팬
33/86 처리 완료: 칼, 그릇, 에어프라이어
34/86 처리 완료: 전자레인지, 주걱, 에어프라이어, 그릇
35/86 처리 완료: 에어프라이어, 주걱, 프라이팬
36/86 처리 완료: 주걱, 도마, 소스팬, 에어프라이어, 그릇
37/86 처리 완료: 계량도구, 에어프라이어
38/86 처리 완료: 가위, 체/거름망, 그릇, 에어프라이어
39/86 처리 완료: 체/거름망, 도구 없음, 에어프라이어, 그릇
40/86 처리 완료: 칼, 그릇, 체/거름망
41/86 처리 완료: 냄비, 도마, 칼, 그릇
42/86 처리 완료: 전자레인지, 도마, 칼, 프라이팬, 주걱
43/86 처리 완료: 칼, 도마, 국자, 프라이팬, 그릇
44/86 처리 완료: 칼, 도마, 프라이팬, 주걱
45/86 처리 완료: 계량도구, 칼, 그릇, 프라이팬, 주걱
46/86 처리 완료: 칼, 도마, 프라이팬, 주걱
47/86 처리 완료: 프라이팬, 주걱, 그릇
48/86 처리 완료: 냄비, 국자, 칼, 도마, 프라이팬, 그릇
49/86 처리 완료: 칼, 도마, 주걱, 에어프라이어, 그릇
50/86 처리 완료: 계량도구, 칼, 주걱, 프라이팬
51/86 처리 완료: 국자, 체/거름망, 그릇, 냄비
52/86 처리 완료: 칼, 프라이팬, 주걱, 뒤집개, 그릇
53/86 처리 완료: 계량도구, 체/거름망, 그릇
54/86 처리 완료: 체인/거름망, 그릇, 칼, 도마
55/86 처리 완료: 계량도구, 냄비, 체/거름망, 주걱, 그릇
56/86 처리 완료: 계란 프라이를 기준으로 프라이팬, 계량도구, 그릇, 칼이 필요합니다.
57/86 처리 완료: 칼, 도마, 냄비, 국자, 프라이팬, 주걱, 그릇
58/86 처리 완료: 계량도구, 칼, 프라이팬, 주걱
59/86 처리 완료: 칼, 팬, 도마, 주걱, 국자
60/86 처리 완료: 칼, 주걱, 프라이팬, 그릇

In [93]:
for idx, row in recipes[60:86].iterrows():
    tool = categorize_with_ai(row["steps"])
    tools.append(tool)
    print(f"{idx+1}/{len(recipes)} 처리 완료: {tool}")

61/86 처리 완료: 계량도구, 칼, 프라이팬, 주걱, 그릇
62/86 처리 완료: 프라이팬, 체/거름망, 집게
63/86 처리 완료: 계량도구, 칼, 도마, 프라이팬, 주걱, 그릇
64/86 처리 완료: 프라이팬, 주걱, 그릇
65/86 처리 완료: 칼, 냄비, 국자, 주걱, 그릇
66/86 처리 완료: 칼, 뒤집개, 그릇, 프라이팬
67/86 처리 완료: 오븐, 칼, 그릇, 주걱, 체/거름망
68/86 처리 완료: 계량도구, 칼, 도마, 프라이팬, 주걱
69/86 처리 완료: 계량도구, 냄비, 그릇, 체/거름망, 도마, 칼
70/86 처리 완료: 계량도구, 가위, 그릇, 도마, 전자레인지, 프라이팬, 주걱
71/86 처리 완료: 냄비, 체/거름망, 칼, 도마, 그릇
72/86 처리 완료: 냄비, 국자, 칼, 도마
73/86 처리 완료: 국자, 칼, 도마, 냄비
74/86 처리 완료: 칼, 냄비, 국자, 프라이팬, 도마
75/86 처리 완료: 칼, 냄비, 국자, 주걱, 그릇, 프라이팬
76/86 처리 완료: 냉장고, 프라이팬, 계량도구, 주걱, 뒤집개
77/86 처리 완료: 프라이팬, 칼, 도마, 그릇
78/86 처리 완료: 칼, 도마, 냄비, 국자, 프라이팬, 주걱
79/86 처리 완료: 칼, 프라이팬, 주걱, 그릇
80/86 처리 완료: 계량도구, 칼, 냄비, 주걱
81/86 처리 완료: 계량도구, 칼, 가위, 도마, 그릇
82/86 처리 완료: 도마, 가위, 프라이팬
83/86 처리 완료: 칼로,주방용 계량도구,도마,프라이팬,주걱
84/86 처리 완료: 칼, 냄비, 주걱, 프라이팬
85/86 처리 완료: 계량도구, 칼, 도마, 프라이팬, 주걱
86/86 처리 완료: 계량도구, 칼, 도마, 프라이팬, 국자

In [96]:
tools

['에어프라이어, 프라이팬, 그릇',
 '프라이팬, 주걱, 뒤집개, 계량도구',
 '계량도구, 필러, 그릇, 주걱, 도마, 전자레인지',
 '그릇, 프라이팬, 도마, 칼, 전자레인지, 가위',
 '계량도구, 그릇, 전자레인지, 프라이팬',
 '도마, 칼, 그릇',
 '칼, 도마, 프라이팬, 전자레인지, 그릇',
 '도마, 칼, 프라이팬, 주걱, 국자, 그릇',
 '체/거름망, 냄비, 그릇',
 '프라이팬, 뒤집개, 도마, 칼',
 '냄비, 국자, 도마, 칼, 가위, 그릇',
 '체/거름망, 프라이팬, 도마, 주걱',
 '계량도구, 칼, 도마, 그릇',
 '칼, 그릇, 도마',
 '체/거름망, 전자레인지, 그릇',
 '체/거름망, 그릇, 국자, 주걱',
 '주걱, 프라이팬, 그릇, 칼',
 '체/거름망, 그릇, 도마, 칼',
 '칼, 국자, 도마, 프라이팬',
 '냄비, 국자, 그릇, 칼, 도마',
 '칼, 그릇, 프라이팬',
 '칼, 에그슬라이서, 프라이팬, 그릇, 주걱',
 '칼, 주걱, 프라이팬',
 '프라이팬, 주걱',
 '에어프라이어, 그릇',
 '주걱, 냄비, 그릇, 도마, 칼',
 '프라이팬, 도마, 칼',
 '체/거름망, 계량도구, 칼, 주걱, 프라이팬, 에어프라이어',
 '체/거름망, 그릇, 프라이팬',
 '칼, 에어프라이어, 그릇',
 '체/거름망, 그릇, 에어프라이어',
 '에어프라이어, 도마, 칼, 주걱, 프라이팬',
 '칼, 그릇, 에어프라이어',
 '전자레인지, 주걱, 에어프라이어, 그릇',
 '에어프라이어, 주걱, 프라이팬',
 '주걱, 도마, 소스팬, 에어프라이어, 그릇',
 '계량도구, 에어프라이어',
 '가위, 체/거름망, 그릇, 에어프라이어',
 '체/거름망, 도구 없음, 에어프라이어, 그릇',
 '칼, 그릇, 체/거름망',
 '냄비, 도마, 칼, 그릇',
 '전자레인지, 도마, 칼, 프라이팬, 주걱',
 '칼, 도마, 국자, 프라이팬, 그릇',
 '칼, 도마, 프라이팬, 주걱',
 '계량도구, 칼, 그릇, 프라이팬, 주걱',
 '칼, 도마, 프라이팬, 주걱',
 '프라이팬, 주걱, 그릇',
 '냄비, 국자, 칼, 도마, 프라이팬, 그릇',
 '칼, 도마, 주걱, 에어프라이어, 그릇',
 '계량도구, 칼, 주걱, 프라이팬',
 '국자, 체/거름망, 그릇, 냄비',
 '칼, 프라이팬, 주걱, 뒤집개, 그릇',
 '계량도구, 체/거름망, 그릇',
 '체인/거름망, 그릇, 칼, 도마',
 '계량도구, 냄비, 체/거름망, 주걱, 그릇',
 '계란 프라이를 기준으로 프라이팬, 계량도구, 그릇, 칼이 필요합니다.',
 '칼, 도마, 냄비, 국자, 프라이팬, 주걱, 그릇',
 '계량도구, 칼, 프라이팬, 주걱',
 '칼, 팬, 도마, 주걱, 국자',
 '칼, 주걱, 프라이팬, 그릇',
 '계량도구, 칼, 뒤집개, 프라이팬, 주걱, 그릇',
 '프라이팬, 집게, 주걱, 체/거름망',
 '계량도구, 칼, 프라이팬, 주걱, 그릇',
 '프라이팬, 체/거름망, 집게',
 '계량도구, 칼, 도마, 프라이팬, 주걱, 그릇',
 '프라이팬, 주걱, 그릇',
 '칼, 냄비, 국자, 주걱, 그릇',
 '칼, 뒤집개, 그릇, 프라이팬',
 '오븐, 칼, 그릇, 주걱, 체/거름망',
 '계량도구, 칼, 도마, 프라이팬, 주걱',
 '계량도구, 냄비, 그릇, 체/거름망, 도마, 칼',
 '계량도구, 가위, 그릇, 도마, 전자레인지, 프라이팬, 주걱',
 '냄비, 체/거름망, 칼, 도마, 그릇',
 '냄비, 국자, 칼, 도마',
 '국자, 칼, 도마, 냄비',
 '칼, 냄비, 국자, 프라이팬, 도마',
 '칼, 냄비, 국자, 주걱, 그릇, 프라이팬',
 '냉장고, 프라이팬, 계량도구, 주걱, 뒤집개',
 '프라이팬, 칼, 도마, 그릇',
 '칼, 도마, 냄비, 국자, 프라이팬, 주걱',
 '칼, 프라이팬, 주걱, 그릇',
 '계량도구, 칼, 냄비, 주걱',
 '계량도구, 칼, 가위, 도마, 그릇',
 '도마, 가위, 프라이팬',
 '칼로,주방용 계량도구,도마,프라이팬,주걱',
 '칼, 냄비, 주걱, 프라이팬',
 '계량도구, 칼, 도마, 프라이팬, 주걱',
 '계량도구, 칼, 도마, 프라이팬, 국자']

In [100]:
recipes["tools"] = tools
recipes.head(1)

,url,title,description,servings,time,difficulty,materials,tools,steps,final_images,tips,danger,category
0,https://www.10000recipe.com/recipe/6953727,떡꼬치,떡꼬치를 너무 좋아하는데 요즘 파는곳이 별로 없어서\n간단하게 집에서 한번 만들어봤...,2,15,초급,"가래떡 7개, 기름 조금, 케찹 3큰술, 진간장 1/2큰술, 고추장 1큰술, 올리고...","에어프라이어, 프라이팬, 그릇",[{'text': '떡에 기름을 골고루 조금씩 묻혀 에어프라이어에 돌려줍니다\n18...,[],"저는 이마트에서 2,000원짜리 떡 한팩을 사와서 냉동에 넣지않고 바로 뒷날 해먹었...",0,간식

In [101]:
recipes.to_csv("recipes_processed_tools.csv", index=False)

## 재료 이름 정제

In [ ]:
import pandas as pd
from openai import OpenAI
import time

client = OpenAI(api_key="sktax-XyeKFrq67ZjS4EpsDlrHHXV8it", base_url="https://guest-api.sktax.chat/v1")

In [ ]:
# AI에게 카테고리 분류 요청
def categorize_with_ai(ingredients):
    """
    ingredients을 입력하면 AI가 필요한 조리 도구를 분류
    """
    prompt = f"다음 재료 리스트에서 재료 이름을 정확하게 정리하고, 수량과 단위는 유지하세요. \n불필요한 수식어나 모호한 표현(예: '긴거', '조금')은 제거하고 표준적인 재료명으로만 남기세요.\n예시 입력: \"가래떡 긴거 7개, 기름 조금, 케찹 3큰술, 진간장 1/2큰술, 고추장 1큰술\"\n예시 출력: \"가래떡 7개, 식용유 약간, 케찹 3큰술, 진간장 1/2큰술, 고추장 1큰술\"\n\n재료들을 쉼표(,)로 구분하여 출력하고, 다른 말은 절대 하지 마세요.\n\n재료 리스트: {ingredients}"
    completion = client.chat.completions.create(
        model="ax4",
        messages=[{"role": "user", "content": prompt}]
    )
    # AI 응답에서 텍스트 추출
    ingredient = completion.choices[0].message.content.strip()
    return ingredient

In [112]:
# CSV 불러오기
recipes = pd.read_csv("recipes.csv")

# ingredients 컬럼 초기화
ingredients = []

In [113]:
for idx, row in recipes[:30].iterrows():
    ingredient = categorize_with_ai(row["materials"])
    ingredients.append(ingredient)
    print(f"{idx+1}/{len(recipes)} 처리 완료: {row['materials']} -> {ingredient}")

1/86 처리 완료: 가래떡 7개, 기름 조금, 케찹 3큰술, 진간장 1/2큰술, 고추장 1큰술, 올리고당 2큰술, 설탕 2/3큰술, 다진마늘 1/2큰술, 깨 취향껏 -> 가래떡 7개, 식용유 약간, 케찹 3큰술, 진간장 1/2큰술, 고추장 1큰술, 올리고당 2큰술, 설탕 2/3큰술, 다진마늘 1/2큰술, 깨 약간
2/86 처리 완료: 빵 4장, 달걀 2개, 슬라이스 치즈 2장, 소금 톡톡, 꿀 듬뿍 -> 빵 4장, 달걀 2개, 슬라이스 치즈 2장, 소금 약간, 꿀 적당히
3/86 처리 완료: 고구마 2개, 계란 흰자 2개, 올리브오일 약간 -> 고구마 2개, 계란 흰자 2개, 올리브오일 약간
4/86 처리 완료: 사과 1/4개, 사과잼 3T, 또띠아 1개, 미트스파게티소스 3T, 달걀 1개, 견과류 가루계피가루가 들어간 1~2T, 모짜렐라 피자치즈 5~6T, 식용유 1~2t -> 사과 1/4개, 사과잼 3T, 또띠아 1개, 미트스파게티소스 3T, 달걀 1개, 견과류 계피가루 1~2T, 모짜렐라 피자치즈 5~6T, 식용유 1~2t
5/86 처리 완료: 버터 20g, 다진마늘 1T, 설탕 1t, 파슬리가루 적당량, 토마토스파게티소스 적당량, 스파게티 1인분, 식빵 2장, 슬라이스 모짜렐라 2장 -> 버터 20g, 다진마늘 1T, 설탕 1t, 파슬리가루 약간, 토마토스파게티소스 약간, 스파게티 1인분, 식빵 2장, 슬라이스 모짜렐라 2장
6/86 처리 완료: 크림치즈 2큰술, 식빵 4장, 치커리 , 딸기 적당량, 슬라이스치즈 4장, 딸기잼취향껏 약간 -> 크림치즈 2큰술, 식빵 4장, 치커리, 딸기 적당량, 슬라이스치즈 4장, 딸기잼 약간
7/86 처리 완료: 양배추 1/4, 감자 1개, 당근 조금, 계란 4알, 식빵 8장, 오이 1개, 허니머스타드 적당히, 마요네즈 적당히, 소금 , 후추 약간, 케찹  -> 양배추 1/4, 감자 1개, 당근 조금, 계란 4개, 식빵 8장, 오이 1개, 허니머스타드 약간, 마요네즈 약간, 소금 약간, 후추 약간, 케찹 1개
8/86 처리 완료: 식빵 4장, 감자 2개, 삶은 달걀 1개, 양파 1/4개, 양배추 3~4장, 슬라이스치즈 2장, 감자전분 1.5큰술, 우유 2큰술, 소금 약간, 후추 약간 -> 식빵 4장, 감자 2개, 삶은 달걀 1개, 양파 1/4개, 양배추 3~4장, 슬라이스치즈 2장, 감자전분 1.5큰술, 우유 2큰술, 소금 약간, 후추 약간
9/86 처리 완료: 연어 통조림 3캔, 양파 1/2개, 사과 1/2개, 삶은 계란 5개, 모닝빵 10개, 양상추 3-4장, 마요네즈 , 씨겨자 , 후추 , 소금 , 올리고당 3T -> 연어 통조림 3캔, 양파 1/2개, 사과 1/2개, 삶은 계란 5개, 모닝빵 10개, 양상추 3-4장, 마요네즈 약간, 씨겨자 약간, 후추 약간, 소금 약간, 올리고당 3T
10/86 처리 완료: 또띠아 1장, 체더치즈 1장, 슬라이스햄 2장, 상추 1장, 달걀 1개, 토마토 1개 -> 또띠아 1장, 체더치즈 1장, 슬라이스햄 2장, 상추 1장, 달걀 1개, 토마토 1개
11/86 처리 완료: 닭가슴살 300g, 식빵 6장, 삶은계란 2개, 토마토 2개, 청상추 6장, 베이컨 3줄, 후추 , 후추 , 허브솔트 , 물 , 마요네즈 5스푼, 돈까스소스 3스푼, 머스터드소스  -> 닭가슴살 300g, 식빵 6장, 삶은계란 2개, 토마토 2개, 청상추 6장, 베이컨 3줄, 후추, 후추, 허브솔트, 물, 마요네즈 5스푼, 돈까스소스 3스푼, 머스터드소스
12/86 처리 완료: 계란 3개, 맛술 1큰술, 닭가슴살 1/2개, 슬라이스치즈 2장, 상추 2장, 깻잎 4장, 양파 1/4개, 양상추 약간, 스리라차소스 적당량, 소금 약간, 후추 약간, 기름 1큰술 -> 계란 3개, 맛술 1큰술, 닭가슴살 1/2개, 슬라이스치즈 2장, 상추 2장, 깻잎 4장, 양파 1/4개, 양상추 약간, 스리라차소스 적당량, 소금 약간, 후추 약간, 식용유 1큰술
13/86 처리 완료: 식빵 4조각, 치즈 2장, 토마토 2개, 삶은 달걀 2개, 샌드위치 햄 6장, 버터 2큰술, 양상추 적당량, 스윗씨겨자소스  -> 식빵 4조각, 치즈 2장, 토마토 2개, 삶은 달걀 2개, 샌드위치 햄 6장, 버터 2큰술, 양상추 적당량, 스윗씨겨자소스 1큰술
14/86 처리 완료: 식빵 4개, 딸기 16개, 생크림 , 딸기 5개, 생크림 , 딸기청 , 슈가파우더  -> 식빵 4개, 딸기 21개, 생크림, 딸기청, 슈가파우더
15/86 처리 완료: 달걀 8개, 소금 , 후추 , 마요네즈 , 식빵 , 버터  -> 달걀 8개, 소금, 후추, 마요네즈, 식빵, 버터
16/86 처리 완료: 계란(노른자만) 1개, 두부or 연두부 30~50g, 호박다진것 1큰술, 당근다진것 1큰술, 다시마 물 2큰술, 소금 약간 -> 계란(노른자) 1개, 두부 30~50g, 호박다진것 1큰술, 당근다진것 1큰술, 다시물 2큰술, 소금 약간
17/86 처리 완료: 식빵 3장, 슬라이스 체더치즈 4장, 슬라이스 햄 4장, 달걀 2개, 우유 6숟가락, 설탕 0.5, 딸기잼 , 허니머스터드 , 식용유  -> 식빵 3장, 슬라이스 체더치즈 4장, 슬라이스 햄 4장, 달걀 2개, 우유 6숟가락, 설탕 0.5, 딸기잼, 허니머스터드, 식용유
18/86 처리 완료: ?그릭 요거트 360g, 꿀 2큰술, 식빵 4장, 딸기 12개 -> 그릭 요거트 360g, 꿀 2큰술, 식빵 4장, 딸기 12개
19/86 처리 완료: 아보카도 퓨레 200g, 양파 1/4개, 방울토마토 4~5개, 할라피뇨 4~5개, 견과류(하루견과) 1봉, 소금 , 후추 약간, 냉동새우 , 청주 1큰술, 레몬즙 1큰술, 소금 , 후추 약간, 크러쉬드 페퍼 약간, 올리브오일 1큰술, 삶은 계란 2개, 파슬리 약간 -> 아보카도 퓨레 200g, 양파 1/4개, 방울토마토 4~5개, 할라피뇨 4~5개, 견과류 1봉, 소금, 후추 약간, 냉동새우, 청주 1큰술, 레몬즙 1큰술, 소금, 후추 약간, 크러쉬드 페퍼 약간, 올리브오일 1큰술, 삶은 계란 2개, 파슬리 약간
20/86 처리 완료: 닭가슴살 , 마요네즈 , 요거트 , 디종머스타드 , 샐러리 , 양파 , 피칸 , 건크랜베리 , 사과 , 파프리카 , 설탕 , 소금 , 후추 , 레몬즙 , 빵  -> 닭가슴살, 마요네즈, 요거트, 디종머스타드, 샐러리, 양파, 피칸, 건크랜베리, 사과, 파프리카, 설탕, 소금, 후추, 레몬즙, 빵
21/86 처리 완료: 통밀빵 2조각, 아보카도 1/2개, 레몬즙 1큰술, 페페론치노혹은 레드페퍼 약간, 새우 6마리, 허브솔트 약간 -> 통밀빵 2조각, 아보카도 1/2개, 레몬즙 1큰술, 페페론치노 약간, 새우 6마리, 허브솔트 약간
22/86 처리 완료: 밥 2공기, 장조림 80g, 무장아찌 1/2컵, 달걀 3개, 포도씨유 약간, 무염버터 2큰술, 후리가케 2큰술, 장조림국물 2큰술, 소금 약간 -> 밥 2공기, 장조림 80g, 무장아찌 1/2컵, 달걀 3개, 포도씨유 약간, 무염버터 2큰술, 후리가케 2큰술, 장조림국물 2큰술, 소금 약간
23/86 처리 완료: 식빵 4장, 슬라이스치즈 2장, 햄 2장, 마요네즈 1큰술, 녹인버터 1큰술 -> 식빵 4장, 슬라이스치즈 2장, 햄 2장, 마요네즈 1큰술, 녹인버터 1큰술
24/86 처리 완료: 또띠아 2장, 찐 단호박 120g, 슬라이스 햄 2장, 토마토 1개, 모짜렐라 피자치즈 50g, 크림치즈 1큰술, 올리고당 2작은술 -> 또띠아 2장, 찐 단호박 120g, 슬라이스 햄 2장, 토마토 1개, 모짜렐라 피자치즈 50g, 크림치즈 1큰술, 올리고당 2작은술
25/86 처리 완료: 냉장고속야채또는샐러드용새싹 , 통오징어 1마리, 시판 무지방 오리엔탈 샐러드 드레싱 2스푼 -> 냉장고속야채, 샐러드용새싹, 통오징어 1마리, 무지방 오리엔탈 샐러드 드레싱 2스푼
26/86 처리 완료: 닭가슴살캔 , 오이 , 양파 , 고춧가루 2큰술, 간장 1큰술, 식초 1큰술, 겨자 1~3큰술, 다진마늘 1작은술, 올리고당 1큰술, 매실청 1작은술, 깨 조금 -> 닭가슴살캔, 오이, 양파, 고춧가루 2큰술, 간장 1큰술, 식초 1큰술, 겨자 1~3큰술, 다진마늘 1작은술, 올리고당 1큰술, 매실청 1작은술, 깨소금 약간
27/86 처리 완료: 양상추 6~7장, 상추 8~9장, 게맛살 200g, 노란 파프리카 1개, 빨간 파프리카 1개, 허니머스터드 3TS, 마요네즈 2TS, 후추 조금 -> 양상추 6~7장, 상추 8~9장, 게맛살 200g, 노란 파프리카 1개, 빨간 파프리카 1개, 허니머스터드 3TS, 마요네즈 2TS, 후추 약간
28/86 처리 완료: 제과용 쌀가루 105g, 아몬드가루 25g, 베이킹파우다 1g, 무염버터 60g, 황설탕 70g, 계란 25g, 견과류 80g -> 제과용 쌀가루 105g, 아몬드가루 25g, 베이킹파우더 1g, 무염버터 60g, 황설탕 70g, 계란 25g, 견과류 80g
29/86 처리 완료: 콩나물 300g, 다진파 2T, 다진마늘 2/3T, 국간장 2/3T, 고운소금 1/2~1/3T, 고춧가루 1T, 참기름 1T, 깨 1T -> 콩나물 300g, 다진파 2T, 다진마늘 2/3T, 국간장 2/3T, 고운소금 1/2~1/3T, 고춧가루 1T, 참기름 1T, 깨 1T
30/86 처리 완료: 통삼겹살 1kg, 소금(블루솔트) , 후추 , 로즈마리 , 올리브유 , 양파 , 감자 , 파프리카 , 애호박  -> 통삼겹살 1kg, 소금, 후추, 로즈마리, 올리브유, 양파, 감자, 파프리카, 애호박

In [114]:
ingredients

['가래떡 7개, 식용유 약간, 케찹 3큰술, 진간장 1/2큰술, 고추장 1큰술, 올리고당 2큰술, 설탕 2/3큰술, 다진마늘 1/2큰술, 깨 약간',
 '빵 4장, 달걀 2개, 슬라이스 치즈 2장, 소금 약간, 꿀 적당히',
 '고구마 2개, 계란 흰자 2개, 올리브오일 약간',
 '사과 1/4개, 사과잼 3T, 또띠아 1개, 미트스파게티소스 3T, 달걀 1개, 견과류 계피가루 1~2T, 모짜렐라 피자치즈 5~6T, 식용유 1~2t',
 '버터 20g, 다진마늘 1T, 설탕 1t, 파슬리가루 약간, 토마토스파게티소스 약간, 스파게티 1인분, 식빵 2장, 슬라이스 모짜렐라 2장',
 '크림치즈 2큰술, 식빵 4장, 치커리, 딸기 적당량, 슬라이스치즈 4장, 딸기잼 약간',
 '양배추 1/4, 감자 1개, 당근 조금, 계란 4개, 식빵 8장, 오이 1개, 허니머스타드 약간, 마요네즈 약간, 소금 약간, 후추 약간, 케찹 1개',
 '식빵 4장, 감자 2개, 삶은 달걀 1개, 양파 1/4개, 양배추 3~4장, 슬라이스치즈 2장, 감자전분 1.5큰술, 우유 2큰술, 소금 약간, 후추 약간',
 '연어 통조림 3캔, 양파 1/2개, 사과 1/2개, 삶은 계란 5개, 모닝빵 10개, 양상추 3-4장, 마요네즈 약간, 씨겨자 약간, 후추 약간, 소금 약간, 올리고당 3T',
 '또띠아 1장, 체더치즈 1장, 슬라이스햄 2장, 상추 1장, 달걀 1개, 토마토 1개',
 '닭가슴살 300g, 식빵 6장, 삶은계란 2개, 토마토 2개, 청상추 6장, 베이컨 3줄, 후추, 후추, 허브솔트, 물, 마요네즈 5스푼, 돈까스소스 3스푼, 머스터드소스',
 '계란 3개, 맛술 1큰술, 닭가슴살 1/2개, 슬라이스치즈 2장, 상추 2장, 깻잎 4장, 양파 1/4개, 양상추 약간, 스리라차소스 적당량, 소금 약간, 후추 약간, 식용유 1큰술',
 '식빵 4조각, 치즈 2장, 토마토 2개, 삶은 달걀 2개, 샌드위치 햄 6장, 버터 2큰술, 양상추 적당량, 스윗씨겨자소스 1큰술',
 '식빵 4개, 딸기 21개, 생크림, 딸기청, 슈가파우더',
 '달걀 8개, 소금, 후추, 마요네즈, 식빵, 버터',
 '계란(노른자) 1개, 두부 30~50g, 호박다진것 1큰술, 당근다진것 1큰술, 다시물 2큰술, 소금 약간',
 '식빵 3장, 슬라이스 체더치즈 4장, 슬라이스 햄 4장, 달걀 2개, 우유 6숟가락, 설탕 0.5, 딸기잼, 허니머스터드, 식용유',
 '그릭 요거트 360g, 꿀 2큰술, 식빵 4장, 딸기 12개',
 '아보카도 퓨레 200g, 양파 1/4개, 방울토마토 4~5개, 할라피뇨 4~5개, 견과류 1봉, 소금, 후추 약간, 냉동새우, 청주 1큰술, 레몬즙 1큰술, 소금, 후추 약간, 크러쉬드 페퍼 약간, 올리브오일 1큰술, 삶은 계란 2개, 파슬리 약간',
 '닭가슴살, 마요네즈, 요거트, 디종머스타드, 샐러리, 양파, 피칸, 건크랜베리, 사과, 파프리카, 설탕, 소금, 후추, 레몬즙, 빵',
 '통밀빵 2조각, 아보카도 1/2개, 레몬즙 1큰술, 페페론치노 약간, 새우 6마리, 허브솔트 약간',
 '밥 2공기, 장조림 80g, 무장아찌 1/2컵, 달걀 3개, 포도씨유 약간, 무염버터 2큰술, 후리가케 2큰술, 장조림국물 2큰술, 소금 약간',
 '식빵 4장, 슬라이스치즈 2장, 햄 2장, 마요네즈 1큰술, 녹인버터 1큰술',
 '또띠아 2장, 찐 단호박 120g, 슬라이스 햄 2장, 토마토 1개, 모짜렐라 피자치즈 50g, 크림치즈 1큰술, 올리고당 2작은술',
 '냉장고속야채, 샐러드용새싹, 통오징어 1마리, 무지방 오리엔탈 샐러드 드레싱 2스푼',
 '닭가슴살캔, 오이, 양파, 고춧가루 2큰술, 간장 1큰술, 식초 1큰술, 겨자 1~3큰술, 다진마늘 1작은술, 올리고당 1큰술, 매실청 1작은술, 깨소금 약간',
 '양상추 6~7장, 상추 8~9장, 게맛살 200g, 노란 파프리카 1개, 빨간 파프리카 1개, 허니머스터드 3TS, 마요네즈 2TS, 후추 약간',
 '제과용 쌀가루 105g, 아몬드가루 25g, 베이킹파우더 1g, 무염버터 60g, 황설탕 70g, 계란 25g, 견과류 80g',
 '콩나물 300g, 다진파 2T, 다진마늘 2/3T, 국간장 2/3T, 고운소금 1/2~1/3T, 고춧가루 1T, 참기름 1T, 깨 1T',
 '통삼겹살 1kg, 소금, 후추, 로즈마리, 올리브유, 양파, 감자, 파프리카, 애호박']

In [115]:
for idx, row in recipes[30:60].iterrows():
    tool = categorize_with_ai(row["steps"])
    tools.append(tool)
    print(f"{idx+1}/{len(recipes)} 처리 완료: {tool}")

31/86 처리 완료: 옥수수 150g, 마요네즈 1.5큰술, 허니머스타드 1.5큰술, 흰후추 약간, 모짜렐라치즈 반컵, 모닝빵, 파슬리가루, 종이호일
32/86 처리 완료: 소고기 3장, 올리브오일, 소금, 후춧가루, 삼겹살용/스테이크용 버터 1개, 고구마, 꿀 또는 올리고당, 소금 약간, 버터 0.5개, 치즈, 파슬리, 파프리카, 편마늘, 편인삼
33/86 처리 완료: 고구마 적당량, 조미료 적당량, ㄱ/고운 고춧가루 약간
34/86 처리 완료: 밥, 종이호일, 물
35/86 처리 완료: 떡, 식용유 약간, 케찹 3큰술, 진간장 1/2큰술, 고추장 1큰술, 올리고당 2큰술, 설탕 2/3큰술, 다진마늘 1/2큰술, 깨 약간
36/86 처리 완료: 식빵, 슬라이스 햄, 슬라이스 치즈, 버터, 밀가루, 우유, 넛맥 약간, 소금, 후추 조금, 베샤멜소스, 모짜렐라 피자치즈, 파슬리 가루
37/86 처리 완료: 우유 150ml, 버터 50g, 피자치즈 60g, 체더치즈 2장, 달걀 1개, 그라나파다노 치즈 약간, 소금 0.3T, 타피오카 전분 180g, 에어프라이어, 올리브오일, 머핀틀, 식힘망
38/86 처리 완료: 박력쌀가루, 슈가파우더, 아몬드가루, 소금, 카놀라유, 두유, 설탕, 얼그레이, 티백
39/86 처리 완료: 꽁치통조림, 밀가루, 카레가루, 에프용 종이호일, 식용유 약간
40/86 처리 완료: 숙주, 당근, 참기름 1T, 국간장 1/2T, 아기소금, 통깨 약간
41/86 처리 완료: 달걀 11개, 간장 4큰술, 생수 4큰술, 맛술 2큰술, 매실즙 2큰술, 올리고당 2큰술, 마늘 1큰술, 양파다진것 2큰술, 청양고추다진것 2큰술, 홍고추 2개
42/86 처리 완료: 중멸치 적당량, 청양고추로 만든 고추지 적당량, 간장 0
43/86 처리 완료: 삼겹살, 파스타, 김치, 마늘, 양파, 버섯, 엔초비, 올리브오일, 소금, 버터, 새싹채소, 치즈가루
44/86 처리 완료: 토마토, 파프리카, 새송이버섯, 닭가슴살, 올리브유, 토마토소스 2스푼, 계란 2개, 식용유, 케찹 약간
45/86 처리 완료: 새우, 파 적당량, 계란, 우유 1큰술, 식용류, 밥, 후추, 굴소스
46/86 처리 완료: 토마토, 계란 2개, 소금 두꼬집, 후추, 올리브유 약간, 라이스페이퍼 2장, 모짜렐라치즈, 파슬리, 꿀
47/86 처리 완료: 식용유 약간, 다진마늘 3T, 밥 1공기, 소금 1꼬집, 버터 10g, 진간장 1T, 소금 약간, 통깨 조금
48/86 처리 완료: 스파게티 면, 물, 소금, 올리브 오일, 베이컨, 마늘, 소금, 후추, 면수, 후추, 소금, 올리브 오일, 깻잎, 파마산 치즈 가루
49/86 처리 완료: 식빵 2장, 피망, 대파, 새우살, 소금, 후춧가루, 통깨, 참기름, 식용유
50/86 처리 완료: 계란 2개, 명란젓 1.5T, 식용유 약간, 밥 1공기, 마요네즈 1T, 야채, 통깨 후리가케 약간
51/86 처리 완료: 면 1인분, 쯔유, 쪽파 1개, 무즙, 깍두기, 얼음, 고추냉이 약간, 연겨자 약간
52/86 처리 완료: 버터, 달걀 1개, 원당 1/4작은술, 깔라만시원액 1/4작은술, 식빵 2조각, 모짜렐라치즈, 달걀 1개
53/86 처리 완료: 쌀, 파프리카, 참치, 참기름, 마요네즈, 김
54/86 처리 완료: 상추, 참기름, 소금, 깨, 밥, 김자반, 고기
55/86 처리 완료: 물 1L, 메밀국수 200g, 진간장 2큰술, 매실액 1큰술, 설탕 1큰술, 들기름 6큰술
56/86 처리 완료: 참치 75g, 마요네즈 1큰술, 후추 약간, 아보카도 1개, 계란 1개, 간장 1큰술, 설탕 1/2큰술, 참기름 1큰술, 밥 1공기, 상추 3장, 깨소금 약간
57/86 처리 완료: 양배추, 양파, 두부, 물 200ml, 진간장 100ml, 맛술 50ml, 마늘 1/2큰술, 생강 10g, 갈색 설탕 3큰술, 올리고당 1큰술, 참기름 1큰술, 깨소금 1큰술, 식용유 약간, 밥, 데리야키 소스 7~8큰술, 파슬리, 데리야끼 소스 2큰술
58/86 처리 완료: 계란 2개, 명란젓 1 1/2T, 식용유, 야채, 밥 1공기, 마요네즈 1T, 통깨, 후리가케
59/86 처리 완료: 소시지, 마늘쫑, 기름, 달걀, 소금, 밥, 소금, 굴소스, 햄, 들기름
60/86 처리 완료: 장조림 적당히, 무장아찌 적당히, 버터 약간, 달걀 1개, 포도씨유 약간, 소금 약간, 밥 약간, 버터 1큰술, 장조림 국물 1큰술, 달걀지단 적당량, 후리가케 약간

In [ ]:
for idx, row in recipes[60:86].iterrows():
    tool = categorize_with_ai(row["steps"])
    tools.append(tool)
    print(f"{idx+1}/{len(recipes)} 처리 완료: {tool}")

61/86 처리 완료: 계량도구, 칼, 프라이팬, 주걱, 그릇
62/86 처리 완료: 프라이팬, 체/거름망, 집게
63/86 처리 완료: 계량도구, 칼, 도마, 프라이팬, 주걱, 그릇
64/86 처리 완료: 프라이팬, 주걱, 그릇
65/86 처리 완료: 칼, 냄비, 국자, 주걱, 그릇
66/86 처리 완료: 칼, 뒤집개, 그릇, 프라이팬
67/86 처리 완료: 오븐, 칼, 그릇, 주걱, 체/거름망
68/86 처리 완료: 계량도구, 칼, 도마, 프라이팬, 주걱
69/86 처리 완료: 계량도구, 냄비, 그릇, 체/거름망, 도마, 칼
70/86 처리 완료: 계량도구, 가위, 그릇, 도마, 전자레인지, 프라이팬, 주걱
71/86 처리 완료: 냄비, 체/거름망, 칼, 도마, 그릇
72/86 처리 완료: 냄비, 국자, 칼, 도마
73/86 처리 완료: 국자, 칼, 도마, 냄비
74/86 처리 완료: 칼, 냄비, 국자, 프라이팬, 도마
75/86 처리 완료: 칼, 냄비, 국자, 주걱, 그릇, 프라이팬
76/86 처리 완료: 냉장고, 프라이팬, 계량도구, 주걱, 뒤집개
77/86 처리 완료: 프라이팬, 칼, 도마, 그릇
78/86 처리 완료: 칼, 도마, 냄비, 국자, 프라이팬, 주걱
79/86 처리 완료: 칼, 프라이팬, 주걱, 그릇
80/86 처리 완료: 계량도구, 칼, 냄비, 주걱
81/86 처리 완료: 계량도구, 칼, 가위, 도마, 그릇
82/86 처리 완료: 도마, 가위, 프라이팬
83/86 처리 완료: 칼로,주방용 계량도구,도마,프라이팬,주걱
84/86 처리 완료: 칼, 냄비, 주걱, 프라이팬
85/86 처리 완료: 계량도구, 칼, 도마, 프라이팬, 주걱
86/86 처리 완료: 계량도구, 칼, 도마, 프라이팬, 국자

In [211]:
tools

['에어프라이어, 프라이팬, 그릇',
 '프라이팬, 주걱, 뒤집개, 계량도구',
 '계량도구, 필러, 그릇, 주걱, 도마, 전자레인지',
 '그릇, 프라이팬, 도마, 칼, 전자레인지, 가위',
 '계량도구, 그릇, 전자레인지, 프라이팬',
 '도마, 칼, 그릇',
 '칼, 도마, 프라이팬, 전자레인지, 그릇',
 '도마, 칼, 프라이팬, 주걱, 국자, 그릇',
 '체/거름망, 냄비, 그릇',
 '프라이팬, 뒤집개, 도마, 칼',
 '냄비, 국자, 도마, 칼, 가위, 그릇',
 '체/거름망, 프라이팬, 도마, 주걱',
 '계량도구, 칼, 도마, 그릇',
 '칼, 그릇, 도마',
 '체/거름망, 전자레인지, 그릇',
 '체/거름망, 그릇, 국자, 주걱',
 '주걱, 프라이팬, 그릇, 칼',
 '체/거름망, 그릇, 도마, 칼',
 '칼, 국자, 도마, 프라이팬',
 '냄비, 국자, 그릇, 칼, 도마',
 '칼, 그릇, 프라이팬',
 '칼, 에그슬라이서, 프라이팬, 그릇, 주걱',
 '칼, 주걱, 프라이팬',
 '프라이팬, 주걱',
 '에어프라이어, 그릇',
 '주걱, 냄비, 그릇, 도마, 칼',
 '프라이팬, 도마, 칼',
 '체/거름망, 계량도구, 칼, 주걱, 프라이팬, 에어프라이어',
 '체/거름망, 그릇, 프라이팬',
 '칼, 에어프라이어, 그릇',
 '체/거름망, 그릇, 에어프라이어',
 '에어프라이어, 도마, 칼, 주걱, 프라이팬',
 '칼, 그릇, 에어프라이어',
 '전자레인지, 주걱, 에어프라이어, 그릇',
 '에어프라이어, 주걱, 프라이팬',
 '주걱, 도마, 소스팬, 에어프라이어, 그릇',
 '계량도구, 에어프라이어',
 '가위, 체/거름망, 그릇, 에어프라이어',
 '체/거름망, 도구 없음, 에어프라이어, 그릇',
 '칼, 그릇, 체/거름망',
 '냄비, 도마, 칼, 그릇',
 '전자레인지, 도마, 칼, 프라이팬, 주걱',
 '칼, 도마, 국자, 프라이팬, 그릇',
 '칼, 도마, 프라이팬, 주걱',
 '계량도구, 칼, 그릇, 프라이팬, 주걱',
 '칼, 도마, 프라이팬, 주걱',
 '프라이팬, 주걱, 그릇',
 '냄비, 국자, 칼, 도마, 프라이팬, 그릇',
 '칼, 도마, 주걱, 에어프라이어, 그릇',
 '계량도구, 칼, 주걱, 프라이팬',
 '국자, 체/거름망, 그릇, 냄비',
 '칼, 프라이팬, 주걱, 뒤집개, 그릇',
 '계량도구, 체/거름망, 그릇',
 '체인/거름망, 그릇, 칼, 도마',
 '계량도구, 냄비, 체/거름망, 주걱, 그릇',
 '계란 프라이를 기준으로 프라이팬, 계량도구, 그릇, 칼이 필요합니다.',
 '칼, 도마, 냄비, 국자, 프라이팬, 주걱, 그릇',
 '계량도구, 칼, 프라이팬, 주걱',
 '칼, 팬, 도마, 주걱, 국자',
 '칼, 주걱, 프라이팬, 그릇',
 '계량도구, 칼, 뒤집개, 프라이팬, 주걱, 그릇',
 '프라이팬, 체/거름망, 집게',
 '계량도구, 칼, 도마, 프라이팬, 주걱, 그릇',
 '프라이팬, 주걱, 그릇',
 '칼, 냄비, 국자, 주걱, 그릇',
 '칼, 뒤집개, 그릇, 프라이팬',
 '오븐, 칼, 그릇, 주걱, 체/거름망',
 '계량도구, 칼, 도마, 프라이팬, 주걱',
 '계량도구, 냄비, 그릇, 체/거름망, 도마, 칼',
 '계량도구, 가위, 그릇, 도마, 전자레인지, 프라이팬, 주걱',
 '냄비, 체/거름망, 칼, 도마, 그릇',
 '냄비, 국자, 칼, 도마',
 '국자, 칼, 도마, 냄비',
 '칼, 냄비, 국자, 프라이팬, 도마',
 '칼, 냄비, 국자, 주걱, 그릇, 프라이팬',
 '냉장고, 프라이팬, 계량도구, 주걱, 뒤집개',
 '프라이팬, 칼, 도마, 그릇',
 '칼, 도마, 냄비, 국자, 프라이팬, 주걱',
 '칼, 프라이팬, 주걱, 그릇',
 '계량도구, 칼, 냄비, 주걱',
 '계량도구, 칼, 가위, 도마, 그릇',
 '도마, 가위, 프라이팬',
 '칼로,주방용 계량도구,도마,프라이팬,주걱',
 '칼, 냄비, 주걱, 프라이팬',
 '계량도구, 칼, 도마, 프라이팬, 주걱',
 '계량도구, 칼, 도마, 프라이팬, 국자',
 '옥수수 150g, 마요네즈 1.5큰술, 허니머스타드 1.5큰술, 흰후추 약간, 모짜렐라치즈 반컵, 모닝빵, 파슬리가루, 종이호일',
 '소고기 3장, 올리브오일, 소금, 후춧가루, 삼겹살용/스테이크용 버터 1개, 고구마, 꿀 또는 올리고당, 소금 약간, 버터 0.5개, 치즈, 파슬리, 파프리카, 편마늘, 편인삼',
 '고구마 적당량, 조미료 적당량, ㄱ/고운 고춧가루 약간',
 '밥, 종이호일, 물',
 '떡, 식용유 약간, 케찹 3큰술, 진간장 1/2큰술, 고추장 1큰술, 올리고당 2큰술, 설탕 2/3큰술, 다진마늘 1/2큰술, 깨 약간',
 '식빵, 슬라이스 햄, 슬라이스 치즈, 버터, 밀가루, 우유, 넛맥 약간, 소금, 후추 조금, 베샤멜소스, 모짜렐라 피자치즈, 파슬리 가루',
 '우유 150ml, 버터 50g, 피자치즈 60g, 체더치즈 2장, 달걀 1개, 그라나파다노 치즈 약간, 소금 0.3T, 타피오카 전분 180g, 에어프라이어, 올리브오일, 머핀틀, 식힘망',
 '박력쌀가루, 슈가파우더, 아몬드가루, 소금, 카놀라유, 두유, 설탕, 얼그레이, 티백',
 '꽁치통조림, 밀가루, 카레가루, 에프용 종이호일, 식용유 약간',
 '숙주, 당근, 참기름 1T, 국간장 1/2T, 아기소금, 통깨 약간',
 '달걀 11개, 간장 4큰술, 생수 4큰술, 맛술 2큰술, 매실즙 2큰술, 올리고당 2큰술, 마늘 1큰술, 양파다진것 2큰술, 청양고추다진것 2큰술, 홍고추 2개',
 '중멸치 적당량, 청양고추로 만든 고추지 적당량, 간장 0',
 '삼겹살, 파스타, 김치, 마늘, 양파, 버섯, 엔초비, 올리브오일, 소금, 버터, 새싹채소, 치즈가루',
 '토마토, 파프리카, 새송이버섯, 닭가슴살, 올리브유, 토마토소스 2스푼, 계란 2개, 식용유, 케찹 약간',
 '새우, 파 적당량, 계란, 우유 1큰술, 식용류, 밥, 후추, 굴소스',
 '토마토, 계란 2개, 소금 두꼬집, 후추, 올리브유 약간, 라이스페이퍼 2장, 모짜렐라치즈, 파슬리, 꿀',
 '식용유 약간, 다진마늘 3T, 밥 1공기, 소금 1꼬집, 버터 10g, 진간장 1T, 소금 약간, 통깨 조금',
 '스파게티 면, 물, 소금, 올리브 오일, 베이컨, 마늘, 소금, 후추, 면수, 후추, 소금, 올리브 오일, 깻잎, 파마산 치즈 가루',
 '식빵 2장, 피망, 대파, 새우살, 소금, 후춧가루, 통깨, 참기름, 식용유',
 '계란 2개, 명란젓 1.5T, 식용유 약간, 밥 1공기, 마요네즈 1T, 야채, 통깨 후리가케 약간',
 '면 1인분, 쯔유, 쪽파 1개, 무즙, 깍두기, 얼음, 고추냉이 약간, 연겨자 약간',
 '버터, 달걀 1개, 원당 1/4작은술, 깔라만시원액 1/4작은술, 식빵 2조각, 모짜렐라치즈, 달걀 1개',
 '쌀, 파프리카, 참치, 참기름, 마요네즈, 김',
 '상추, 참기름, 소금, 깨, 밥, 김자반, 고기',
 '물 1L, 메밀국수 200g, 진간장 2큰술, 매실액 1큰술, 설탕 1큰술, 들기름 6큰술',
 '참치 75g, 마요네즈 1큰술, 후추 약간, 아보카도 1개, 계란 1개, 간장 1큰술, 설탕 1/2큰술, 참기름 1큰술, 밥 1공기, 상추 3장, 깨소금 약간',
 '양배추, 양파, 두부, 물 200ml, 진간장 100ml, 맛술 50ml, 마늘 1/2큰술, 생강 10g, 갈색 설탕 3큰술, 올리고당 1큰술, 참기름 1큰술, 깨소금 1큰술, 식용유 약간, 밥, 데리야키 소스 7~8큰술, 파슬리, 데리야끼 소스 2큰술',
 '계란 2개, 명란젓 1 1/2T, 식용유, 야채, 밥 1공기, 마요네즈 1T, 통깨, 후리가케',
 '소시지, 마늘쫑, 기름, 달걀, 소금, 밥, 소금, 굴소스, 햄, 들기름',
 '장조림 적당히, 무장아찌 적당히, 버터 약간, 달걀 1개, 포도씨유 약간, 소금 약간, 밥 약간, 버터 1큰술, 장조림 국물 1큰술, 달걀지단 적당량, 후리가케 약간']

In [ ]:
recipes["tools"] = tools
recipes.head(1)

,url,title,description,servings,time,difficulty,materials,tools,steps,final_images,tips,danger,category
0,https://www.10000recipe.com/recipe/6953727,떡꼬치,떡꼬치를 너무 좋아하는데 요즘 파는곳이 별로 없어서\n간단하게 집에서 한번 만들어봤...,2,15,초급,"가래떡 7개, 기름 조금, 케찹 3큰술, 진간장 1/2큰술, 고추장 1큰술, 올리고...","에어프라이어, 프라이팬, 그릇",[{'text': '떡에 기름을 골고루 조금씩 묻혀 에어프라이어에 돌려줍니다\n18...,[],"저는 이마트에서 2,000원짜리 떡 한팩을 사와서 냉동에 넣지않고 바로 뒷날 해먹었...",0,간식

In [182]:
recipes.to_csv("recipes.csv", index=False)

## 사진 URL 가져오기

In [223]:
import pandas as pd

recipes = pd.read_csv('recipes.csv')

In [224]:
recipes.head(1)

,url,title,description,servings,time,difficulty,materials,tools,steps,final_images,tips,danger,category
0,https://www.10000recipe.com/recipe/6953727,떡꼬치,떡꼬치를 너무 좋아하는데 요즘 파는곳이 별로 없어서\n간단하게 집에서 한번 만들어봤...,2,15,초급,"가래떡 7개, 식용유 1약간, 케찹 3큰술, 진간장 1/2큰술, 고추장 1큰술, 올...","에어프라이어, 프라이팬, 그릇",[{'text': '떡에 기름을 골고루 조금씩 묻혀 에어프라이어에 돌려줍니다\n18...,[],"저는 이마트에서 2,000원짜리 떡 한팩을 사와서 냉동에 넣지않고 바로 뒷날 해먹었...",0,간식

In [226]:
recipes2 = pd.read_csv('recipes_2000to2054.csv')
recipes2.head(1)

,url,main_image,author,title,description,servings,time,difficulty,materials,tools,video_url,steps,final_images,tips
0,https://www.10000recipe.com/recipe/3680877,https://recipe1.ezmember.co.kr/cache/recipe/20...,카푸치노,시원한 아이스 카페모카 만들기,초콜릿소스를 이용해서 시원한 아이스 카페모카 한잔 어떠신가요~,1인분,10분 이내,초급,"에스프레소 25cc, 찬우유 200cc, 초콜릿소스 30cc, 휘핑크림 적당량, 얼...",NaN,NaN,[{'text': '아테네크리스탈아이스티잔에 초콜릿소스를 넣어주신후에 얼음을 가득 ...,['https://recipe1.ezmember.co.kr/cache/recipe/...,NaN

In [227]:
# recipes 랑 recipes2에서 url이 같은 행 추출해서 recipes에 recipes2에 있는 main_image 컬럼 추가
recipes = recipes.merge(recipes2[['url', 'main_image']], on='url', how='left')
recipes

,url,title,description,servings,time,difficulty,materials,tools,steps,final_images,tips,danger,category,main_image
0,https://www.10000recipe.com/recipe/6953727,떡꼬치,떡꼬치를 너무 좋아하는데 요즘 파는곳이 별로 없어서\n간단하게 집에서 한번 만들어봤...,2,15,초급,"가래떡 7개, 식용유 1약간, 케찹 3큰술, 진간장 1/2큰술, 고추장 1큰술, 올...","에어프라이어, 프라이팬, 그릇",[{'text': '떡에 기름을 골고루 조금씩 묻혀 에어프라이어에 돌려줍니다\n18...,[],"저는 이마트에서 2,000원짜리 떡 한팩을 사와서 냉동에 넣지않고 바로 뒷날 해먹었...",0,간식,https://recipe1.ezmember.co.kr/cache/recipe/20...
1,https://www.10000recipe.com/recipe/6928779,계란빵 꿀빵,계란빵도 먹고 꿀빵도 먹고 즐거운 간식 타임에 모양틀을 이용해 아이와 함께 또는 혼...,2,15,초급,"식빵 4장, 계란 2개, 슬라이스치즈 2장, 소금 1약간, 꿀 1적당량","프라이팬, 주걱, 뒤집개, 계량도구","[{'text': '1 계란빵 만들기\n빵에 구멍을 냅니다', 'images': [...",['https://recipe1.ezmember.co.kr/cache/recipe/...,큼직한 식빵에 만들면 더 쉬워요,0,간식,https://recipe1.ezmember.co.kr/cache/recipe/20...
2,https://www.10000recipe.com/recipe/6728751,고구마 빵,"초간단 노오븐 베이킹. 노버터, 노밀가루라 아기에게 딱!! 건강한 간식이예요",2,30,초급,"고구마 2개, 계란 2개, 올리브유 1약간","계량도구, 필러, 그릇, 주걱, 도마, 전자레인지",[{'text': '고구마는 껍질을 까고 쪄낸 후 뜨거울때 으깨주세요. 고구마가 달...,['https://recipe1.ezmember.co.kr/cache/recipe/...,NaN,0,간식,https://recipe1.ezmember.co.kr/cache/recipe/20...
3,https://www.10000recipe.com/recipe/6880305,또띠아 피자,달걀지단이 들어간\n사과 또띠아 피자!,2,15,초급,"사과 1/4개, 사과잼 3T, 또띠아 1개, 미트소스 3T, 계란 1개, 견과류가루...","그릇, 프라이팬, 도마, 칼, 전자레인지, 가위",[{'text': '* 재료 준비\n또띠아 1개\n사과 1/4개\n사과잼 3T\n미...,['https://recipe1.ezmember.co.kr/cache/recipe/...,NaN,0,간식,https://recipe1.ezmember.co.kr/cache/recipe/20...
4,https://www.10000recipe.com/recipe/6966633,스파게티 샌드위치,"에미넴이 디트로이트에 오픈한 맘스 스파게티 식당에서 파는 ""스파게티 샌드위치"" 궁금...",1,20,아무나,"버터 20g, 다진마늘 1T, 설탕 1t, 파슬리가루 1적당량, 토마토소스 1적당량...","계량도구, 그릇, 전자레인지, 프라이팬",[{'text': '토마토 시판소스를 이용하여 빠르게 토마토스파게티를 만든다 (저는...,['https://recipe1.ezmember.co.kr/cache/recipe/...,마늘빵 사이에 끼워먹는 토마토스파게티\n탄수화물 역시 맛있어\n유투브 구독해줭......,1,양식,https://recipe1.ezmember.co.kr/cache/recipe/20...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86,https://www.10000recipe.com/recipe/6966278,김밥,당근밥으로 만드는 다이어트 김밥,3,20,초급,"밥 2공기, 매실액 1T, 김밥김 5장, 당근 2개, 소금 , 식용유 , 계란 3개...","칼로,주방용 계량도구,도마,프라이팬,주걱",[{'text': '오이는 길쯕하게 썬다.\n오이씨는 물기가 많으니 잘라내버리세요....,['https://recipe1.ezmember.co.kr/cache/recipe/...,NaN,1,간식,https://recipe1.ezmember.co.kr/cache/recipe/20...
87,https://www.10000recipe.com/recipe/6966278,김밥,당근밥으로 만드는 다이어트 김밥,3,20,초급,"밥 2공기, 매실액 1T, 김밥김 5장, 당근 2개, 소금 , 식용유 , 계란 3개...","칼로,주방용 계량도구,도마,프라이팬,주걱",[{'text': '오이는 길쯕하게 썬다.\n오이씨는 물기가 많으니 잘라내버리세요....,['https://recipe1.ezmember.co.kr/cache/recipe/...,NaN,1,간식,https://recipe1.ezmember.co.kr/cache/recipe/20...
88,https://www.10000recipe.com/recipe/6735763,카레라이스,얼마전 일본에서 사왔던 카레로 급 만들어본 일본식 카레라이스~ 물론 카레안에도 고기...,5,30,초급,"고형카레 100g, 물 700ml, 감자 2개, 당근 1개, 양파 1개, 돼지고기 ...","칼, 냄비, 주걱, 프라이팬","[{'text': '재료들은 먹기좋게 썰어 준비하세요.', 'images': ['h...",['https://recipe1.ezmember.co.kr/cache/recipe/...,NaN,1,양식,https://recipe1.ezmember.co.kr/cache/recipe/20...
89,https://www.10000recipe.com/recipe/6881857,쇠고기볶음,아이들이 좋아하는 꼬기~~ 그냥 구워서도 맛있는데 향긋한 미나리 넣어서 볶았더니 향...,2,30,초급,"등심 500g, 미나리 1/2줌, 새송이버섯 100g, 마늘 10개, 청양고추 2개...","계량도구, 칼, 도마, 프라이팬, 주걱","[{'text': '청주 2큰술로 샤워시켜 준 후, 후추와 바질가루 뿌려서 잠깐 재...",[],성장기 어린이들이나 보양식으로 좋은 소고기는 단백질이 풍부해서 입맛 잃기 쉬운 요즘...,1,한식,https://recipe1.ezmember.co.kr/cache/recipe/20...
90,https://www.10000recipe.com/recipe/6881967,김치부침개피자,김치부침개 모두들 좋아하시지요~~~\n\n피자도 좋아하시지요~~~\n\n부침개와 피...,2,30,초급,"김치 1컵, 밀가루 2/3컵, 우유 1/2컵, 모짜렐라 피자치즈 150g, 방울토마...","계량도구, 칼, 도마, 프라이팬, 국자",[{'text': '페파로니 대신 베이컨을 사용하셔도 됩니다~!~\n냉장고에 있는 ...,['https://recipe1.ezmember.co.kr/cache/recipe/...,NaN,1,한식,https://recipe1.ezmember.co.kr/cache/recipe/20...

In [231]:
len(recipes['title'].unique())
# 행 중복 제거
recipes = recipes.drop_duplicates(subset=['title'])
len(recipes)

81

In [232]:
recipes[:1]

,url,title,description,servings,time,difficulty,materials,tools,steps,final_images,tips,danger,category,main_image
0,https://www.10000recipe.com/recipe/6953727,떡꼬치,떡꼬치를 너무 좋아하는데 요즘 파는곳이 별로 없어서\n간단하게 집에서 한번 만들어봤...,2,15,초급,"가래떡 7개, 식용유 1약간, 케찹 3큰술, 진간장 1/2큰술, 고추장 1큰술, 올...","에어프라이어, 프라이팬, 그릇",[{'text': '떡에 기름을 골고루 조금씩 묻혀 에어프라이어에 돌려줍니다\n18...,[],"저는 이마트에서 2,000원짜리 떡 한팩을 사와서 냉동에 넣지않고 바로 뒷날 해먹었...",0,간식,https://recipe1.ezmember.co.kr/cache/recipe/20...

In [233]:
recipes.to_csv("recipes.csv", index=False)

## 메뉴 이름 띄어쓰기 오류 수정

In [234]:
recipes = pd.read_csv('recipes.csv')
recipes['title'].unique()

array(['떡꼬치', '계란빵 꿀빵', '고구마 빵', '또띠아 피자', '스파게티 샌드위치', '치즈 샌드위치',
       '양배추샌드위치', '샌드위치', '연어 샌드위치', '닭가슴살샌드위치', '닭가슴살브리또', '딸기롤샌드위치',
       '에그 샌드위치', '두부 계란찜', '몬테크리스토 샌드위치', '딸기샌드위치', '오픈샌드위치',
       '닭 가슴살 샐러드, 샌드위치', '아보카도 샌드위치', '버터비빔밥', '파니니샌드위치', '치즈샌드위치',
       '오징어 샐러드', '닭가슴살 무침', '게맛살 또띠아 샌드위치', '견과아몬드쿠키', '콩나물무침', '통 삼겹살',
       '옥수수치즈', '소고기\n고구마', '웨지고구마', '누룽지', '크로크무슈', '브라질 치즈빵',
       '얼그레이 사브레 쿠키', '카레구이', '숙주나물무침', '마약달걀장', '멸치고추지볶음', '삼겹살김치파스타',
       '오믈렛', '볶음밥', '토마토 계란 피자', '마늘볶음밥', '알리오 올리오', '해물 토스트',
       '명란젓 마요계란밥', '메밀소바', '모짜프렌치토스트', '참치마요 주먹밥', '상추 주먹밥',
       '들기름 막국수\n간장비빔메밀국수', '아보카도 참치마요 덮밥', '두부 덮밥', '마요네즈계란밥', '찹스테이크',
       '삼겹살 상추 조림', '야채 김 계란말이', '돈까스 샌드위치', '양배추 만둣국', '명란,된장', '참치샐러드',
       '카레 주먹밥', '열무김치국수', '치즈떡 계란말이', '비빔국수', '김치찌개', '콩나물국', '간장파스타',
       '국물떡볶이', '계란빵, 꿀빵', '연어 샐러드', '소세지야채볶음', '달걀 볶음밥', '두부찌개',
       '데리야키 닭고기', '몬테크리스토 시리얼 토스트', '김밥', '카레라이스', '쇠고기볶음', '김치부침개피자'],
      dtype=object)

In [238]:
recipes['title'] = recipes['title'].str.replace('\\n', ' ', regex=True)
recipes['title'].unique()
recipes.to_csv("recipes.csv", index=False)

In [235]:
recipes_tool = pd.read_csv('recipes_tools.csv')
recipes_tool['title'].unique()

array(['떡꼬치', '계란빵 꿀빵', '고구마 빵', '또띠아 피자', '스파게티 샌드위치', '치즈 샌드위치',
       '양배추샌드위치', '샌드위치', '연어 샌드위치', '닭가슴살샌드위치', '닭가슴살브리또', '딸기롤샌드위치',
       '에그 샌드위치', '두부 계란찜', '몬테크리스토 샌드위치', '딸기샌드위치', '오픈샌드위치',
       '닭 가슴살 샐러드, 샌드위치', '아보카도 샌드위치', '버터비빔밥', '파니니샌드위치', '치즈샌드위치',
       '오징어 샐러드', '닭가슴살 무침', '게맛살 또띠아 샌드위치', '견과아몬드쿠키', '콩나물무침', '통 삼겹살',
       '옥수수치즈', '소고기\r\n고구마', '웨지고구마', '누룽지', '크로크무슈', '브라질 치즈빵',
       '얼그레이 사브레 쿠키', '카레구이', '숙주나물무침', '마약달걀장', '멸치고추지볶음', '삼겹살김치파스타',
       '오믈렛', '볶음밥', '토마토 계란 피자', '마늘볶음밥', '알리오 올리오', '해물 토스트',
       '명란젓 마요계란밥', '메밀소바', '모짜프렌치토스트', '참치마요 주먹밥', '상추 주먹밥',
       '들기름 막국수\r\n간장비빔메밀국수', '아보카도 참치마요 덮밥', '두부 덮밥', '마요네즈계란밥', '찹스테이크',
       '삼겹살 상추 조림', '야채 김 계란말이', '돈까스 샌드위치', '양배추 만둣국', '명란,된장', '참치샐러드',
       '카레 주먹밥', '열무김치국수', '치즈떡 계란말이', '비빔국수', '김치찌개', '콩나물국', '간장파스타',
       '국물떡볶이', '계란빵, 꿀빵', '연어 샐러드', '소세지야채볶음', '달걀 볶음밥', '두부찌개',
       '데리야키 닭고기', '몬테크리스토 시리얼 토스트', '김밥', '카레라이스', '쇠고기볶음', '김치부침개피자'],
      dtype=object)

In [ ]:
recipes_tools['title'] = recipes_tools['title'].str.replace('\\n', ' ', regex=True)
recipes_tools['title'].unique()

array(['떡꼬치', '계란빵 꿀빵', '고구마 빵', '또띠아 피자', '스파게티 샌드위치', '치즈 샌드위치',
       '양배추샌드위치', '샌드위치', '연어 샌드위치', '닭가슴살샌드위치', '닭가슴살브리또', '딸기롤샌드위치',
       '에그 샌드위치', '두부 계란찜', '몬테크리스토 샌드위치', '딸기샌드위치', '오픈샌드위치',
       '닭 가슴살 샐러드, 샌드위치', '아보카도 샌드위치', '버터비빔밥', '파니니샌드위치', '치즈샌드위치',
       '오징어 샐러드', '닭가슴살 무침', '게맛살 또띠아 샌드위치', '견과아몬드쿠키', '콩나물무침', '통 삼겹살',
       '옥수수치즈', '소고기 고구마', '웨지고구마', '누룽지', '크로크무슈', '브라질 치즈빵',
       '얼그레이 사브레 쿠키', '카레구이', '숙주나물무침', '마약달걀장', '멸치고추지볶음', '삼겹살김치파스타',
       '오믈렛', '볶음밥', '토마토 계란 피자', '마늘볶음밥', '알리오 올리오', '해물 토스트',
       '명란젓 마요계란밥', '메밀소바', '모짜프렌치토스트', '참치마요 주먹밥', '상추 주먹밥',
       '들기름 막국수 간장비빔메밀국수', '아보카도 참치마요 덮밥', '두부 덮밥', '마요네즈계란밥', '찹스테이크',
       '삼겹살 상추 조림', '야채 김 계란말이', '돈까스 샌드위치', '양배추 만둣국', '명란,된장', '참치샐러드',
       '카레 주먹밥', '열무김치국수', '치즈떡 계란말이', '비빔국수', '김치찌개', '콩나물국', '간장파스타',
       '국물떡볶이', '계란빵, 꿀빵', '연어 샐러드', '소세지야채볶음', '달걀 볶음밥', '두부찌개',
       '데리야키 닭고기', '몬테크리스토 시리얼 토스트', '김밥', '카레라이스', '쇠고기볶음', '김치부침개피자'],
      dtype=object)

In [241]:
recipes_tools.to_csv("recipes_tools.csv", index=False)

In [236]:
recipes_ingredients = pd.read_csv('recipes_ingredients.csv')
recipes_ingredients['title'].unique()

array(['떡꼬치', '계란빵 꿀빵', '고구마 빵', '또띠아 피자', '스파게티 샌드위치', '치즈 샌드위치',
       '양배추샌드위치', '샌드위치', '연어 샌드위치', '닭가슴살샌드위치', '닭가슴살브리또', '딸기롤샌드위치',
       '에그 샌드위치', '두부 계란찜', '몬테크리스토 샌드위치', '딸기샌드위치', '오픈샌드위치',
       '닭 가슴살 샐러드, 샌드위치', '아보카도 샌드위치', '버터비빔밥', '파니니샌드위치', '치즈샌드위치',
       '오징어 샐러드', '닭가슴살 무침', '게맛살 또띠아 샌드위치', '견과아몬드쿠키', '콩나물무침', '통 삼겹살',
       '옥수수치즈', '소고기 고구마', '웨지고구마', '누룽지', '크로크무슈', '브라질 치즈빵',
       '얼그레이 사브레 쿠키', '카레구이', '숙주나물무침', '마약달걀장', '멸치고추지볶음', '삼겹살김치파스타',
       '오믈렛', '볶음밥', '토마토 계란 피자', '마늘볶음밥', '알리오 올리오', '해물 토스트',
       '명란젓 마요계란밥', '메밀소바', '모짜프렌치토스트', '참치마요 주먹밥', '상추 주먹밥',
       '들기름 막국수 간장비빔메밀국수', '아보카도 참치마요 덮밥', '두부 덮밥', '마요네즈계란밥', '찹스테이크',
       '삼겹살 상추 조림', '야채 김 계란말이', '돈까스 샌드위치', '양배추 만둣국', '명란,된장', '참치샐러드',
       '카레 주먹밥', '열무김치국수', '치즈떡 계란말이', '비빔국수', '김치찌개', '콩나물국', '간장파스타',
       '국물떡볶이', '계란빵, 꿀빵', '연어 샐러드', '소세지야채볶음', '달걀 볶음밥', '두부찌개',
       '데리야키 닭고기', '몬테크리스토 시리얼 토스트', '김밥', '카레라이스', '쇠고기볶음', '김치부침개피자'],
      dtype=object)